### ISSUE TITLE
Status Colour change

### ISSUE THREAD

**Issue by barryboom** [donaldzou/WGDashboard#100]
**Is your feature request related to a problem? Please describe.**
very slight improbement visually but i fine tthe status colour difficult to differratiate between the green and grey as below

![Statuscolour](https://user-images.githubusercontent.com/67483859/140647348-db170475-0c8a-48ac-936a-af6821097357.png)

**Describe the solution you'd like**
simple enough idea am sure but a brighter green and maybe offline RED will allow at a quick glance to view the status i do know that i can check latest handshake and metrics for the data send / recieved etc but if this is easy to would be a nice improvement

**Comment by donaldzou** [comment]
Hi @barryboom, thank you for making this suggestion! Yes I do realize this problem when I'm using the dashboard, I will make adjustment on it!

**Comment by donaldzou** [comment]
This issue has been fixed in the next release!
