### ISSUE TITLE
Looking for a better way to distribute releases of WGDashboard 

### ISSUE THREAD

**Issue by donaldzou** [donaldzou/WGDashboard#103]

**Comment by TomAtHarvestThermal** [comment]
I researched this a few days ago for another app I am involved in.  Here are some options:

- https://docs.python.org/3/library/zipapp.html
- https://lincolnloop.com/blog/dissecting-python-zipapp-built-shiv/
- https://pyoxidizer.readthedocs.io/en/stable/pyoxidizer_comparisons.html

Docker is probably the go-to solution.

Given the security concerns of interfacing with WireGuard it may be wise to reduce dependencies to a minimum.

**Comment by barryboom** [comment]
please avoid docker really dont like woeking with docker and not as easy to use and implament for novices where as your current soloution is easy to follow and works for everyone

**Comment by ikidd** [comment]
I'm currently running it in a Ubuntu 20.04 VM but would run as a docker as well, though it would complicate routing. If you weren't routing to anything outside the WG server, docker would be a simpler way to deploy, but keeping the ability to just git pull and use it is pretty important.

**Comment by marneu** [comment]
I'd rather vote for a "python virtual environment". That would remain out of the github space but can easily be packaged.

**Comment by donaldzou** [comment]
> please avoid docker really dont like woeking with docker and not as easy to use and implament for novices where as your current soloution is easy to follow and works for everyone

I agree to this, docker isn't a good way for this project, since i need to wrap both the dashboard and WireGuard into one container.

**Comment by donaldzou** [comment]
> I'm currently running it in a Ubuntu 20.04 VM but would run as a docker as well, though it would complicate routing. If you weren't routing to anything outside the WG server, docker would be a simpler way to deploy, but keeping the ability to just git pull and use it is pretty important.

I will definitely keep the git method, but i'm looking for a more "elegant" way to let user update the dashboard, instead of using `git pull <url> <version_number>` ;) and sometimes the update in the bash script `wgd.sh` isn't working perfectly.

**Comment by donaldzou** [comment]
> I'd rather vote for a "python virtual environment". That would remain out of the github space but can easily be packaged.

Do you have any good documentation on this? Since I never use this before. Thanks in advanced!

**Comment by donaldzou** [comment]
I guess I will keep using GitHub to distribute new versions ;)

**Comment by mzs114** [comment]
The current process seems ok, do consider OpenSuse OBS to support native packages. 
Imo, avoid docker, keep it agnostic, so people can run this on LXC, BSD Jails or Podman,  or a plain old VM.  :)

**Comment by donaldzou** [comment]
Hi @mzs114 , yes currently I'm keeping this process as I think is the simplest way for this project.
