### ISSUE TITLE
Auto detect Peer name and Private address

### ISSUE THREAD

**Issue by barryboom** [donaldzou/WGDashboard#104]
**Is your feature request related to a problem? Please describe.**
Not sure if this is normal or becuase i use my own wireguard install script but my wg0.conf file in etc\wireguard folder contains the names of my clients like below:

# test1234
[Peer]
PublicKey = UMW/cydSpcvabcdefgghnmixN+0y9DkCwU=
AllowedIPs = 10.9.0.4/32
# test101
[Peer]
PublicKey = tifdTs9qqBUZdNaabcdefghijklSpY4bgiJoiw=
AllowedIPs = 10.9.0.5/32
# test656575
[Peer]
PublicKey = m2051Ay622pB4dabcdefghijklWzujC/4RYlo=
AllowedIPs = 10.9.0.6/32

![image](https://user-images.githubusercontent.com/67483859/143309289-1dbe4304-df6d-4116-b6ee-f2d2943c3f1e.png)

**Describe the solution you'd like**
Would be good if the dashboard was able to read and apply the names for the peers instead of having to go in and manually add the names.

the way i have to do this manually is by looking at the AllowedIPs and matching up with client and renaming.

This also got me looking as well at my manual soloution to add private key to allow QR Code etc. where by i look at the files stored in the the /Root named as above i.e test1234-wg0.conf and then open and copy the private key.

Would be great if some logic could be applied to extract and apply this automatically

**Comment by donaldzou** [comment]
Hi! There are tons of way to name peers in the config file so is hard to get the name by reading the comments, and is not practical to just search config file for peers, since some people might not configure theirs like you did :) But still thank you for bringing this enhancement!
