### ISSUE TITLE
Sign In page renders in pretty ugly fonts, style and spacing.

### ISSUE THREAD

**Issue by ikidd** [donaldzou/WGDashboard#107]
https://i.imgur.com/i6oY7j5.png

Not sure if this is a Firefox thing or what.  IIRC, it works fine on a Windows machine using Firefox.  I'm guessing there's a font specified in the stylesheet (bootstrap something) that isn't on my machines.

The actual interface screen renders ok:

https://i.imgur.com/RxfsiAf.png

Though I'm not sure if that's the font I saw when using it on Windows.

Served with V 2.3.1 on Ubuntu 20.04

**Comment by donaldzou** [comment]
Hmmmm, this is interesting. Could you provide the console output on your browser when you opened the signin page? Thanks!
