### ISSUE TITLE
Connection doesn't work without preshared key

### ISSUE THREAD

**Issue by kundancool** [donaldzou/WGDashboard#109]
**Describe The Problem**
Without preshared key for client and server it doesn't work for me connection gets active but there is no traffic but once I add preshared key it works.

**Expected Error / Traceback**
```
Please provide the error traceback here
```

**To Reproduce**
Please provide how you run the dashboard

**OS Information:**
 - OS: Ubuntu 20.04
 - Python Version: Python 3.8.10

**Sample of your `.conf` file**
```
[Interface]
PrivateKey = uHRfKR+/Z7LQatN2am/Ynq0aCr6BEVFaGKhukTBu+GA=
Address = 10.66.66.2/32,fd42:42:42::2/128
DNS = 1.1.1.1,8.8.8.8

[Peer]
PublicKey = olTLWgKTXly0lPJESx1XcSzkjpFXuvsNn2FHJp5tmFA=
PresharedKey = bg5c0ovpVPogoXEsyGYePOpseDoikqsRoefe6wXG5rk=
Endpoint = X.X.X.X:59050
AllowedIPs = 0.0.0.0/0,::/0
```

**Comment by ikidd** [comment]
You might try adding a PersistentKeepalive to the client conf file.  For some reason, the client configuration it generates and you download doesn't put this in if you've set it in the peer setting.  But if you're trying to ping from the server side and it hasn't opened the tunnel from the client side with keepalive, you won't get a response even if the handshake goes ahead.
