### ISSUE TITLE
点击configuration的wg0 起来后  页面不会再刷新

### ISSUE THREAD

**Issue by 171285296** [donaldzou/WGDashboard#110]
![image](https://user-images.githubusercontent.com/51934903/145344794-46252f75-1023-4c05-8424-ccf8c5c79886.png)

**Comment by donaldzou** [comment]
嗨，您好，因为这个Issue长期没有更新，我需要关闭掉了。如果你还有遇到这样的情况，请重新再Open一个Issue。感谢您的理解 ;)
