### ISSUE TITLE
Distributed wireguard and dashboard with podman/docker and ansible

### ISSUE THREAD

**Issue by pgalonza** [donaldzou/WGDashboard#123]
I can added instructions and files for example of my repository [wireguard-image](https://gitlab.com/pgalonza/wireguard-image/-/tree/develop/) how install wireguard with dashboard in container with podman and ansible

**Comment by donaldzou** [comment]
For sure! I'll link your repo on the readme for v3.0 ;) Big thanks on helping with Gunicorn!

**Comment by donaldzou** [comment]
Or do you have a set of instructions I could put on?

**Comment by pgalonza** [comment]
> For sure! I'll link your repo on the readme for v3.0 ;) Big thanks on helping with Gunicorn!

Thank you for this great project. I using it with pleasure.

**Comment by pgalonza** [comment]
> Or do you have a set of instructions I could put on?

I will try to do it soon.
