### ISSUE TITLE
Does this need to be run within a docker?

### ISSUE THREAD

**Issue by MehrabD123** [donaldzou/WGDashboard#130]
**Describe The Problem**
I am having issues trying to access the web interface, i have followed the installation instructions and i know it is running but when i try to access it using my-ip:10086 nothing loads.

 - OS: Raspbian GNU/Linux11
 - Python Version: 3.9.2

**Comment by donaldzou** [comment]
Hi, this doesn't need to be run on docker. Could you provide a step-by-step how you install the dashboard? Thanks!

**Comment by MehrabD123** [comment]
so i followed step by step the installation instructions on the main page for this program.
i downloaded the dashboard, opened the folder, installed the dashboard, gave permissions then started the program
i tried accessing it using my raspberrypi-ip:10086 to no avail so im not certain which IP im supposed to connect with if it is different from my PI's IP

**Comment by donaldzou** [comment]
I see, could you try: `./wgd.sh stop && ./wgd.sh debug` and post the output here please? Thank you!

**Comment by MehrabD123** [comment]
so this time when running in debug mode it connects to the interface but gives me a 500 internal server error
ive posted the debug output below
![Screenshot 2022-01-18 135630](https://user-images.githubusercontent.com/66188122/150001160-76cbea67-72fc-449a-8050-5f719b7dd072.png)

**Comment by donaldzou** [comment]
This seems like a database issue... could you try to run it with `sudo ./wgd.sh debug`? There are some permission issue with Pi OS before

**Comment by MehrabD123** [comment]
that seems to have fixed it! running it with sudo allowed it to start
i still attached the log below if that helps, should i just run the sudo ./wgd.sh start command instead of without sudo?
![Screenshot 2022-01-18 140347](https://user-images.githubusercontent.com/66188122/150002033-a0df772c-d316-49e1-851a-5ac8d3e1b018.png)

**Comment by donaldzou** [comment]
Yes, `sudo ./wgd.sh start` would work! If you doesn't want it to run with sudo, i guess you can give read and write permission to the whole directory ;)
