### ISSUE TITLE
ERR_NETWORK_ACCESS_DENIED

### ISSUE THREAD

**Issue by MrHumanRebel** [donaldzou/WGDashboard#136]
When I try to log in when connected to the WG VPN I get this error in Chrome:
ERR_NETWORK_ACCESS_DENIED

As soon as I disconnect from the VPN it is working again.
What could be the problem?

System:    Kernel: 5.4.0-96-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Xfce 4.16.0 
           tk: Gtk 3.24.20 wm: xfwm4 dm: LightDM Distro: Linux Mint 20.3 Una 
           base: Ubuntu 20.04 focal

**Comment by donaldzou** [comment]
Hi, I'm sorry you encountered problems. Is your server running in the same network as your client? Such as your server is `192.168.1.4` and you are `192.168.1.8`

**Comment by MrHumanRebel** [comment]
Yes, the server is 192.XXX.Y.197 and the PC is 192.XXX.Y.195

**Comment by donaldzou** [comment]
Yes, that's what i'm thinking. That is because your server is under `192.xxx.x.197` and your WireGuard interface is not under the same subnet. Did you enable `net.ipv4.ip_forward=1`?

**Comment by MrHumanRebel** [comment]
That is a good tip, gonna try it out! Thank you mate! :D Keep on, this page is amazing.

**Comment by donaldzou** [comment]
No problem, please let me know if i can help for any other questions! I'm glad you like this project ;)
