### ISSUE TITLE
Internal Service Error on Ubuntu and RPi3

### ISSUE THREAD

**Issue by Gyrohammer** [donaldzou/WGDashboard#137]
**Describe The Problem**
Cannot login to dashboards on either a Ubuntu or a RPi install. Ubuntu install was installed with fresh WireGuard install, RPi install had an already configured WireGuard setup. 

Attempting to login with the dashboard with the default username admin and password admin results in an internal server error:
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

```
**Expected Error / Traceback**
For Ubuntu:
```
[2022-01-24 11:47:39,116] ERROR in app: Exception on /auth [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "dashboard.py", line 704, in auth
    password = hashlib.sha256(data['password'].encode())
TypeError: 'NoneType' object is not subscriptable'
```

For RPi:
```
[2022-01-24 11:41:35,080] ERROR in app: Exception on /auth [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "dashboard.py", line 704, in auth
    password = hashlib.sha256(data['password'].encode())
TypeError: 'NoneType' object is not subscriptable
```
Sidenote: Are my user permissions bad? I see the traceroute says fail on /auth is that for my authentication or is that on wg-dashboard? This error is the same across two distros so it must be something consistent with either wg-dashboard or my network.

**To Reproduce**
I did a fresh install of both wg-dashboard and wireguard into their default directories running them with `./wgd.sh start`. I then tried to access them via the ip and port with default credentials. Upon entering credentials I am greeted with an internal server error. 

**OS Information:**
 - OS: Ubuntu 20..04.1
 - Python Version: 3.8.10

 - OS: Linux 5.10.63-v7+
 - Python Version: 3.7.3

**Sample of your `.conf` file**
Ubuntu: 
```
[Interface]
Address = 10.0.0.1/24
SaveConfig = true
ListenPort = 51820
PrivateKey = ABCD
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o wlp0s20f3 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o wlp0s20f3 -j MASQUERADE
```

RPi:
```
[Interface]
Address = 10.100.0.1/32
ListenPort = 47111
PrivateKey = ABCD
DNS = 192.168.50.25

PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE


[Peer]
#x360
PublicKey = ABCD
PresharedKey = ABCD
AllowedIPs = 10.100.0.2/32, fd08:4711::2/128, 192.168.0.0/24
```
If any more information is required please let me know! I know I'm prone to making simple errors sometimes lol

**Comment by donaldzou** [comment]
Hi, i'm sorry that you encountered problems. Would you mind telling me which browser did you used?

**Comment by Gyrohammer** [comment]
All good! Problems happen especially with homebrew stuff, no sweat 👍 

I'm using the Brace browser (chromium based I think). I just tried Firefox and got the same result:
```[2022-01-24 12:26:31,733] ERROR in app: Exception on /auth [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "dashboard.py", line 704, in auth
    password = hashlib.sha256(data['password'].encode())
TypeError: 'NoneType' object is not subscriptable
```

I may have misunderstood the order of operations for this dashboard so I will attempt to clarify my thoughts:

Does there need to be an initial peer set up to connect to the WG tunnel? I assumed one could do a fresh WG install without any peers, connect to the dashboard from any PC on their LAN, and _then_ create peers that way. 

If you need clarification let me know, when I translate thoughts-to-words I usually tend to overcomplicate, sorry!

**Comment by donaldzou** [comment]
This is weird. I will check on the front-end code, it seems like when you click **Sign In**, it did not send the password to the server, so it caused the issue. I will get back to you as soon ass possible ;)

**Comment by donaldzou** [comment]
> Does there need to be an initial peer set up to connect to the WG tunnel? I assumed one could do a fresh WG install without any peers, connect to the dashboard from any PC on their LAN, and then create peers that way.

As for this, you don't need to configure initial peers to have it work, as long as you have an initial configuration, then you can add peers with the dashboard ;)

**Comment by Gyrohammer** [comment]
> This is weird. I will check on the front-end code, it seems like when you click **Sign In**, it did not send the password to the server, so it caused the issue. I will get back to you as soon ass possible ;)

Thanks so much! I really appreciate it.

> > Does there need to be an initial peer set up to connect to the WG tunnel? I assumed one could do a fresh WG install without any peers, connect to the dashboard from any PC on their LAN, and then create peers that way.
> 
> As for this, you don't need to configure initial peers to have it work, as long as you have an initial configuration (empty configuration with no peers), then you can add peers with the dashboard ;)

Ok cool so my brain is working correctly, thank goodness haha

**Comment by donaldzou** [comment]
Hmmm.. I've test couple of times on my side with different browser and they all works well. Could you briefly tell me how did you sign in? I will continue to look into the code to see if anything that is causing the trouble ;)

**Comment by Gyrohammer** [comment]
> Hmmm.. I've test couple of times on my side with different browser and they all works well. Could you briefly tell me how did you sign in? I will continue to look into the code to see if anything that is causing the trouble ;)

Sure; I navigated into the IP of the host using the default port, entered admin into the username space and admin into the password space and then hit sign in. After doing that I get the server internal error.

**Comment by donaldzou** [comment]
Hmm.. Do you mind help me to debug something? I made a GIF on what i'm looking for. Basically I want to know if the browser did send the username and password to the server.
![ezgif-2-83f40a0571](https://user-images.githubusercontent.com/25237201/150901433-7ad7c196-15e0-409e-aba0-2cbab321a8ac.gif)

**Comment by Gyrohammer** [comment]
Yeah sure! Be back in a few minutes.

**Comment by donaldzou** [comment]
Thank you!!

**Comment by Gyrohammer** [comment]
![image](https://user-images.githubusercontent.com/78768460/150902431-53a81700-5079-4fd3-bf61-04be3c7a9899.png)

Got the following out. Could if be my windows firewall blocking the submission...? Will test that out with port cleared from windows firewall side.

**Comment by donaldzou** [comment]
Hmm but if that's the case, you won't even able to open the webpage. Is this a screenshot from Brave?

**Comment by Gyrohammer** [comment]
Yup its a screenshot from Brave, I'll do the same sequence in chrome and post the result.

**Comment by donaldzou** [comment]
It seems like, you did a "Form" post, instead of a ajax post... So basically your webpage file is from an older version, and the server (python codes) is from a new version. Do you mind updating the server and try it out? You can follow this https://github.com/donaldzou/WGDashboard#update-method-2 to update the dashboard

**Comment by Gyrohammer** [comment]
![image](https://user-images.githubusercontent.com/78768460/150904477-14931265-43b1-4a47-9d6a-f308a2546464.png)

Attempted update, got return that it was latest image, attempted login again and got same error.

**Comment by donaldzou** [comment]
This got me thinking... Did you disabled Javascript on your browser?

**Comment by Gyrohammer** [comment]
GOT IT 

Holy moly this one is extremely unique to me. I recently set up some blocklists on my Pi-Hole and one of them was blocking
 ```
code.jquery.com
(blocked cds.s5x3j6q5.hwcdn.net)
```

After adding that to the whitelist the login works _perfectly_. 

Thanks so much for your help @donaldzou! Sorry this took so long and ended up being such a niche use-case.

**Comment by donaldzou** [comment]
Ahah nice!! I would consider to move all dependencies to local. But the reason is flask running on HTTP 1.1, and it need to wait for resources 1 by 1, so would cause longer loading time. By using CDN can have faster loading speed on scripts and CSS libraries. I will close this issue now, if you have any more questions please let me know!!
