### ISSUE TITLE
Upgrade instructions don't work 

### ISSUE THREAD

**Issue by barryboom** [donaldzou/WGDashboard#138]
upgrade instructions as below do not seem to work currently running V3.0 on Ubuntu 20.04

Change your directory to wgdashboard

cd wgdashboard

Update the dashboard

git pull https://github.com/donaldzou/WGDashboard.git v3.0.3 --force

Install

./wgd.sh install

this is the output from SSH

Last login: Mon Jan 24 19:22:08 2022 from 80.235.145.203
root@vpn:~# cd wgdashboard
root@vpn:~/wgdashboard# git pull https://github.com/donaldzou/WGDashboard.git v3.0.3 --force
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 18 (delta 9), reused 17 (delta 9), pack-reused 0
Unpacking objects: 100% (18/18), 27.69 KiB | 1.20 MiB/s, done.
From https://github.com/donaldzou/WGDashboard
 * tag               v3.0.3     -> FETCH_HEAD
Updating 9f8559c..af71176
Fast-forward
 README.md                          | 20 +++++++++++++-------
 src/dashboard.py                   | 15 ++++++++-------
 src/static/js/configuration.js     | 10 ++++++++++
 src/static/js/configuration.min.js |  2 +-
 src/templates/configuration.html   |  2 +-
 src/wgd.sh                         |  1 +
 6 files changed, 34 insertions(+), 16 deletions(-)
root@vpn:~/wgdashboard# ./wgd.sh update
-bash: ./wgd.sh: No such file or directory
root@vpn:~/wgdashboard# ./wgd.sh install
-bash: ./wgd.sh: No such file or directory
root@vpn:~/wgdashboard#

**Comment by donaldzou** [comment]
> root@vpn:/wgdashboard# ./wgd.sh install
-bash: ./wgd.sh: No such file or directory
root@vpn:~/wgdashboard#

Hi, that is because you're not in `wgdashboard/src` according to your terminal output

**Comment by barryboom** [comment]
instructions dont advise to go to wgdashboard/src only CD wgdashboard

![image](https://user-images.githubusercontent.com/67483859/150856223-e60210d3-7cbb-4196-8c87-31f2f582ff72.png)

**Comment by donaldzou** [comment]
Ohhh I see, sorry about that, I will fix it right away, thank you for letting me know ;)
