### ISSUE TITLE
Keys matching issues

### ISSUE THREAD

**Issue by LimonFruit** [donaldzou/WGDashboard#141]
**Describe The Problem**
Private key does not match with Public Key.

**To Reproduce**
On the section of adding a new peer, if you manually enter a Private Key, it will not match with the Public Key. However, if you generate a Private Key using WGDashboard, it will match with the Public Key.  It's only when you manually enter a Private Key where it will not match with the Public Key. 

**OS Information:**
 - OS: Ubuntu 20.04
 - Python Version: 3.8.10

Running on v3.0.3. This was not an issue on v2.3.1.

I figured I should let you know just in case :)

**Comment by donaldzou** [comment]
Hi, thank you for letting me know, I will look into it right away.

**Comment by donaldzou** [comment]
Hi, do you mind provide the set of keys you are using. Please be assured that I won't be able to get any personal information just from the set of keys. I've also tried multiple keys that generated from the WireGuard desktop app and the dashboard works well.
![Screen Shot 2022-01-26 at 11 51 49 AM](https://user-images.githubusercontent.com/25237201/151209303-ac22190d-baef-4b80-a404-bd1b982328db.png)

**Comment by LimonFruit** [comment]
Yes the Private Key that I was using as a test is 

`OMjc72M88/5CftRQ+oPexPADrn+KUcEDEzjgTP/rHkE=`


When using WGDashboard v3.0.3, I get this results shown here:

![v3 0 3](https://user-images.githubusercontent.com/98423489/151226263-db814b06-4d7b-4568-896e-f3bb7821d6b3.jpg)


But when I'm using WGDashboard v2.3.1, I get this results shown here. Which is the correct Public Key:

![v2 3 1](https://user-images.githubusercontent.com/98423489/151226494-02a6d972-38d9-486e-8bff-667b9da85c67.jpg)

**Comment by donaldzou** [comment]
This issue has been fixed in the newest release `v3.0.4` ;)
