### ISSUE TITLE
The version in the latest tag 3.0.4 was not adjusted

### ISSUE THREAD

**Issue by tbnobody** [donaldzou/WGDashboard#144]
**Describe The Problem**
The version in the latest tag 3.0.4 was not adjusted
https://github.com/donaldzou/WGDashboard/blob/0d858493d5fb3357c1f6154b445fffb469a13a4e/src/dashboard.py#L34

Therefor, even after a update the GUI shows that an update is available...

**Comment by donaldzou** [comment]
Sorry about that, now should be good to go ;)
