### ISSUE TITLE
Autostart configuration fails

### ISSUE THREAD

**Issue by tokon2000** [donaldzou/WGDashboard#150]
Hi!

What is the right way to configure the autostart at the moment?
As there is a comment "A more automated approach" at wg-dashboard.service, I thougt manual editing the directory is not necessary any more.
Isn't filled {{VIRTUAL_ENV}} and {{APP_ROOT}} automatically?

If I try to start the service, status is showing "WorkingDirectory= path is not absolute: {{APP_ROOT}}"

So I entered the directory manually and it works.

OS: Debian 11

Best Regards!

**Comment by barryboom** [comment]
Same issues on Ubunutu Autostart after reboot instructions no longer work and need t be reviewed and surely must be an easier way to make this change as well.

**Comment by donaldzou** [comment]
Hi, sorry for the late reply, it was my problem didn't fix that. But for reference, you can check out an old version (`v2.3`) that have a working solution on it: https://github.com/donaldzou/WGDashboard/tree/v2.3

**Comment by DaanSelen** [comment]
Is this still relevant?
