### ISSUE TITLE
gunicorn: command not found

### ISSUE THREAD

**Issue by raldridgenctm** [donaldzou/WGDashboard#152]
Seeing this error on start:

| Starting WGDashboard with Gunicorn in the background.    |
./wgd.sh: line 104: gunicorn: command not found

Ubuntu server 20.04.4
Python 3.8
pip 20.0.2

*Update - installed gunicorn, getting this error now:

Failed to read config file: /home/*****user/wgdashboard/src/gunicorn.conf.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/*****user/wgdashboard/src/gunicorn.conf.py", line 2, in <module>
    import dashboard
  File "/home/*****user/wgdashboard/src/dashboard.py", line 7, in <module>
    from flask import g
ModuleNotFoundError: No module named 'flask'

*Update2:

ran start command from user home and it found gunicorn.conf.py file.

**Comment by donaldzou** [comment]
Hi did you run `./was.sh install`?

**Comment by raldridgenctm** [comment]
Yes, it's running now, but the site's not loading.  Getting ready to check logs.

**Comment by donaldzou** [comment]
You can run `./wgd.sh debug` to let it run in on foreground.

**Comment by raldridgenctm** [comment]
OK, started over and realized I didn't have pip installed or Gunicorn installed prior to the install.  so reinstalled.  Now starting seems to happen without errors.  site still doesn't load.  running in debug mode now, seeing this error:

sqlite3.OperationalError: unable to open database file

**Comment by donaldzou** [comment]
> OK, started over and realized I didn't have pip installed or Gunicorn installed prior to the install. so reinstalled. Now starting seems to happen without errors. site still doesn't load. running in debug mode now, seeing this error:
> 
> sqlite3.OperationalError: unable to open database file

Hmm could you try to kill the process, and do `sudo ./wgd.sh start` to see if it helps?

**Comment by raldridgenctm** [comment]
I saw this thread:

https://github.com/donaldzou/WGDashboard/issues/142

running as sudo produces new errors in finding the conf files.  But chown on the wgdashboard folder to the user, and running as not sudo finally got everything working.

**Comment by raldridgenctm** [comment]
Unfortunately, now when I try to toggle WG, it won't let me since I'm not sudo, and I can't add a new client as it claims wg0 isn't running, but it is.

**Comment by raldridgenctm** [comment]
removed the folder and started a fresh install.  everything is working correctly now.  Seems I didn't have requirements installed prior to the installation.  Please remove this case.  Thanks!

**Comment by donaldzou** [comment]
I'm glad everything worked!
