### ISSUE TITLE
Select available IP

### ISSUE THREAD

**Issue by cirrusflyer** [donaldzou/WGDashboard#153]
When I add a new peer and use the "search available IPs", the "select available IP" list is empty.
![Selection_058](https://user-images.githubusercontent.com/33668552/155813678-e4d13858-26a6-4489-b5e4-94f343ecbe9c.png)

**Comment by tokon2000** [comment]
Is it a IPv4-only config or IPv4+IPv6?

**Comment by cirrusflyer** [comment]
both, but doesn't need to be. could change to IPv4 only if that helps.

**Comment by tokon2000** [comment]
If I tested with IPv4-only, I got the list. With 4+6 the list was empty. And also issue #151

**Comment by cirrusflyer** [comment]
Thanks.  I switched to IPv4 only and it's working fine now.  Thanks
