### ISSUE TITLE
presented this error

### ISSUE THREAD

**Issue by eduardorosabales** [donaldzou/WGDashboard#154]
Good just installed, and this happens to me;

| Starting WGDashboard with Gunicorn in the background.    |
Failed to read config file: /root/wgdashboard/src/gunicorn.conf.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/wgdashboard/src/gunicorn.conf.py", line 2, in <module>
    import dashboard
  File "/root/wgdashboard/src/dashboard.py", line 7, in <module>
    from flask import g
ModuleNotFoundError: No module named 'flask'
| Log files is under log/               

**how can I solve it?**

**Comment by tokon2000** [comment]
There are missing some requirements. Same problem as #152

**Comment by donaldzou** [comment]
> Good just installed, and this happens to me;
> 
> 
> 
> | Starting WGDashboard with Gunicorn in the background.    |
> 
> Failed to read config file: /root/wgdashboard/src/gunicorn.conf.py
> 
> Traceback (most recent call last):
> 
>   File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
> 
>     spec.loader.exec_module(mod)
> 
>   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
> 
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> 
>   File "/root/wgdashboard/src/gunicorn.conf.py", line 2, in <module>
> 
>     import dashboard
> 
>   File "/root/wgdashboard/src/dashboard.py", line 7, in <module>
> 
>     from flask import g
> 
> ModuleNotFoundError: No module named 'flask'
> 
> | Log files is under log/               
> 
> 
> 
> **how can I solve it?**

Hi! I'm wondering did you run `./wgd.sh install`?

**Comment by eduardorosabales** [comment]
my solution was to install the missing pip dependency, then delete the folder and run the install again.

Thank you all.
