### ISSUE TITLE
I can't access the interface remotely

### ISSUE THREAD

**Issue by eduardorosabales** [donaldzou/WGDashboard#155]
if you can help me...and installed correctly the server tells me started, but now when I try to access that server from the internet by putting the server's ip with the port on which it was turned on and then it doesn't access the interface it's as if It wasn't there...and to check, I ping the server's IP from outside and if it responds.

**Comment by eduardorosabales** [comment]
I also solved by directing the traffic to port 80

**Comment by donaldzou** [comment]
Hi, I'm sorry for late reply. I'm thinking it might your server's firewall that blocked port `10086` or maybe your server provider that blocked that port. Let me know if you fixed it ;)

**Comment by eduardorosabales** [comment]
If the problem is solved, it was exactly that
