### ISSUE TITLE
include PostUp and PostDown

### ISSUE THREAD

**Issue by grufocom** [donaldzou/WGDashboard#156]
It would be great to get the postup/down config commands into the webinterface for client and server configuration.
At the moment I have to change the downloaded client config file manually to include those commands.

It would be a great benefit if your wonderful tool could handle those parameters too! :-)

**Comment by donaldzou** [comment]
Hi! Yes, I've added this as a new feature to the next release of the dashboard ;)

**Comment by grufocom** [comment]
Great, thank you!!

**Comment by donaldzou** [comment]
This feature got added into the next release ;)

**Comment by lockdlock** [comment]
Is there anything that needs to be configured on the client side?
