### ISSUE TITLE
WGDashboard should inform the user that there's a discrepancy between the actual interface status and wg-quick configuration file

### ISSUE THREAD

**Issue by Quintasan** [donaldzou/WGDashboard#165]
**Is your feature request related to a problem? Please describe.**

As outlined in https://github.com/donaldzou/WGDashboard/issues/164#issuecomment-1079265393 - if anything/anyone modifies the wireguard interface being configured AND `SaveConfig` is enabled then `wg-quick` will OVERWRITE the configuration file with the actual status of the interface

**Describe the solution you'd like**

An error message saying that there was a manual change to the interface would be a good start.

Bonus points if it's possible to show the differences and take appropriate action based on user's decision

**Comment by donaldzou** [comment]
Yeah the reason the dashboard need `SaveConfig` to be `true` is the dashboard is add/remove peer through `wireguard` command, instead of changing the `.conf` directly, to prevent format issue and other things. So each time, `wireguard` will edit the file.
