### ISSUE TITLE
IPv6 in WireGuard might not fully support.

### ISSUE THREAD

**Issue by donaldzou** [donaldzou/WGDashboard#167]
#160 ;)

**Comment by donaldzou** [comment]
IPv6 will crash the dashboard when it tried to generate available IPs

**Comment by pgalonza** [comment]
I using IPV6 without problem, but in older version.

**Comment by donaldzou** [comment]
> I using IPV6 without problem, but in older version.

Yeah, the reason is the Python IP library kind of buggy when generating IPv6 ip

**Comment by nandish486** [comment]
yes

**Comment by pgalonza** [comment]
> @pgalonza which release would that be?

I am not remember, but you can try branch witch i use https://github.com/pgalonza/WGDashboard/tree/develop, set var
ENVIRONMENT=production

for ssl
SSL=true
SERVERURL=<your domain name>

**Comment by DaanSelen** [comment]
https://github.com/donaldzou/WGDashboard/issues/461
