### ISSUE TITLE
failed to start error 500

### ISSUE THREAD

**Issue by bytec77** [donaldzou/WGDashboard#169]
Hi, 

after enter the password and hit enter I ran into "Internal Server Error"

Error: 

`* Serving Flask app 'WGDashboard' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:10086
 * Running on http://10.0.1.85:10086 (Press CTRL+C to quit)
User not signed in - Attempted access: index
10.0.1.210 - - [28/Mar/2022 22:30:04] "GET / HTTP/1.1" 302 -
10.0.1.210 - - [28/Mar/2022 22:30:04] "GET /signin?redirect=10.0.1.85:10086/ HTTP/1.1" 200 -
10.0.1.210 - - [28/Mar/2022 22:30:04] "GET /static/js/tools.min.js HTTP/1.1" 200 -
10.0.1.210 - - [28/Mar/2022 22:30:04] "GET /static/css/dashboard.css HTTP/1.1" 200 -
10.0.1.210 - - [28/Mar/2022 22:30:05] "GET /static/img/logo.png HTTP/1.1" 200 -
10.0.1.210 - - [28/Mar/2022 22:30:14] "GET /signin?redirect=10.0.1.85/ HTTP/1.1" 200 -
10.0.1.210 - - [28/Mar/2022 22:30:14] "GET /static/css/dashboard.css HTTP/1.1" 200 -
10.0.1.210 - - [28/Mar/2022 22:30:20] "POST /auth HTTP/1.1" 200 -
10.0.1.210 - - [28/Mar/2022 22:30:44] "GET /static/css/dashboard.css HTTP/1.1" 200 -
10.0.1.210 - - [28/Mar/2022 22:30:44] "GET /static/json/manifest.json HTTP/1.1" 200 -
10.0.1.210 - - [28/Mar/2022 22:30:53] "POST /auth HTTP/1.1" 200 -
[2022-03-28 22:30:53,902] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "dashboard.py", line 734, in index
    return render_template('index.html', conf=get_conf_list(), msg=msg)
  File "dashboard.py", line 501, in get_conf_list
    g.cur.execute(create_table)
sqlite3.OperationalError: near "-": syntax error
10.0.1.210 - - [28/Mar/2022 22:30:53] "GET / HTTP/1.1" 500 -`

**To Reproduce**
Please provide how you run the dashboard

**OS Information:**
 - OS: [RASPBIAN Buster]
 - Python Version: [v3.7]

**Sample of your `.conf` file**
`[Interface]
Address = 10.10.10.1/24
SaveConfig = true
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
ListenPort = 51820
PrivateKey = ABC
[Peer]
PublicKey = ABC
AllowedIPs = 10.10.10.2/32

[Peer]
PublicKey = ABC
AllowedIPs = 192.168.0.0/24, 10.10.10.0/24
Endpoint = HIDDEN-IP:33818

[Peer]
PublicKey = ABC
AllowedIPs = 10.10.10.6/32

[Peer]
PublicKey = ABC
AllowedIPs = 10.10.10.7/32
`
Please provide a sample of your configuration file that you are having problem with. You can replace your public key and private key to ABCD...
```

**Comment by donaldzou** [comment]
Hi, do you mind telling me what's the name of your configuration?

**Comment by bytec77** [comment]
The name is: wg0.conf

**Comment by donaldzou** [comment]
Do you have any other `.conf` in `/etc/wireguard`?

**Comment by bytec77** [comment]
yes man 🙈 I have forgotten one client conf in the folder. Now it works after I deleted it.

**Comment by mar-maradnus** [comment]
Hi, I have another conf file in /etc/wireguard - Procustodibus. How can I run WG Dahsboard along with that?
