### ISSUE TITLE
Add New Peer Allowed IP selection fails to display IP

### ISSUE THREAD

**Issue by gtmylab** [donaldzou/WGDashboard#170]
Newly installed works fine for available IP selection in (Allowed IPs field)  when creating first time Add New Peer. 

But second attempt for Add New Peer creation, the available IP section of  (Allowed IPs field)  disappear and does not display IP. I have to enter the IP manually.

Any idea why ? I am running Ubuntu 20.04

**Comment by donaldzou** [comment]
Hi would you mind post your configuration file here? You can remove all the keys.

**Comment by zverstal** [comment]
@gtmylab hi, i have this issue if the wg0.conf have IPv6 in **Address**.
Just delete IPv6 from wg0.conf.
The example here:
![image](https://user-images.githubusercontent.com/63104825/162620866-32629227-a435-42df-8c35-416dda773006.png)
![image](https://user-images.githubusercontent.com/63104825/162620873-f7ae6203-aed9-4c44-9540-0cd2440e281c.png)

Your wg.conf file should be like this:
![image](https://user-images.githubusercontent.com/63104825/162620985-acb45210-294c-46bf-a899-24aef03b7a5e.png)


Try this:
1. wg-quick down wg0 
2. editing wg.conf on my example
3. wg-quick up wg0

**Comment by donaldzou** [comment]
IPv6 is a known problem with this project: #167, if you removed your IPv6 address, will it work?

**Comment by donaldzou** [comment]
I will be fixing it in the next release ;)

**Comment by zverstal** [comment]
Yes, available IPs appeared if i remove IPv6 :)

**Comment by donaldzou** [comment]
I see, IPv6 wasn't fully support in the current version. If you really need IPv6 support, you can download the beta version of `v3.1`, you can follow the instruction on the very top of README.md ;)

**Comment by DaanSelen** [comment]
@gtmylab is this still relevant?
