### ISSUE TITLE
Can't leave DNS field empty

### ISSUE THREAD

**Issue by argiedoubleya** [donaldzou/WGDashboard#172]
Hi I am trying out your dashboard and so far I like it a lot, however, my configs do not use a DNS server and I can't leave the field empty. Can you adjust the form so that a DNS entry is not requirement?

**Comment by donaldzou** [comment]
I will fix this in the next release

**Comment by argiedoubleya** [comment]
Ok great. It also shouldn't throw an error if the MTU and Persistent keepalive fields are left blank too.

Good work it is an awesome dashboard

**Comment by shyjuk** [comment]
> I will fix this in the next release

Hi @donaldzou Is this fix already applied?

**Comment by donaldzou** [comment]
This will be fix in `v4`. Please refer to #293
