### ISSUE TITLE
wgd.sh missing

### ISSUE THREAD

**Issue by republicandaddy** [donaldzou/WGDashboard#174]
Hi!  after the last time I ran the update command (./wgd.sh update), all worked fine.  However, I went to do so today to see if there was a new subversion and literally the file is missing.  the page still runs as expected, but the wgd.sh is missing in the src folder.

Can I just pull it from github and insert it or is it built on install and specific to the hardware/build I'm running?

**Comment by donaldzou** [comment]
I believe you can just pull it from the github

**Comment by donaldzou** [comment]
Let me know did you solve the problem ;)

**Comment by eklascode** [comment]
same  problem
