### ISSUE TITLE
There is no download button and qr code

### ISSUE THREAD

**Issue by p1grishin** [donaldzou/WGDashboard#176]
Peers that are not created through the dashboard do not have a download config button and a qr code.

**Comment by LeoEricson** [comment]
This is likely due to the lack of a value in the "Private Key" field.

Isn't this intended behavior?

**Comment by donaldzou** [comment]
@LeoEricson Yes you're right.

This was due to the peer is not created from the Dashboard so it doesn't have the private key of the peer. Creating the config file/QR code require the private key.
