### ISSUE TITLE
Gunicorn bad config?

### ISSUE THREAD

**Issue by HyptexPvP** [donaldzou/WGDashboard#178]
**Describe The Problem**
Gunicorn config doesnt work? Mostlikely a python issue i think.

**Expected Error / Traceback**
```
Please provide the error traceback here
| Starting WGDashboard with Gunicorn in the background.    |
Failed to read config file: /root/wgdashboard/src/gunicorn.conf.py
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 106, in get_config_from_filename
execfile_(filename, cfg, cfg)
File "/usr/lib/python2.7/site-packages/gunicorn/_compat.py", line 91, in execfile_
return execfile(fname, *args)
File "/root/wgdashboard/src/gunicorn.conf.py", line 9
bind = f"{app_host}:{app_port}"
^
SyntaxError: invalid syntax
| Log files is under log/   
```

**To Reproduce**
Please provide how you run the dashboard

**OS Information:**
 - OS: Oracle linux 8, (ARM)
 - Python Version: 3.9.

**Sample of your `.conf` file**
```
Please provide a sample of your configuration file that you are having problem with. You can replace your public key and private key to ABCD...
import multiprocessing
import dashboard

app_host, app_port = dashboard.get_host_bind()

worker_class = 'gthread'
workers = multiprocessing.cpu_count() * 2 + 1
threads = 4
bind = f"{app_host}:{app_port}"
daemon = True
pidfile = './gunicorn.pid'
```

**Comment by satheshshiva** [comment]
I face the same issue.

**Comment by pgalonza** [comment]
@HyptexPvP Hi, in your log-massage i see you using gunicorn for Python 2

File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 106, in get_config_from_filename
execfile_(filename, cfg, cfg)
File "/usr/lib/python2.7/site-packages/gunicorn/_compat.py", line 91, in execfile_

You should to use Python 3. Plz install gunicorn for example like this command python3 -m pip install gunicorn

**Comment by DaanSelen** [comment]
Python 3.10 is advised in the documentation.
