### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by quantuumsnot** [donaldzou/WGDashboard#180]
**Describe The Problem**
WGDashboard won't start and outputs a missing modules in the script and no logs saved in `log` dir

```
| Starting WGDashboard with Gunicorn in the background.    |
Failed to read config file: /home/wgdashboard/src/gunicorn.conf.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wgdashboard/src/gunicorn.conf.py", line 2, in <module>
    import dashboard
  File "/home/wgdashboard/src/dashboard.py", line 23, in <module>
    import ifcfg
ModuleNotFoundError: No module named 'ifcfg'
| Log files is under log/

```
**To Reproduce**
starting it with `./wdg.sh start` while logged as `root`

**OS Information:**
 - OS: Ubuntu 20.04
 - Python Version: v3.8.10

I know that the problem is in the missing python modules but for the sanity of the people that do not use python it will be good to actually install them in the `install` script

**Comment by DaanSelen** [comment]
Have you tested on the new version?

**Comment by quantuumsnot** [comment]
Actually yes, I even tested all offered solutions with updating python to 3.12, enabling venv, etc ...
Nothing worked, `systemctl status wg-dashboard.service` always reports service is failed to start (some Type error thingy)
Decided to remove it for now

In fact it was working while version was 3 something (3.0.6 or similar) :headscratch:
The actual problem was it was working on my specific port only from local network connections (192.168.0.1 as example) while using 10.7.0.1 it didn't  ¯\\_(ツ)_/¯

**Comment by DaanSelen** [comment]
I'd like to help but can you perhaps show some configuration options if possible? And if you get any response at all?

**Comment by quantuumsnot** [comment]
I was pushed to do some upgrade of the distro, 20.04 LTS to 22.04 LTS, this shit tried to kernel boot loop me :D
Fixed it with switching to previous kernel then dpkg updated it again

Anyway, step by step:
```
root@zzz:/home/zzz# git clone https://github.com/donaldzou/WGDashboard.git && \
cd ./WGDashboard/src && \
chmod +x ./wgd.sh && \
./wgd.sh install
Cloning into 'WGDashboard'...
remote: Enumerating objects: 5081, done.
remote: Counting objects: 100% (3590/3590), done.
remote: Compressing objects: 100% (1089/1089), done.
remote: Total 5081 (delta 2662), reused 3207 (delta 2444), pack-reused 1491 (from 1)
Receiving objects: 100% (5081/5081), 32.19 MiB | 3.33 MiB/s, done.
Resolving deltas: 100% (3399/3399), done.
------------------------------------------------------------
[WGDashboard] Starting to install WGDashboard
[WGDashboard] Creating ./log folder
[WGDashboard] OS: ubuntu
[WGDashboard] ✔ Python is installed
[WGDashboard] ✔ Python Virtual Environment is installed
[WGDashboard] ✔ Python Package Manager (PIP) is installed
[WGDashboard] WireGuard is already installed.
[WGDashboard] Creating ./db folder
[WGDashboard] Creating Python Virtual Environment under ./venv
[WGDashboard] Upgrading Python Package Manage (PIP)
[WGDashboard] Installing latest Python dependencies
[WGDashboard] WGDashboard installed successfully!
[WGDashboard] Enter ./wgd.sh start to start the dashboard
------------------------------------------------------------
```
Next command after installation:
```
root@zzz:/home/zzz/WGDashboard/src# systemctl status wg-dashboard.service
× wg-dashboard.service
     Loaded: loaded (/etc/systemd/system/wg-dashboard.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2024-10-05 17:43:16 EEST; 1h 15min ago
   Main PID: 1349 (code=exited, status=200/CHDIR)
        CPU: 7ms

Oct 05 17:43:16 zzz systemd[1]: wg-dashboard.service: Scheduled restart job, restart counter is at 5.
Oct 05 17:43:16 zzz systemd[1]: Stopped wg-dashboard.service.
Oct 05 17:43:16 zzz systemd[1]: wg-dashboard.service: Start request repeated too quickly.
Oct 05 17:43:16 zzz systemd[1]: wg-dashboard.service: Failed with result 'exit-code'.
Oct 05 17:43:16 zzz systemd[1]: Failed to start wg-dashboard.service.
```
Next command after checking wg-dashboard service status:
```
root@zzz:/home/zzz/WGDashboard/src# ./wgd.sh start
[WGDashboard] WireGuard is already installed.
------------------------------------------------------------
[WGDashboard] Starting WGDashboard with Gunicorn in the background.
[WGDashboard] Initialized Configuration: wg0
[WGDashboard] WGDashboard w/ Gunicorn will be running on 0.0.0.0:10086
[WGDashboard] Access log file is at ./log/access_2024_10_05_19_00_18.log
[WGDashboard] Error log file is at ./log/error_2024_10_05_19_00_18.log
[WGDashboard] Checking if WGDashboard w/ Gunicorn started successfully
[WGDashboard] WGDashboard w/ Gunicorn started successfully
------------------------------------------------------------
```
`net.ipv4.ip_forward=1` is ENABLED


`./log/error_2024_10_05_19_00_18.log`
```
[2024-10-05 19:00:18 +0300] [9255] [INFO] Starting gunicorn 23.0.0
[2024-10-05 19:00:18 +0300] [9255] [INFO] Listening at: http://0.0.0.0:10086 (9255)
[2024-10-05 19:00:18 +0300] [9255] [INFO] Using worker: gthread
[2024-10-05 19:00:18 +0300] [9257] [INFO] Booting worker with pid: 9257
[WGDashboard] Background Thread #1 Started
[WGDashboard] Background Thread #2 Started
```
`nano wg-dashboard.ini`
```
[Account]
username = admin
password = $2b$12$QtYsdLgM6hIbtohv6My7Z.7S8eMxNWCu/sj/k/mfl5rMMc7dZCMMW
enable_totp = false
totp_verified = false
totp_key = 2CUQ7SCNGJUOJKHPG4HDMOJ2JL2XVXGP

[Server]
wg_conf_path = /etc/wireguard
app_prefix =
app_ip = 0.0.0.0
app_port = 65002
auth_req = true
version = v4.0.4
dashboard_refresh_interval = 60000
dashboard_sort = status
dashboard_theme = dark
dashboard_api_key = false

[Peers]
peer_global_dns = 1.1.1.1
peer_endpoint_allowed_ip = 0.0.0.0/0
peer_display_mode = grid
remote_endpoint = 192.168.0.107
peer_mtu = 1420
peer_keep_alive = 21

[Other]
welcome_session = true

[Database]
type = sqlite
```

wg-dashboard.service status is still FAILED, no possible connections through local or VPN address while other remote services are working ok

**Comment by donaldzou** [comment]
Hi! I'm sorry that you encountered this issue. Just to confirm, starting WGDashboard with `.wgd.sh start` works fine? Would you mind to provide the service file you have currently please: `/etc/systemd/system/wg-dashboard.service`? and we can look from there :)

**Comment by quantuumsnot** [comment]
```
[Unit]
After=syslog.target network-online.target
ConditionPathIsDirectory=/etc/wireguard

[Service]
Environment="VIRTUAL_ENV={{VIRTUAL_ENV}}"
WorkingDirectory=/home/wgdashboard/src
ExecStart=/usr/bin/python3 /home/wgdashboard/src/dashboard.py
PrivateTmp=yes
Restart=always


[Install]
WantedBy=multi-user.target
```

**Comment by donaldzou** [comment]
Hi, seems like you're using your system's Python Interpreter, not the Virtual Environment. Assumed you install the virtual environment correctly (used `.wgd.sh install`):
- Replace 
    - `ExecStart=/usr/bin/python3 /home/wgdashboard/src/dashboard.py`
- With
    - `ExecStart=/home/wgdashboard/src/wgd.sh start`

Hope this helps :)

**Comment by quantuumsnot** [comment]
```
[2024-10-07 00:42:27 +0300] [9511] [INFO] Handling signal: term
[2024-10-07 00:42:57 +0300] [9511] [ERROR] Worker (pid:9513) was sent SIGKILL! Perhaps out of memory?
[2024-10-07 00:42:57 +0300] [9511] [INFO] Shutting down: Master
```

Nope

**Comment by DaanSelen** [comment]
> ```
> [2024-10-07 00:42:27 +0300] [9511] [INFO] Handling signal: term
> [2024-10-07 00:42:57 +0300] [9511] [ERROR] Worker (pid:9513) was sent SIGKILL! Perhaps out of memory?
> [2024-10-07 00:42:57 +0300] [9511] [INFO] Shutting down: Master
> ```
> 
> Nope

From this I read that the kernel is killing it, could there be something wrong with the system?

**Comment by quantuumsnot** [comment]
```
Mem:  3.73GB used: 1.65GB
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           382M  3.1M  379M   1% /run
/dev/md0        458G   18G  417G   4% /
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           382M  4.0K  382M   1% /run/user/0
```
I dunno why, memory is enough

**Comment by DaanSelen** [comment]
Regarding the service itself, you can check the `journalctl -u wg-dashboard.service -f`. But weird that that happends. Can you if you don't have a big installation reinstall everything, including the dependencies?

**Comment by quantuumsnot** [comment]
I've just deleted the directory and installed it again, `wg-dashboard.service` is still in FAILED state while dashboard works but not with `https://` ` ¯\_(ツ)_/¯`

**Comment by donaldzou** [comment]
This is so weird.. Let me look into this.

> Edit: Is it possible to add peer names into wireguard's config file instead somewhere else?

Yes, you can follow this instruction: https://donaldzou.github.io/WGDashboard-Documentation/requirements.html#existing-wireguard-configurations

**Comment by quantuumsnot** [comment]
Ok, thanks ... If you have some ideas to check, I'll post the results here again 👍

**Comment by DaanSelen** [comment]
@quantuumsnot do you still encounter this?

**Comment by DaanSelen** [comment]
Okay... wel its nog a SIGKILL. Can you reproduce this issue and create a couple steps on how to reproduce this?

**Comment by quantuumsnot** [comment]
```
wg-dashboard.service: Failed at step EXEC spawning /home/wgdashboard/src/wgd.sh: No such file or directory
wg-dashboard.service: Failed to locate executable /home/wgdashboard/src/wgd.sh: No such file or directory
```

Despite the fact that `wgd.sh` is located in /home/zzz/WGDashboard/src

**Comment by DaanSelen** [comment]
Hey @quantuumsnot , sorry for my late response. Can you reproduce this?
