### ISSUE TITLE
 Failed to start wg-dashboard.service even though step by step guideline instructions

### ISSUE THREAD

**Issue by KelvinPhyo** [donaldzou/WGDashboard#183]
**Failed to start wg-dashboard.service**
when I done step by step install and modified configuration but I face the error that wg-dashboard service failed to start. Kindly see below screen shot for reference. Please reply to me for suggestion and how to fix this error. Thanks.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/57132151/174528679-8a552662-2961-43df-8e61-859c19046aa3.png">

<img width="469" alt="image" src="https://user-images.githubusercontent.com/57132151/174528724-345c702f-d541-4d11-a923-48d359a93b97.png">

<img width="467" alt="image" src="https://user-images.githubusercontent.com/57132151/174528799-1d1d5c55-e345-4b31-9162-74881610ba36.png">

#- ### ### ### ### ### ### ### 
-

**Comment by Dean2706** [comment]
I had the same issue on boot, but if I manually start the service it was OK.
I added the StartLimitInterval=1 under the Restart=always and this fixed the issue for me.

########################################################

[Unit]
After=netword.service

[Service]
WorkingDirectory=/root/wgdashboard/src
ExecStart=/usr/bin/python3 /root/wgdashboard/src/dashboard.py
Restart=always
StartLimitInterval=1

[Install]
WantedBy=default.target

**Comment by Avonae** [comment]
> I had the same issue on boot, but if I manually start the service it was OK. I added the StartLimitInterval=1 under the Restart=always and this fixed the issue for me.
> 
> ########################################################
> 
> [Unit] After=netword.service
> 
> [Service] WorkingDirectory=/root/wgdashboard/src ExecStart=/usr/bin/python3 /root/wgdashboard/src/dashboard.py Restart=always StartLimitInterval=1
> 
> [Install] WantedBy=default.target

thank you so much! it works like a charm!
