### ISSUE TITLE
Add Peer dialog hangs on /16 networks

### ISSUE THREAD

**Issue by lesha-co** [donaldzou/WGDashboard#184]
**Describe The Problem**
Add Peer dialog hangs on /16 networks

**Expected Error / Traceback**
```
No traceback, it just hangs
```

**To Reproduce**
- create interface with /16 network
- try to add peer

anyway

https://github.com/donaldzou/WGDashboard/blob/d7d7a84bd5aee496846095c48d638ab46c91958a/src/static/js/configuration.js#L494

this line tries to add 65k elements to the DOM and browsers don't like it one bit

**Comment by DaanSelen** [comment]
I think this is no longer relevant?
