### ISSUE TITLE
Can't login --> I'm Getting internal Server Error 

### ISSUE THREAD

**Issue by WolfSc84** [donaldzou/WGDashboard#188]
Hello Guys

I can't access to the dashboard, cause im getting internal server error just next i put the crednetials into the logon page... Im using admin - admin as the guide says.... This is the debug log:

![image](https://user-images.githubusercontent.com/29180419/180627455-08aa0574-9d3b-4309-b9d0-0fa72a9224b4.png)

![image](https://user-images.githubusercontent.com/29180419/180627488-7e320029-8f1c-4de9-b952-8ec035b6f00e.png)

This is my configuration file into wireguard:

![image](https://user-images.githubusercontent.com/29180419/180627522-962d2d8e-9875-4b16-b642-2fdf9823ec08.png)

And this the dashboard configuration file:

![image](https://user-images.githubusercontent.com/29180419/180627540-bf1fbc18-7985-47ee-bf7b-01e0c7e08312.png)

I granted permissions to the files as the guidelines says..

Do you have any idea guys what is wrong with that?

Im using docker to deploy wireguard, and wgdashboard is running locally in the host server...

This is the docker compose used to deploy wireguard:

version: '3.7'

services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - SERVERURL=192.168.1.3
      - SERVERPORT=51820 #optional
      - PEERS=6 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - /root/wireguard:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 172.20.0.7
    restart: always
    networks:
      containers:
        ipv4_address: 172.20.0.6

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    #expose:
      #- "53"
      #- "67"
      #- "80"
      #- "443"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'America/Bogota'
      WEBPASSWORD: 'Marimar...Guao...CostenitaSoy'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      containers:
        ipv4_address: 172.20.0.7

networks:
  containers:
    ipam:
      config:
        - subnet: 172.20.0.0/24

**Comment by DaanSelen** [comment]
If you still have this issue, and want it resolved. Please check our https://github.com/donaldzou/WGDashboard/issues/272 for a more up-to-date image. Any feedback is welcome.
