### ISSUE TITLE
Clients can only have a /32 IP

### ISSUE THREAD

**Issue by mar-maradnus** [donaldzou/WGDashboard#197]
I tried to change the IP subnet of my clients to a /24, so that they can all be reachable from each other. The dashboard accepts only a /32. The error provided is "Warning: AllowedIP has nonzero host part: xxx.xxx.xxx.xxx/24"

**Comment by kryztoval** [comment]
Allowed IPs which is the interface ip should be /32, that is the ip address the other clients will use to reach you.
The Endpoint allowed IPs is the one that can be /24 so any other device in the same range can see you.

**Comment by DaanSelen** [comment]
Distinction between a network notation and endpoint notation. /32 is a single IP-address, e.g. a single machine, /24 is 256 addresses, e.g. a network.
