### ISSUE TITLE
Other conf files in /etc/wireguard cause internal server error

### ISSUE THREAD

**Issue by mar-maradnus** [donaldzou/WGDashboard#198]
I run procustodibus, that gives me remote monitoring of my WG networks.

Procustodibus needs two conf files in the /etc/wireguard directory.

This causes WGD to give an internal server error.

Is there any way to fix this so that WGD only picks up the required wg*.conf files and ignores the others?

**Comment by DaanSelen** [comment]
Is this still relevant with version 4.0.2?
