### ISSUE TITLE
Option to default flag the 'Use Pre-shared Key' when creating a new profile

### ISSUE THREAD

**Issue by martin-g-it** [donaldzou/WGDashboard#200]
Currently, the option/flag to 'Use Pre-shared Key' is unticked when creating a new profile.
Would be great to flag this by default or make it a setting in the WG Dashboard

**Comment by martin-g-it** [comment]
Seems like this can be achieved by adding:
 checked="{checked}"

to line 219 in /wgdashboard/src/templates/configuration.html

`                                    <input class="form-check-input" type="checkbox" id="enable_preshare_key" name="enable_preshare_key" value="enable_psk" checked="{checked}">
`

**Comment by buddyqc69** [comment]
that work now, you can close the ticket
