### ISSUE TITLE
wgdashboard issue with sqlite table names, does not handle interface names with dash in name

### ISSUE THREAD

**Issue by epiecs** [donaldzou/WGDashboard#207]
**Describe The Problem**
Wireguard allows interfaces names that match the following regex: `^[a-zA-Z0-9_=+.-]{1,15}$`

In dashboard.py the on line [490](https://github.com/donaldzou/WGDashboard/blob/main/src/dashboard.py#L490) the create_table function crashes when using an interface name such as `wg-test`.

The reason for this is that SQlite does not allow dashes in database names unless they are quoted. As reference see this {stackoverflow answer](https://stackoverflow.com/a/3694291).

The fix is to replace `CREATE TABLE IF NOT EXISTS {i} (` with `CREATE TABLE IF NOT EXISTS \"{i}\" (`

This will fix the login error. However there are some more locations in the code that still need escaping. For example opening an interface wont work.

**Expected Error / Traceback**
```
Dec 17 23:01:02 wireguard python3[40351]:   File "/srv/wgdashboard/src/dashboard.py", line 501, in get_conf_list
Dec 17 23:01:02 wireguard python3[40351]:     g.cur.execute(create_table)
Dec 17 23:01:02 wireguard python3[40351]: sqlite3.OperationalError: near "-": syntax error
```

**To Reproduce**
Run the dashboard with an interface with dashes in the name such as `wg-test`

**OS Information:**

```
       _,met$$$$$gg.          root@wireguard
    ,g$$$$$$$$$$$$$$$P.       --------------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) x86_64
 ,$$P'              `$$$.     Host: KVM/QEMU (Standard PC (i440FX + PIIX, 1996) pc-i440fx-7.1)
',$$P       ,ggs.     `$$b:   Kernel: 5.10.0-19-cloud-amd64
`d$$'     ,$P"'   .    $$$    Uptime: 1 day, 2 hours, 8 mins
 $$P      d$'     ,    $$P    Packages: 451 (dpkg)
 $$:      $$.   -    ,d$$'    Shell: bash 5.1.4
 $$;      Y$b._   _,d$P'      CPU: Intel i7-8559U (2) @ 2.711GHz
 Y$$.    `.`"Y$$$$P"'         Memory: 112MiB / 1985MiB
 `$$b      "-.__
  `Y$$
   `Y$$.
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""

python3 -V
Python 3.9.2
```

**Sample of your `.conf` file**
```
default file without any changes
```

**Comment by DaanSelen** [comment]
I think this is fixed in version 4 and later.
