### ISSUE TITLE
Enable peer

### ISSUE THREAD

**Issue by VladimirKoh** [donaldzou/WGDashboard#211]
![Снимок экрана 2023-02-21 в 12 17 50](https://user-images.githubusercontent.com/109983400/220302564-a15affd4-1011-42bd-8782-70240e4e2654.png)

 Activating a user throws an error. The reason is the unclosed tag - samp
![Снимок экрана 2023-02-21 в 12 16 20](https://user-images.githubusercontent.com/109983400/220302673-45c93587-df2f-4b84-9936-1bed24cd9770.png)

file /src/static/js/configuration.js         line 519

**Comment by DaanSelen** [comment]
Hello @VladimirKoh please try again with the new version.
