### ISSUE TITLE
New configurations doesn't work. Only the default configuration (wg0) works.

### ISSUE THREAD

**Issue by rasurulaev** [donaldzou/WGDashboard#212]
I'm trying to create a second network (wg1), everything seems to be fine, but when connecting to a VPN, handshake does not occur. Can you suggest what is the problem? I attach the configuration file and screenshots

My dashboard is running on veesp.com VPS with Wireguard template.

wg1_02202023182931
```
[Interface]
PrivateKey = SMhCbXkFgacavkSzH+7D4x/qNlYGFiv/r937m+Dpt2g=
Address = 10.0.1.3/32
DNS = 1.1.1.1
MTU = 1420

[Peer]
PublicKey = Cu5JIs64y530586MeZz7ph4qX8AXVATfx0rmRemRIRY=
AllowedIPs = 0.0.0.0/0
Endpoint = 91.197.3.127:52836
PersistentKeepalive = 21
```
![2023-02-20_21-47-04](https://user-images.githubusercontent.com/45902427/220316340-14aa2f43-e686-4fdb-b298-8d85e1c964a5.png)
![2023-02-20_21-44-54](https://user-images.githubusercontent.com/45902427/220316363-403819f3-8dcb-4611-b308-93cba8f1d8a7.png)

**Comment by CaptainBlur** [comment]
Yeah, just faced the same problem. All different ips and ports doesn't work

**Comment by DaanSelen** [comment]
Do you still experience this? @CaptainBlur @rasurulaev

It looks like you are missing `iptables` rules.
