### ISSUE TITLE
adds users without taking into account IP addresses of disabled users

### ISSUE THREAD

**Issue by VladimirKoh** [donaldzou/WGDashboard#214]
![2023-02-21 19 45 07](https://user-images.githubusercontent.com/109983400/220409263-c25427f5-036d-46c8-b0e8-04d83df03422.jpg)

![2023-02-21 19 45 19](https://user-images.githubusercontent.com/109983400/220409326-350c9d4c-235c-467a-8c24-bd9167d9a728.jpg)

![2023-02-21 19 45 42](https://user-images.githubusercontent.com/109983400/220409377-88a66dc1-3e0c-4240-9d33-d85b6dd0466e.jpg)

![2023-02-21 19 45 48](https://user-images.githubusercontent.com/109983400/220409550-0826934b-fed7-4f84-87d3-d33205ecdff4.jpg)

on the last screenshot the fix option

**Comment by DaanSelen** [comment]
I think this is fixed with the new version. @VladimirKoh
