### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by psmoros** [donaldzou/WGDashboard#217]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@nicolai-h) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by donaldzou** [comment]
Hi @psmoros,

Thank you so much for bringing up this, I would love to do that :)

Best,
Donald

**Comment by psmoros** [comment]
My pleasure!  :)) Could you please give me an email we can use?

**Comment by DaanSelen** [comment]
Hello @psmoros, I think you can find an email on Donald's profile.
