### ISSUE TITLE
SaveConfig = true

### ISSUE THREAD

**Issue by HanSyt** [donaldzou/WGDashboard#218]
I have installed WGDashboard on a raspberry pi. It did not install out-of-the-box, I had to add some libraries.
Now I have the problem by adding SaveConfig = true to the wireguard config file, wireguard  (wg show) gives a different port, but is not starting anymore.

Without SaveConfig = true it starts and works like a charm. However wgdashboard is showing the pears, but does not recognise wireguard as started nor peers to be alive.

I know this dashboard is not tested on a raspberry pi, so maybe ther is no solution for it.

![image](https://user-images.githubusercontent.com/56794786/229216885-e608411b-60f5-44d2-860b-70e35c93015e.png)

**Comment by DaanSelen** [comment]
Hello @HanSyt please try again with the new version.

**Comment by HanSyt** [comment]
Hello @DaanSelen , this summer (2024) I replaced my network gear with 1GB capable equipment and I am using Wireguard from the router, so I am not using the raspeberry pi anymore for this.

**Comment by DaanSelen** [comment]
So this issue is no longer relevant?

**Comment by HanSyt** [comment]
For me it is no longer relevant
