### ISSUE TITLE
User expiration date

### ISSUE THREAD

**Issue by ExtremeDot** [donaldzou/WGDashboard#219]
Hi

can you please add a user expiration date and time to set on peers?

**Comment by therealpimi** [comment]
Hello, can we have expire date and data usage on panel? More like a counter and wearing in the panel.. it is better to these options in automatic, but warning can do the job also.
And it would be nice to have like a sort and group management for users also.
Like group and sort users into data limit and ip speed limit or expire limit.

**Comment by sohrabp72** [comment]
I need the expiration date to remove the peer or disable it after the expiration date also being able to limit monthly traffic would be great!

**Comment by upgo7502** [comment]
Hello Dear
Please add expireation date for peers .

Thanks in advance

**Comment by upgo7502** [comment]
Hello Dear
Please add expireation date for peers .

Thanks in advance

**Comment by upgo7502** [comment]
Hello Dear
Please add expireation date for peers .

Thanks in advance

**Comment by upgo7502** [comment]
Hello Dear
Please add expireation date for peers .

Thanks in advance

**Comment by donaldzou** [comment]
Will do

**Comment by MoeinNS** [comment]
> Will do
Please add expireation date for peers

**Comment by MoeinNS** [comment]
> Will do

Please add expireation date for peers

**Comment by ExtremeDot** [comment]
azumi has done it , but its is on persian language

**Comment by sohrabp72** [comment]
> azumi has done it , but its is on persian language

That project has many bug and gets no update. That project is not suitable in production.
