### ISSUE TITLE
Error at WGD start Failed to read config file: gunicorn.conf.py | Possibly issue with gunicorn

### ISSUE THREAD

**Issue by Mikeileech** [donaldzou/WGDashboard#220]
**Describe The Problem**
Packet instals correctly and i see installation confirmation message, but it always fails at start with following list of errors.
Here is what i got from start to finish:

### #root@vm87631:~# git clone -b v3.0.6 https://github.com/donaldzou/WGDashboard.git wgdashboardfatal: destination path 'wgdashboard' already exists and is not an empty directory.

root@vm87631:~# cd wgdashboard/src
root@vm87631:~/wgdashboard/src# sudo chmod u+x [wgd.sh](http://wgd.sh/)
root@vm87631:~/wgdashboard/src# sudo ./[wgd.sh](http://wgd.sh/) install
------------------------------------------------------------|
Starting to install WGDashboard ||
Upgrading pip ||
Installing latest Python dependencies ||
WGDashboard installed successfully! ||
Enter ./[wgd.sh](http://wgd.sh/) start to start the dashboard |
------------------------------------------------------------
root@vm87631:~/wgdashboard/src# sudo chmod -R 755 /etc/wireguard
root@vm87631:~/wgdashboard/src# ./[wgd.sh](http://wgd.sh/) start
------------------------------------------------------------|
Starting WGDashboard with Gunicorn in the background. |
Failed to read config file: /root/wgdashboard/src/[gunicorn.conf.py](http://gunicorn.conf.py/)
Traceback (most recent call last):
File "/usr/local/lib/python3.11/dist-packages/gunicorn/app/[base.py](http://base.py/)", line 111, in get_config_from_filename spec.loader.exec_module(mod)
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/root/wgdashboard/src/[gunicorn.conf.py](http://gunicorn.conf.py/)", line 2, in <module> import dashboard
File "/root/wgdashboard/src/[dashboard.py](http://dashboard.py/)", line 23, in <module> import ifcfg
ModuleNotFoundError: No module named 'ifcfg'| Log files is under log/

**OS Information:
 - OS: [e.g. Ubuntu 22.04 LTS
 - Python Version: [latest, as far as i can trust cmd answers]**

**Comment by Silence02ru** [comment]
`ModuleNotFoundError: No module named 'ifcfg'`
The installer could not install the module, check what prevents it through `pip install -U -r requirements.txt`

**Comment by barryboom** [comment]
pip install ifcfg --break-system-packages

and need to do the same for all other components which have been removed. Flask, FLask_QRcode etc etc

i assume you have upgraded to 23.04 ?

**Comment by Silence02ru** [comment]
> pip install ifcfg --break-system-packages
> 
> and need to do the same for all other components which have been removed. Flask, FLask_QRcode etc etc
> 
> i assume you have upgraded to 23.04 ?

Debian 11 has the same problem, there were no problems on the last server

**Comment by Silence02ru** [comment]
`ERROR: Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.` 
`sudo apt remove python3-blinker` I deleted it manually, and was able to install the modules
