### ISSUE TITLE
Mikrotik

### ISSUE THREAD

**Issue by rdavey228** [donaldzou/WGDashboard#227]
I’m looking my for a way to use this but my WireGuard is on my MikroTik router. 

Obviously the dashboard need access to the configuration to work. So how would I do this if I setup the dashboard on my docker host

Any way to use this with a MikroTik WireGuard setup?

**Comment by DaanSelen** [comment]
I am not familiar with MikroTik, are they able to run Docker containers? If yes, then you would only have to parse the wireguard's wg0.conf file to the /etc/wireguard/wg0.conf in the container.

**Comment by donaldzou** [comment]
Will close this due to inactivity :)
