### ISSUE TITLE
Adding configuration problem

### ISSUE THREAD

**Issue by whatisloveg** [donaldzou/WGDashboard#229]
Hello, I want to add configurations via ssh and have them displayed in the panel, I tried to do it automatically via  ./easy-wg-quick. No results, the question is, is it possible to somehow call the function via ssh to create the configuration automatically?

**Comment by donaldzou** [comment]
Hi, sorry for the late reply. One way is to create it manually, you can just create a `.conf` file under `/etc/wireguard` in your system and refer https://github.com/donaldzou/wireguard-docs :)
