### ISSUE TITLE
Internal Server Error.The server encountered an internal error and was unable to complete your request. Either the server is overloaded or an error occurred in the application." 

### ISSUE THREAD

**Issue by Kot-nikot** [donaldzou/WGDashboard#230]
Everything works fine after installation, but two days ago the panel became unavailable. After authorization in the browser error "Internal Server Error.The server encountered an internal error and was unable to complete your request. Either the server is overloaded or an error occurred in the application." 
The log shows this:
"GET / HTTP/1.1" 302 -
xxx.xxx.xxx.xxx - - [26/Aug/2023 07:48:37] "GET /signin?redirect=xxx.xxx.xxx.xxx:10089/ HTTP/1.1" 2
xxx.xxx.xxx.xxx - - [26/Aug/2023 07:48:38] "GET /static/css/dashboard.css HTTP/1.1" 200 -
xxx.xxx.xxx.xxx - - [26/Aug/2023 07:48:38] "GET /static/js/tools.min.js HTTP/1.1" 200 -
xxx.xxx.xxx.xxx - - [26/Aug/2023 07:48:45] "POST /auth HTTP/1.1" 200 -
[2023-08-26 07:48:46,138] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/home/ubuntu/wgdashboard/src/dashboard.py", line 734, in index
return render_template('index.html', conf=get_conf_list(), msg=msg)
File "/home/ubuntu/wgdashboard/src/dashboard.py", line 501, in get_conf_list
g.cur.execute(create_table)
sqlite3.OperationalError: near "-": syntax error

**Comment by MichaelTrip** [comment]
I have the same error.

**Comment by nandish486** [comment]
yes very true, python is using too much memory so. 

https://github.com/donaldzou/WGDashboard/issues/237

I just post it.

**Comment by choofster** [comment]
not sure if this is helpful, but I had a similar issue because you see the last line of the log that says syntax error near "-" meaning probably the name of your wg.conf file or some other related file has a dash "-" in it. and the code is not properly escaping the dash when it is creating the table, since "-" characters have to be input specially into databases.

I fixed it this error by renaming my wg1-something.conf file to just wg1.conf, removing the dash.

**Comment by Kot-nikot** [comment]
> not sure if this is helpful, but I had a similar issue because you see the last line of the log that says syntax error near "-" meaning probably the name of your wg.conf file or some other related file has a dash "-" in it. and the code is not properly escaping the dash when it is creating the table, since "-" characters have to be input specially into databases.
> 
> I fixed it this error by renaming my wg1-something.conf file to just wg1.conf, removing the dash.

Yes indeed the error was due to a hyphen in the config name. After renaming the config, the problem disappeared. Thank you, kind man.
