### ISSUE TITLE
Creating configuration

### ISSUE THREAD

**Issue by Iman-Sh** [donaldzou/WGDashboard#231]
Hi, sry im really new to server stuff but i managed to get the dashboard working but now it needs configurations to work so can somebody guide me how can i make a configuration plz? any help would be appriciated.

**Comment by donaldzou** [comment]
Hi! Sorry for the late reply. Are you still having the issue?

**Comment by DaanSelen** [comment]
> Hi, sry im really new to server stuff but i managed to get the dashboard working but now it needs configurations to work so can somebody guide me how can i make a configuration plz? any help would be appriciated.

For ease of use, you can look into the Docker documentation, which has a lot of automated processes, for and example see here:
```
[Interface]
Address = 10.0.0.1/24
SaveConfig = true
PostUp = iptables -t nat -I POSTROUTING 1 -s 10.0.0.1/24 -o eth0 -j MASQUERADE
PostUp = iptables -I FORWARD -i wg0 -o wg0 -j DROP
PreDown = iptables -t nat -D POSTROUTING -s 10.0.0.1/24 -o eth0 -j MASQUERADE
PreDown = iptables -D FORWARD -i wg0 -o wg0 -j DROP
ListenPort = 51820
PrivateKey = yBsUJvKtKfv3PwcOzijsvLYnD1WGYWZ8EB7wQldE/W4=

[Peer]
PublicKey = UScE4ib+5P7bM/EuiNhuxjq+DwkALMN4lvaOAo5qq1Q=
AllowedIPs = 10.0.0.2/32
```
