### ISSUE TITLE
Creating new user resets configuration address to /32

### ISSUE THREAD

**Issue by egorshulga** [donaldzou/WGDashboard#236]
**Describe The Problem**

I had this configuration:
```
[Interface]
Address = 10.100.0.1/24
SaveConfig = true
PostUp = ...
PostDown = ...
ListenPort = 51000
```

When I create a new user via the dashboard, then the Address in the configuration is reset to `10.100.0.1/32`. In its turn, it breaks the discovery of available IP addresses for new users that I create afterwards.

**Comment by donaldzou** [comment]
Hi, will this happen if you control the interface with `wg-quick`?

**Comment by egorshulga** [comment]
Unfortunately, I don't have the setup anymore. Sorry, can't test that. I believe we may close this bug, until someone else stumbled upon something similar

**Comment by donaldzou** [comment]
No problem. Sorry couldn't provide help back then :(
