### ISSUE TITLE
too much memory used by web ui

### ISSUE THREAD

**Issue by nandish486** [donaldzou/WGDashboard#237]
I have centos 7 with 8GB ram and 4 core .

its start smooth but when create new peer that time its use too much memory (python 3.7) in additionally hang a server for 2 to 3 minutes and all connection gone down.

so please look into.

**Comment by Sardelka9515** [comment]
Same here

**Comment by koffein7755** [comment]
When adding or deleting a user, the server hangs, memory load 100%

**Comment by donaldzou** [comment]
This issue is solved in `v4`. Will be releasing soon.
