### ISSUE TITLE
Reset user traffic option

### ISSUE THREAD

**Issue by eream24** [donaldzou/WGDashboard#240]
Hello,

I think if you add "reset user traffic" option to web panel, it will be so useful.

Now i am handling this option maually with bash script and work with DB sqlite file.

**Comment by eduardorosabales** [comment]
> Hello,
> 
> I think if you add "reset user traffic" option to web panel, it will be so useful.
> 
> Now i am handling this option maually with bash script and work with DB sqlite file.

Could you share here how you achieved it? I also need to do that manually until they implement it on the web.

**Comment by donaldzou** [comment]
> > Hello,
> > I think if you add "reset user traffic" option to web panel, it will be so useful.
> > Now i am handling this option maually with bash script and work with DB sqlite file.
> 
> Could you share here how you achieved it? I also need to do that manually until they implement it on the web.

What you can do is connect to the DB file with a sqlite client, navigate to the table `<config_name>_transfer` and find the correspondent peer and remove the row and restart the dashboard.

**Comment by donaldzou** [comment]
This is implemented in `v4` :)
