### ISSUE TITLE
Disable internet connetion check on docker container startup

### ISSUE THREAD

**Issue by eream24** [donaldzou/WGDashboard#241]
Hello,

some times i need setup wgdashboard dockerize version in isolated or non-internet network. (For example local networks)
Because of checking internet connection for github or other links, container not start perfectly and i can't use docker version.

**Comment by DaanSelen** [comment]
If the issue is still present, please can you give more details to which image you are using and what parameters you are parsing into the docker command, or the compose.yaml?

**Comment by donaldzou** [comment]
Will close this issue due to inactivity. Please refer to #272
