### ISSUE TITLE
It is not possible to view web panel with VPN local IP in dockerize v.3.1

### ISSUE THREAD

**Issue by eream24** [donaldzou/WGDashboard#242]
Hello,
I want to explain exactly what happen.

1- In few months ago i have installed dockerize version beta v3.1 with predefined config and all thing is OK. in wireguard config, interface IP is [10.50.50.1/24](http://10.50.50.1/24) and i can access web panel with [10.50.50.1:10086](http://10.50.50.1:10086/) or docker-container-ip:[10086](tel:10086)

2- Some days ago, i have installed dockerize v3.1 in other server with new config. Container IP is [172.16.20.2](http://172.16.20.2/) All thing OK but i can't view web panel with user VPN connections. So i can't view [10.50.50.1:10086](http://10.50.50.1:10086/) and [172.16.20.2:10086](http://172.16.20.2:10086/) through VPN. But have ping to [10.50.50.1](http://10.50.50.1/) and [172.16.20.2](http://172.16.20.2/) and can download index page with wget correctly. I have installed other services like Nginx in wgdashboard container and also can't view any cotainer web panel services in that container. also other containers webpanel like [172.16.20.4:80](http://172.16.20.4/) + [172.16.20.7:8080](http://172.16.20.7:8080/) is accessible through VPN from browser.

3- when i downgrade from v3.1 to v3.0.6 all problems solved! But some features (for example create new wireguard config) is not available.

i have checked this process some times.

**Comment by DaanSelen** [comment]
Can you check in the logs if WireGuard-Dashboard (WGDashboard) was able to allocate the Ip-address succesfully, or if there are any issues when running the `wgd.sh debug` command.

**Comment by donaldzou** [comment]
Will move this issue to #272 :)
