### ISSUE TITLE
Change configuration via Rest Api

### ISSUE THREAD

**Issue by rjjrbatarao** [donaldzou/WGDashboard#245]
**Is your feature request related to a problem? Please describe.**
I wanted to automate some task like user creation etc on the fly without interaction to dashboard, adding rest api would 
make this possible.

**Describe the solution you'd like*
no solution so far

**Comment by barryboom** [comment]
where or how are you looking to send the API call from ?

**Comment by donaldzou** [comment]
Do you mean you want to run some automation on peers?

**Comment by rjjrbatarao** [comment]
yes we like to automate creation and disabling peers from different servers and its possible through rest api, hmm we saw some rest api implementation does WGDashboard still operable with this implementations? https://github.com/suquant/wgrest https://github.com/FokiDoki/WireRest

**Comment by donaldzou** [comment]
> yes we like to automate creation and disabling peers from different servers and its possible through rest api, hmm we saw some rest api implementation does WGDashboard still operable with this implementations? https://github.com/suquant/wgrest https://github.com/FokiDoki/WireRest

A Rest API is definitely possible, since the frontend is already using some kind of rest api... all the endpoints is just scattered around lol. In the next release I'm planning re-organize all the endpoints and simply adding a token/API-key mechanism to request directly to each API.

**Comment by rjjrbatarao** [comment]
> > yes we like to automate creation and disabling peers from different servers and its possible through rest api, hmm we saw some rest api implementation does WGDashboard still operable with this implementations? https://github.com/suquant/wgrest https://github.com/FokiDoki/WireRest
> 
> A Rest API is definitely possible, since the frontend is already using some kind of rest api... all the endpoints is just scattered around lol. In the next release I'm planning re-organize all the endpoints and simply adding a token/API-key mechanism to request directly to each API.

Thats great! this feature make a way for us to automate some task and use the wonderful dashboard to monitor devices amazing project, looking forward to this. Seamless integration from other systems would also be possible with this addition.

**Comment by donaldzou** [comment]
This is implemented in `v4` :) Will close now.
