### ISSUE TITLE
option to use external mysql as database server

### ISSUE THREAD

**Issue by rjjrbatarao** [donaldzou/WGDashboard#247]
**Is your feature request related to a problem? Please describe.**
using external server helps in making common authentication and settings for all vpn servers, so we can do loadbalacing for all servers, is it possible to do this? what we can think is make a synchronized /etc/wireguard folder for all the wireguard servers and add a load balancer, the problem will be each dashboard is needed to be configured one by one so we are thingking if we can just use external database for this and every vpn servers are connected to it centrally

**Describe the solution you'd like**
other solutions uses complex automations to sync wireguard settings and peers across multiple servers.

**Comment by rjjrbatarao** [comment]
hmm im thinking rest api would be the best way to do this? we like to just work on one dashboard and all vpn servers would synchronize with the settings and configurations

**Comment by Bialri** [comment]
It might be a good idea. Actually this feature can be implement by using ORM such as sqlalchemy. I'm not sure about synchronizing wireguard config, but i think we can find solution. Let's push this topic to attract attention and get acceptance from owner!

**Comment by rjjrbatarao** [comment]
@Bialri may be this can be used https://nats.io/ for the wireguard config through the wgdashboard any changes to servers with the dashboard will update all distributed wgdashboard cluster, this will be an awesome feature since nats also support mesh cluster, automatic scaling can be done

**Comment by Bialri** [comment]
@rjjrbatarao yes, so the challenge is to make loadbalancer. Also it can be a connector to existing loadbalancer, such as nginx, but script should update configuration at cluster and provide monitoring for servers. Can we discus and make it together? I'm insterested about this feature.

**Comment by rjjrbatarao** [comment]
@Bialri I found other solutions but it doesnt WGDashboard anymore same concept with what im planning and its also opensource https://docs.netmaker.io/about.html#what-is-netmaker
