### ISSUE TITLE
Switch to make wgX interface to auto start on boot

### ISSUE THREAD

**Issue by rjjrbatarao** [donaldzou/WGDashboard#248]
**Is your feature request related to a problem? Please describe.**
restarting server would turn off all wgX interfaces

**Describe the solution you'd like**
it would be nice to add a switch to enable wgX interfaces to autostart on boot.
here are some quick commands we have to do on each interfaces
```
sudo systemctl enable wg-quick@wg0.service
sudo systemctl daemon-reload
```

**Comment by donaldzou** [comment]
Please refer to #293.
