### ISSUE TITLE
Wrong server status

### ISSUE THREAD

**Issue by Upellift99** [donaldzou/WGDashboard#253]
**Describe The Problem**
Everything seems to work, it's great! except the **status of the server:** it says in the dashboard that it's stopped, but it's actually running, and the connected peers are even well displayed!
I tried to restart the WireGuard server, WGDashboard and even the machine itself, but the problem is still there.

**Expected Error / Traceback**
When I try to switch from OFF, it says:
```
wg-quick: 'wg_server' already exists
```
and it stays OFF.

**To Reproduce**
I followed the standard installation, and my WireGuard was already set up.

**OS Information:**
 - OS: Debian GNU/Linux 10 (buster)
 - Python Version: Python 3.7.3

**Sample of my `wg_server.conf` file**
```
[Interface]
Address = 10.ABC.0.1/22
SaveConfig = true
ListenPort = 15082
PrivateKey = XXXXXXXXXXXXXXXXXX

[Peer]
PublicKey = XXXXXXXXXXXXXXXXXX
AllowedIPs = 10.ABC.0.2/32

[Peer]
PublicKey = XXXXXXXXXXXXXXXXXX
AllowedIPs = 10.ABC.1.5/32
.......
```

**Comment by donaldzou** [comment]
Can you check if you have another configuration with the name `wg_server` under `/etc/wireguard`?

**Comment by donaldzou** [comment]
That's weird... can you type `wg` into your terminal and see if there's a configuration already running, if not follow this:
```bash
sudo apt-get install -y net-tools
ifconfig
```
then see if there is an interface called `wg_server`

**Comment by Upellift99** [comment]
Yes :
```
root@vps:~# wg
interface: wg_server
  public key: XXXXXXXXXXXXXXXXXX
  private key: (hidden)
  listening port: 15082

peer: ....
....
```
and I see also the interface `wg_server` with `ifconfig`

**Comment by donaldzou** [comment]
I think I found the issue, it has nothing to do with WireGuard or your settings. It was caused by the library I used to parse network interface that does not parse any interface name containing `_` (underscore) hence the dashboard think the configuration is not "on". I think you can do that following for a workaround:
```
cd /etc/wireguard
wg-quick down wg_server
mv wg_server.conf wgserver.conf # rename it to without underscore
wg-quick up wgserver
```
and now should be good to control the configuration from the dashboard.

The issue is reported in the library's repo: https://github.com/ftao/python-ifcfg/issues/70#issue-1374082764

**Comment by Upellift99** [comment]
Kudos, you're a whiz! I would have never figured it out. I made the change, and everything is working like a charm! Again, kudos and thank you!

**Comment by Upellift99** [comment]
Thank you for approving the pull request 😁
