### ISSUE TITLE
RuntimeError: Got results that don't belong to a device

### ISSUE THREAD

**Issue by orojlo** [donaldzou/WGDashboard#255]
After Run Dashboard and login get this error :
---
[2024-02-16 21:01:33,924] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/root/wgdashboard/src/dashboard.py", line 734, in index
    return render_template('index.html', conf=get_conf_list(), msg=msg)
  File "/root/wgdashboard/src/dashboard.py", line 502, in get_conf_list
    temp = {"conf": i, "status": get_conf_status(i), "public_key": get_conf_pub_key(i)}
  File "/root/wgdashboard/src/dashboard.py", line 475, in get_conf_status
    ifconfig = dict(ifcfg.interfaces().items())
  File "/usr/local/lib/python3.10/dist-packages/ifcfg/__init__.py", line 70, in interfaces
    return Parser(ifconfig=ifconfig).interfaces
  File "/usr/local/lib/python3.10/dist-packages/ifcfg/parser.py", line 34, in __init__
    self.parse(self.ifconfig_data)
  File "/usr/local/lib/python3.10/dist-packages/ifcfg/parser.py", line 76, in parse
    raise RuntimeError(
RuntimeError: Got results that don't belong to a device
------
 i think ipv6 is not supported because after disable ipv6 panel start without any error!
do you have any solutions for this problem?

**OS Information:**
 - OS:Ubuntu 22.04
 - Python Version: v3.10

**Comment by donaldzou** [comment]
> Did you find any way to solve that?
> 
> 
> 
> I also tried `pip install ifcfg` but no luck.

Hi! Can you first check if `net-tools` is installed by `sudo apt-get install net-tools` and then use `python3 -m pip install ifcfg` and let me know what does it show please?

**Comment by donaldzou** [comment]
> > > Did you find any way to solve that?
> > > I also tried `pip install ifcfg` but no luck.
> > 
> > 
> > Hi! Can you first check if `net-tools` is installed by `sudo apt-get install net-tools` and then use `python3 -m pip install ifcfg` and let me know what does it show please?
> 
> ```
> root@wireguard:~/wgdashboard/src# python3 -m pip install ifcfg
> Collecting ifcfg
>   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79f26ab20d30>: Failed to establish a new connection: [Errno -2] Name or service not known')': /packages/d8/35/d5d8da34881946022e311693a875e2d162045f20ea17d7d33707ab929eb8/ifcfg-0.24-py2.py3-none-any.whl
> 
> WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79f26ab20370>: Failed to establish a new connection: [Errno -2] Name or service not known')': /packages/d8/35/d5d8da34881946022e311693a875e2d162045f20ea17d7d33707ab929eb8/ifcfg-0.24-py2.py3-none-any.whl
> ```

Hi, seems like the error is saying you're not connected to Internet. `pip` tried to get this URL: `https://files.pythonhosted.org/packages/d8/35/d5d8da34881946022e311693a875e2d162045f20ea17d7d33707ab929eb8/ifcfg-0.24-py2.py3-none-any.whl` but failed. Can you check if your system is connected to the internet, or is there any proxy that is preventing you connect to the python dependency repo?

**Comment by donaldzou** [comment]
Considering to drop `ifcfg`.. It is not stable at all. Refer to #293
