### ISSUE TITLE
Not Working and Outdated

### ISSUE THREAD

**Issue by eakteam** [donaldzou/WGDashboard#257]
@donaldzou Is this project still maintained or not? 
It seems to be very outdated (it doesn't work with most of LTS OS versions) and too many issues are involved when trying to install and use it.

If it is still mainttained, is there any ETA when we can expect a release which will support LTS versions and newer ones?
Regards.

**Comment by zaknick** [comment]
I've been studying various Wireguard webGUIs and can attest to this being a doable project for any Linux sysadmin. Ifconfig not being present is a non-issue to anybody with basic knowledge of server administration. 

The license on Donald's WGDashboard is very generous; others aren't so altruistic.

I for one am very grateful for all his work.
