### ISSUE TITLE
All connected Peers are listed as Untitled instead of showing their name

### ISSUE THREAD

**Issue by dancb10** [donaldzou/WGDashboard#258]
Is there a specific wireguard config format that we must follow tho also display the Peers names? Seems like I can see all the transferred data for each peer, their endpoints, allowed ips, etc but all peers are listed in the UI as Unitled. I've been trying to read from the code how do you parse the wg0.conf file and extract the name?

**Comment by donaldzou** [comment]
Hi! Unfortunately the dashboard will not parse comments in the configuration file due to it could be any format. To set the peer's name, you can do it through the UI. Sorry about that.

**Comment by nv6** [comment]
How exactly is this implemented? What is the expected comment format in order for peer name to be automatically set from the config? The linked roadmap issue doesn't explain this at all, nor does the documentation.
