### ISSUE TITLE
sidebar is shown twice after upgrade 3.0.6 to 3.1-dev then hide some peers

### ISSUE THREAD

**Issue by jeanphiLouys** [donaldzou/WGDashboard#259]
**Describe The Problem**
after login, the sidebar is shown to time,
half of screen is ok with sidebar and content (wgX and peers)
in the middle of the screen a second time sidebar is shown on the whole screen and hide the peers list

**Expected Error / Traceback**
```
none
```

**To Reproduce**
installed version v3.0.6 => rename wgdashboard folder after wgd.sh stop
moved the folder to wgdashboardv3.0.6
git the version 3.1-dev
installed completely
set the wg-dashboard.ini with old settings (admin pass and all other settings), but not replaced the whole file (some settings are new on the new one)
copy wgdahsboard/src/db to the new environnement then start
 (same problem on two server upgraded, not on a fresh one installed)

**OS Information:**
 - OS: Debian GNU/Linux 11 (bullseye) runnig on LXC
 - Python Version: Python 3.9.2

**Sample of your `.conf` file**
```
[Account]
username = admin
password = xxxxxx

[Server]
wg_conf_path = /etc/wireguard
app_ip = 0.0.0.0
app_port = 80
auth_req = true
version = v3.1
dashboard_refresh_interval = 60000
dashboard_sort = status
dashboard_theme = light

[Peers]
peer_global_dns = 172.17.xx.x,domain.local
peer_endpoint_allowed_ip = 172.17.xx.0/24,172.17.xxx.0/24
peer_display_mode = list
remote_endpoint = vpn.server.name
peer_mtu = 1420
peer_keep_alive = 21
```
on the capture, the back of the yellow line is fixed and hide peer list

![Screenshot 2024-03-15 005835](https://github.com/donaldzou/WGDashboard/assets/149914608/d8c24bf3-fa32-4de4-8f1d-fa103b750137)

**Comment by jeanphiLouys** [comment]
Clean LXC debian 11 server installed as basic + wiregaurd + python3/python3-pip/git only and the probleme not reappear
i think the LXC Wireguard template used is the source of the problem and not WGDashboard itself

Sorry

**Comment by donaldzou** [comment]
Hi, are you using using this: https://github.com/tteck/Proxmox/blob/6037d381ef3f061357b6d689f5fa89df26310c59/ct/wireguard.sh ? Interestingly this is the first time I'm seeing this script lol.. and surprised my project got included in some other huge project ;)

I don't think the script have issue, I'm suspecting that you install `v3.1-dev` instead of `v3.0.6` <= the official release. I believe the `v3.1-dev` branch have bugs in it and no longer maintaining. Currently I'm working on the `v4` branch if you're interested :)

**Comment by barryboom** [comment]
> Hi, are you using using this: https://github.com/tteck/Proxmox/blob/6037d381ef3f061357b6d689f5fa89df26310c59/ct/wireguard.sh ? Interestingly this is the first time I'm seeing this script lol.. and surprised my project got included in some other huge project ;)
> 
> I don't think the script have issue, I'm suspecting that you install `v3.1-dev` instead of `v3.0.6` <= the official release. I believe the `v3.1-dev` branch have bugs in it and no longer maintaining. Currently I'm working on the `v4` branch if you're interested :)

the script here links to v 3.0.6 not 3.1 which i actually think is a much better build than 3.0.6 looks better just a pity it advises there is a new version available when the -Dev version is installed which can be confusing but really like the dark mode and features v3.1 over 3.0.6

**Comment by donaldzou** [comment]
> > Hi, are you using using this: https://github.com/tteck/Proxmox/blob/6037d381ef3f061357b6d689f5fa89df26310c59/ct/wireguard.sh ? Interestingly this is the first time I'm seeing this script lol.. and surprised my project got included in some other huge project ;)
> > I don't think the script have issue, I'm suspecting that you install `v3.1-dev` instead of `v3.0.6` <= the official release. I believe the `v3.1-dev` branch have bugs in it and no longer maintaining. Currently I'm working on the `v4` branch if you're interested :)
> 
> the script here links to v 3.0.6 not 3.1 which i actually think is a much better build than 3.0.6 looks better just a pity it advises there is a new version available when the -Dev version is installed which can be confusing but really like the dark mode and features v3.1 over 3.0.6

@barryboom Yeah I understand the confusion, it was a bad design when I coded the update checker lol. Will improve this in the upcoming `v4` :)

**Comment by blca1** [comment]
> `v4`

When can I try it?

**Comment by donaldzou** [comment]
> > `v4`
> 
> When can I try it?

You can try it now, you just need to clone the `v4` branch and do `python3 -m pip install -r requirements.txt` -> `python3 daashboard_new.py` :)

**Comment by blca1** [comment]
@donaldzou clone faild "git clone -b v4 https://github.com/donaldzou/WGDashboard.git wgdashboard
fatal: destination path 'wgdashboard' already exists and is not an empty directory."

**Comment by donaldzou** [comment]
> @donaldzou clone faild "git clone -b v4 https://github.com/donaldzou/WGDashboard.git wgdashboard fatal: destination path 'wgdashboard' already exists and is not an empty directory."

> very loose on instructions there for sure but maybe best wait until its properly relased even as a beta version and proper instructions to install or update existing dashboard

I have to admit using `v4` is not a good idea in this stage since it is still under development. I’m basically doing a revamp from my old codes (it was some bad code lol). If you really want to try it out, according to your error, you would need to remove `wgdashboard` from your current directory and then rerun the commands I provided above :)

**Comment by deker1176** [comment]
![image](https://github.com/donaldzou/WGDashboard/assets/52081059/db2bfdc3-21b2-4769-ae58-167876cb4d7d)

**Comment by deker1176** [comment]
this is if you install v4

**Comment by donaldzou** [comment]
@deker1176 Hi, `v4` is still under development. Please follow my instruction on https://github.com/donaldzou/WGDashboard at the top :)

**Comment by donaldzou** [comment]
Close due to inactivity.
