### ISSUE TITLE
Please add usage time limitation

### ISSUE THREAD

**Issue by rlrexyz** [donaldzou/WGDashboard#260]
For example, we should be able to choose the date when a peer will close.

Example: until 01.0.1.2025

After the specified period of time, the peer becomes deactivated.

**Comment by donaldzou** [comment]
Hi @iRexyz, yes this will be implement into `v4.0`, and thank you for the suggestion :)

**Comment by donaldzou** [comment]
This function is implemented in `v4`. Refer to #293
