### ISSUE TITLE
Remove DNS as a mandatory item

### ISSUE THREAD

**Issue by 777petruh** [donaldzou/WGDashboard#263]
Is it possible to change this parameter in your panel? I don't use DNS. And the panel forcibly asks me to indicate it.

**Comment by hoggatt** [comment]
+1

I have to manually remove the DNS on each client because this requirement breaks in certain cases.

**Comment by barryboom** [comment]
DNS is set during the install of WG, And as far as i know is needed to instruct somewhere for the client to be able to lookup the endpoint especially when using a a web DNS rather than RAW like i do for my server endpoint.

**Comment by hoggatt** [comment]
> DNS is set during the install of WG, And as far as i know is needed to instruct somewhere for the client to be able to lookup the endpoint especially when using a a web DNS rather than RAW like i do for my server endpoint.

Well, I can say from personal experience that having wireguard with a DNS specified breaks my entire network on the client. If I remove the DNS from wireguard, everything works as expected. YMMV, but this seems like sufficient reason alone to make DNS the default, but not required.

**Comment by donaldzou** [comment]
Hi all, thank you for bringing this issue up. When I was designing the system, DNS is required in my use cases since I'm using to find my WG server. I will push an update to the newest version (v3.6) later today and I already removed the required in the upcoming v4.

Please let me know if there any other issues :)

**Comment by donaldzou** [comment]
Solved in https://github.com/donaldzou/WGDashboard/commit/9e38137e769c22f23db84384755e96fe10e6af56 :)

**Comment by hoggatt** [comment]
Thanks so much! I did NOT expect this so soon. Excited for v4!
