### ISSUE TITLE
Incorrect version display

### ISSUE THREAD

**Issue by 777petruh** [donaldzou/WGDashboard#264]
![image](https://github.com/donaldzou/WGDashboard/assets/18466470/e4ea3423-9e0d-4cb7-befd-7dc14574500a)
![image](https://github.com/donaldzou/WGDashboard/assets/18466470/a8090ecc-834c-4ba3-8b3b-dcb86ddf7573)

I updated to version v3.0.6.1 but it still shows the update prompt. And the version below is v3.0.6. Although in terms of functionality the version is v3.0.6.1 (DNS has become optional)

**Comment by donaldzou** [comment]
Uh oh totally my bad lol... Forgot to update the version number, will do another release to fix this. Sorry about that.

**Comment by donaldzou** [comment]
All good now :)
