### ISSUE TITLE
internal server error when having multiple IPs active on server.

### ISSUE THREAD

**Issue by barryboom** [donaldzou/WGDashboard#266]
**Describe The Problem**
trying to set up a multi config system on single server. adding multiple WG instances like wg0 , wg1 , wg2 etc that part works fine
i also want to assign alias IPs or multiple IPs which will still route back to the same server this also works fine in terms of wireguard in that i can connect to the WG connection using either of the Configs and multiple IPs 

However what seems to stop working is the dashboard once i setup the secondary virtual interface and actiavte the addional IP on the server.

Error that comes up after logon is as below :

**### Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.**

as soon as i deactivate the secondary IP and reboot it all start working fine again.

**OS Information:**
 - OS: [e.g. Ubuntu 18.02] Ubuntu 24.04 
 - Python Version: [e.g v3.7]

**Comment by donaldzou** [comment]
It seems like this is a Flask issue? I still to recreate it on my side to make sure

**Comment by barryboom** [comment]
i have managed to overcome the issue by using a bridge rather than alias of exisitng interface this seemed to work.
