### ISSUE TITLE
internal server error 

### ISSUE THREAD

**Issue by mix0nSPb** [donaldzou/WGDashboard#271]
**Describe The Problem**
After installing the panel on a new server and trying to log in to the panel, it gives the error "internal server error"

in "debug" mode the console displays an error, as shown in the screenshot.

please tell me what is the problem?

**OS Information:**
 - OS: [e.g. Ubuntu 20.04]
 - Python Version: [e.g v3.9]

<img width="965" alt="Снимок экрана 2024-05-24 в 00 23 17" src="https://github.com/donaldzou/WGDashboard/assets/106708944/f6c399c7-5127-4645-a0ed-166f9130f09e">

**Comment by donaldzou** [comment]
Close due to inactivity.
