### ISSUE TITLE
Dont work/start on Debian

### ISSUE THREAD

**Issue by solisinvictum** [donaldzou/WGDashboard#280]
Like the Title says. (Debian latest Stable 12.5)

1) Follow instructions, check requirements from https://github.com/donaldzou/WGDashboard

After ./wgd.sh start : 
```

user@wireguard:~/wgdashboard/src$ sudo chmod u+x wgd.sh 
user@wireguard:~/wgdashboard/src$ sudo ./wgd.sh install
------------------------------------------------------------
| Starting to install WGDashboard                          |
| Upgrading pip                                            |
| Installing latest Python dependencies                    |
| WGDashboard installed successfully!                      |
| Enter ./wgd.sh start to start the dashboard              |
------------------------------------------------------------
user@wireguard:~/wgdashboard/src$ sudo ./wgd.sh start
------------------------------------------------------------
| Starting WGDashboard with Gunicorn in the background.    |
Failed to read config file: /home/user/wgdashboard/src/gunicorn.conf.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/wgdashboard/src/gunicorn.conf.py", line 2, in <module>
    import dashboard
  File "/home/user/wgdashboard/src/dashboard.py", line 23, in <module>
    import ifcfg
ModuleNotFoundError: No module named 'ifcfg'
| Log files is under log/                                  |
------------------------------------------------------------
user@wireguard:~/wgdashboard/src$ 

```

**Comment by barryboom** [comment]
been answered already please see https://github.com/donaldzou/WGDashboard/issues/220

**Comment by barryboom** [comment]
this is the reason and that along with likely others will need manually installed.

ModuleNotFoundError: No module named 'ifcfg'

**Comment by donaldzou** [comment]
The issue is caused by some fresh installed Debian does not include the network tool aka `ifconfig`.

**Comment by donaldzou** [comment]
And I will make sure the check is implemented in the next release.

**Comment by DaanSelen** [comment]
Otherwise, use a Python venv

**Comment by DaanSelen** [comment]
> > Otherwise, use a Python venv
> 
> I don't think venv would solve the main issue, since the system is lacking the networking tool

With the venv you don't have to pass in the "--break-system-packages" which is not a fun term to be passing. For the way how to do this, I have used it in the Docker image.

**Comment by donaldzou** [comment]
Ah I see what you meant, yes a venv would be the best solution.. Indeed I'm planning to have venv include in `v4`

**Comment by DaanSelen** [comment]
> Ah I see what you meant, yes a venv would be the best solution.. Indeed I'm planning to have venv include in `v4`

I cannot say if it is the best, but is *a* solution 😁.

**Comment by donaldzou** [comment]
Close due to inactivity.
