### ISSUE TITLE
Don't work on Ubuntu

### ISSUE THREAD

**Issue by warpwanderer** [donaldzou/WGDashboard#284]
**Describe The Problem**
When going to http://<server ip address>:10086 the message is displayed: Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Expected Error / Traceback**
```
(myenv) root:~/wgdashboard/src$ sudo ./wgd.sh start
------------------------------------------------------------
| Starting WGDashboard with Gunicorn in the background.    |
Failed to read config file: /home/medraut/wgdashboard/src/gunicorn.conf.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/medraut/wgdashboard/src/gunicorn.conf.py", line 2, in <module>
    import dashboard
  File "/home/medraut/wgdashboard/src/dashboard.py", line 23, in <module>
    import ifcfg
ModuleNotFoundError: No module named 'ifcfg'
| Log files is under log/                                  |
------------------------------------------------------------
(myenv) root:~/wgdashboard/src$ ./wgd.sh start
------------------------------------------------------------
| Starting WGDashboard with Gunicorn in the background.    |
| Log files is under log/                                  |
------------------------------------------------------------

```

**To Reproduce**
http://<server ip-address>:10086 in the client browser

**OS Information:**
 - OS: Ubuntu 24.04 LTS
 - Python 3.12.3

**Comment by Houdoe** [comment]
same here

**Comment by donaldzou** [comment]
Hi, could you run `python3 -m pip install -r requirements.txt` in your virtual environment and see if that helps?

**Comment by donaldzou** [comment]
Hi @Houdoe, are you using an virtual environment? If not, I suggest you to create one since the newer version of Python does not allow user to install global dependencies by default. You can follow this if you're using Debian/Ubuntu system:

```
$ sudo apt-get install python3.12-venv        << Replace the python version you have on your system
$ cd wgdashboard/src
$ python3 -m venv ./venv
$ source ./venv/bin/activate
(venv) $ python3 -m pip install -r requirements.txt
(venv) $ ./wgd.sh start
```

Let me know if this helps :)

**Comment by warpwanderer** [comment]
> Hi, could you run `python3 -m pip install -r requirements.txt` in your virtual environment and see if that helps?

Yes, I used a virtual environment, everything was installed, but when I go to the IP it gives the error ```Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. ```
if you do not use a virtual environment, the packages are not installed and an error appears on the server related to import ifcfg

**Comment by warpwanderer** [comment]
> Hi, are you still encountering the issue even with venv? Would you able to paste the error when you run `./wgd.sh debug` please?

when venv the error appears in the browser

**Comment by donaldzou** [comment]
> > Hi, are you still encountering the issue even with venv? Would you able to paste the error when you run `./wgd.sh debug` please?
> 
> when venv the error appears in the browser

I see, what if you run `./wgd.sh debug` and does it show any error in the console when you access the dashboard?

**Comment by donaldzou** [comment]
> > Hi, are you still encountering the issue even with venv? Would you able to paste the error when you run `./wgd.sh debug` please?
> 
> when venv the error appears in the browser

I see, what if you run `./wgd.sh debug` and does it show any error in the console when you access the dashboard?

**Comment by warpwanderer** [comment]
> ./wgd.sh debug
It turns out the port is occupied by another program. Can I edit the launch port in the conf file?
```
(venv) root@quarrelsome-verse:~/wgdashboard/src$ ./wgd.sh debug
------------------------------------------------------------
| Starting WGDashboard in the foreground.                  |
 * Serving Flask app 'WGDashboard'
 * Debug mode: off
Address already in use
Port 10086 is in use by another program. Either identify and stop that program, or start the server with a different port.
```

**Comment by warpwanderer** [comment]
> > > Hi, are you still encountering the issue even with venv? Would you able to paste the error when you run `./wgd.sh debug` please?
> > 
> > 
> > when venv the error appears in the browser
> 
> I see, what if you run `./wgd.sh debug` and does it show any error in the console when you access the dashboard?


I killed the process on the port, restarted it, again the same error in the browser, but the debug shows:
```
(venv) medraut@:~/wgdashboard/src$ ./wgd.sh debug
------------------------------------------------------------
| Starting WGDashboard in the foreground.                  |
 * Serving Flask app 'WGDashboard'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:10086
 * Running on http://*.*.*.* :10086
Press CTRL+C to quit
[2024-07-04 20:27:21,704] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/medraut/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 878, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 1253, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/dashboard.py", line 639, in auth_req
    g.db = connect_db()
           ^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/dashboard.py", line 66, in connect_db
    return sqlite3.connect(os.path.join(configuration_path, 'db', 'wgdashboard.db'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
*.*.*.*  - - [04/Jul/2024 20:27:21] "GET / HTTP/1.1" 500 -
[2024-07-04 20:27:21,975] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/medraut/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 878, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 1253, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/dashboard.py", line 639, in auth_req
    g.db = connect_db()
           ^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/dashboard.py", line 66, in connect_db
    return sqlite3.connect(os.path.join(configuration_path, 'db', 'wgdashboard.db'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
*.*.*.*  - - [04/Jul/2024 20:27:21] "GET /favicon.ico HTTP/1.1" 500 -
[2024-07-04 20:27:22,803] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/medraut/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 878, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 1253, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/dashboard.py", line 639, in auth_req
    g.db = connect_db()
           ^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/dashboard.py", line 66, in connect_db
    return sqlite3.connect(os.path.join(configuration_path, 'db', 'wgdashboard.db'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
*.*.*.* - - [04/Jul/2024 20:27:22] "GET / HTTP/1.1" 500 -
[2024-07-04 20:27:23,014] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/medraut/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 878, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 1253, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/dashboard.py", line 639, in auth_req
    g.db = connect_db()
           ^^^^^^^^^^^^
  File "/home/medraut/wgdashboard/src/dashboard.py", line 66, in connect_db
    return sqlite3.connect(os.path.join(configuration_path, 'db', 'wgdashboard.db'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
95.25.214.72 - - [04/Jul/2024 20:27:23] "GET /favicon.ico HTTP/1.1" 500 -

```

**Comment by donaldzou** [comment]
Seems like the dashboard can't find the database... I'm thinking will it caused by permission? Could you please try using sudo and run debug and see if that helps?

**Comment by warpwanderer** [comment]
> Seems like the dashboard can't find the database... I'm thinking will it caused by permission? Could you please try using sudo and run debug and see if that helps?
does not start if used sudo error ModuleNotFoundError: No module named 'ifcfg', without sudo start ok
```
medraut@:~/wgdashboard/src$ sudo ./wgd.sh start
[sudo] password for medraut:
------------------------------------------------------------
| Starting WGDashboard with Gunicorn in the background.    |
Failed to read config file: /home/medraut/wgdashboard/src/gunicorn.conf.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/medraut/wgdashboard/src/gunicorn.conf.py", line 2, in <module>
    import dashboard
  File "/home/medraut/wgdashboard/src/dashboard.py", line 23, in <module>
    import ifcfg
ModuleNotFoundError: No module named 'ifcfg'
| Log files is under log/                                  |
------------------------------------------------------------

```

**Comment by warpwanderer** [comment]
> > Seems like the dashboard can't find the database... I'm thinking will it caused by permission? Could you please try using sudo and run debug and see if that helps?
> does not start if used sudo error ModuleNotFoundError: No module named 'ifcfg', without sudo start ok
> 
> ```
> medraut@:~/wgdashboard/src$ sudo ./wgd.sh start
> [sudo] password for medraut:
> ------------------------------------------------------------
> | Starting WGDashboard with Gunicorn in the background.    |
> Failed to read config file: /home/medraut/wgdashboard/src/gunicorn.conf.py
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
>     spec.loader.exec_module(mod)
>   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "/home/medraut/wgdashboard/src/gunicorn.conf.py", line 2, in <module>
>     import dashboard
>   File "/home/medraut/wgdashboard/src/dashboard.py", line 23, in <module>
>     import ifcfg
> ModuleNotFoundError: No module named 'ifcfg'
> | Log files is under log/                                  |
> ------------------------------------------------------------
> ```

**Comment by donaldzou** [comment]
Hi,

Sorry for the confusion. I meant using your venv, then sudo.

Something like:

$ source <your venv path>
$ sudo ./wgd.sh start

:)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by warpwanderer** [comment]
That's exactly what I did

**Comment by donaldzou** [comment]
> > > Seems like the dashboard can't find the database... I'm thinking will it caused by permission? Could you please try using sudo and run debug and see if that helps?
> 
> 
> 
> does not start if used sudo error ModuleNotFoundError: No module named 'ifcfg', without sudo start ok
> 
> 
> 
> ```
> 
> medraut@:~/wgdashboard/src$ sudo ./wgd.sh start
> 
>  [sudo] password for medraut:
> 
>  ------------------------------------------------------------
> 
>  | Starting WGDashboard with Gunicorn in the background.    |
> 
>  Failed to read config file: /home/medraut/wgdashboard/src/gunicorn.conf.py
> 
>  Traceback (most recent call last):
> 
>    File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
> 
>      spec.loader.exec_module(mod)
> 
>    File "<frozen importlib._bootstrap_external>", line 995, in exec_module
> 
>    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
> 
>    File "/home/medraut/wgdashboard/src/gunicorn.conf.py", line 2, in <module>
> 
>      import dashboard
> 
>    File "/home/medraut/wgdashboard/src/dashboard.py", line 23, in <module>
> 
>      import ifcfg
> 
>  ModuleNotFoundError: No module named 'ifcfg'
> 
>  | Log files is under log/                                  |
> 
>  ------------------------------------------------------------
> 
>  ```
> 
> 
> 
> 

Hmm I don't think you used venv in this one.. it should have a bracket wrapping your venv's name before each command.

**Comment by warpwanderer** [comment]
Sorry, you are right, the fact is that the first time I tried without venv,
but the second time it was venv, I sent you the old debug since it was no
different, the situation does not change if you use sudo

сб, 6 июл. 2024 г. в 11:51, Donald Zou ***@***.***>:

**Comment by DaanSelen** [comment]
Is this issue fixed?

**Comment by warpwanderer** [comment]
> Is this issue fixed?

Yes, I checked today, installed everything from the beginning, everything works fine

**Comment by DaanSelen** [comment]
So this issue is solved?

**Comment by warpwanderer** [comment]
> So this issue is solved?

Yes, that's right, we can close it, thank you.
