### ISSUE TITLE
Does not run on Ubuntu

### ISSUE THREAD

**Issue by Profik** [donaldzou/WGDashboard#285]
**Describe The Problem**
After entering the command **./wgd.sh start** 
 
Starting WGDashboard with Gunicorn in the background.  
./wgd.sh: line 104: gunicorn: command not found
Log files is under log/    

**./wgd.sh debug**
| Starting WGDashboard in the foreground.                  |
Traceback (most recent call last):
  File "/root/wgdashboard/src/dashboard.py", line 25, in <module>
    from flask import Flask, request, render_template, redirect, url_for, session, jsonify, g
ModuleNotFoundError: No module named 'flask'

**Command**
python3 -m pip install flask

Collecting flask
  Using cached flask-3.0.3-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: Werkzeug>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from flask) (3.0.3)
Requirement already satisfied: Jinja2>=3.1.2 in /usr/local/lib/python3.10/dist-packages (from flask) (3.1.4)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.10/dist-packages (from flask) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.10/dist-packages (from flask) (8.1.7)
Collecting blinker>=1.6.2 (from flask)
  Using cached blinker-1.8.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=3.1.2->flask) (2.1.5)
Using cached flask-3.0.3-py3-none-any.whl (101 kB)
Using cached blinker-1.8.2-py3-none-any.whl (9.5 kB)
Installing collected packages: blinker, flask
  Attempting uninstall: blinker
    Found existing installation: blinker 1.4
error: uninstall-distutils-installed-package

× Cannot uninstall blinker 1.4
╰─> It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**OS Information:**
 - OS: Ubuntu 20-22.04 LTS
 - Python Version: Python 3.10.12

**Comment by Profik** [comment]
**I found a solution:**
```
1. sudo apt remove python3-blinker
2. pip3 install -r requirements.txt 
```

Good luck to everyone! :)

**Comment by donaldzou** [comment]
This is fixed with venv in `v4`
