### ISSUE TITLE
Adding a private key automatically

### ISSUE THREAD

**Issue by Crashermage** [donaldzou/WGDashboard#286]
Hi there. I have a Python script that automatically generates new peer configurations. The code works correctly and creates a peer on the VPS, which then appears in WG Dashboard. The problem is that the peer's private key is not automatically added in the Dashboard. All peer settings are correct, but when I try to connect, it doesn't work until I manually add the private key. 

It there some way to add private key in WG Dashboard automatically?

![chrome_r5hqiPLQ8y](https://github.com/user-attachments/assets/da60ee60-996c-45ce-957e-7d9a5eb961e7)

**Comment by donaldzou** [comment]
Hi @Crashermage , since the `.conf` file for each Configuration in WG only stored the peer's public key, which is by WGDashboard won't be able to add private key automatically **if** the peer is not created through WGDashboard.

> IIRC, when WireGuard generate a key pair, it will generate the private key first, then generate the public key from the private key, and you can't do the other way around if I understand asymmetric cryptography correctly 😄

**Comment by donaldzou** [comment]
Close due to inactivity.
