### ISSUE TITLE
ModuleNotFoundError: No module named 'bcrypt'

### ISSUE THREAD

**Issue by BobiDikson** [donaldzou/WGDashboard#287]
Start ./wgd.sh start

Error: 
| Starting WGDashboard with Gunicorn in the background.    |
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 5, in <module>
    from gunicorn.app.wsgiapp import run
ModuleNotFoundError: No module named 'gunicorn'
| Log files is under log/    

Start ./wgd.sh debug:

| Starting WGDashboard in the foreground.                  |
Traceback (most recent call last):
  File "dashboard.py", line 18, in <module>
    import bcrypt
ModuleNotFoundError: No module named 'bcrypt'

**OS Information:**
 - OS: [e.g. Ubuntu 20.02]
 - Python Version: [e.g v3.12]

**Sample of your `.conf` file**
```

**Comment by BobiDikson** [comment]
I tried to do this, but it didn't help.
<<$ sudo apt-get install python3.12-venv        << Replace the python version you have on your system
$ cd wgdashboard/src
$ python3 -m venv ./venv
$ source ./venv/bin/activate
(venv) $ python3 -m pip install -r requirements.txt
(venv) $ ./wgd.sh start>>

**Comment by donaldzou** [comment]
Hi @BobiDikson, that is super weird...Could you try `python3 -m pip install bcrypt` in your virtual environment?

**Comment by BobiDikson** [comment]
@donaldzou 
root@Test:~/wgdashboard/src# ./wgd.sh debug
------------------------------------------------------------
| Starting WGDashboard in the foreground.                  |
Traceback (most recent call last):
  File "dashboard.py", line 20, in <module>
    import ifcfg
ModuleNotFoundError: No module named 'ifcfg'

**Comment by donaldzou** [comment]
> ## @donaldzou
> root@Test:~/wgdashboard/src# ./wgd.sh debug
> | Starting WGDashboard in the foreground. | Traceback (most recent call last): File "dashboard.py", line 20, in import ifcfg ModuleNotFoundError: No module named 'ifcfg'

Hi, sorry that you're encountering this issue.. Could you try `python3 -m pip install ifcfg` in your `venv` please? I'm still figuring out why other users also have this issue where they ran `python3 -m pip install -r requirements.txt` but still not installing all the packages.. I've tested on multiple VM and works for me lol

**Comment by BobiDikson** [comment]
~/wgdashboard/src# ./wgd.sh debug
------------------------------------------------------------
| Starting WGDashboard in the foreground.                  |
Traceback (most recent call last):
  File "dashboard.py", line 117, in <module>
    class PeerJobs:
  File "dashboard.py", line 162, in PeerJobs
    def saveJob(self, Job: PeerJob) -> tuple[bool, list] | tuple[bool, str]:
TypeError: 'type' object is not subscriptable

**Comment by donaldzou** [comment]
> ## ~/wgdashboard/src# ./wgd.sh debug
> | Starting WGDashboard in the foreground. | Traceback (most recent call last): File "dashboard.py", line 117, in class PeerJobs: File "dashboard.py", line 162, in PeerJobs def saveJob(self, Job: PeerJob) -> tuple[bool, list] | tuple[bool, str]: TypeError: 'type' object is not subscriptable

Ohhhh seems like you're running v4.0 which is still in development. If this is intended, you can clone the v4.0 branch again as I pushed some changes to it recently. If not, please follow the instruction on the main branch to install a stable version :)

**Comment by BobiDikson** [comment]
>  like you're running v4.0 

Yes. My main version is 3.1 the best, I'm doing this test on another server.
