### ISSUE TITLE
Starts only with debug v4

### ISSUE THREAD

**Issue by Johnnykson** [donaldzou/WGDashboard#289]
During normal startup nothing happens, the web interface is not available.
![Снимок экрана 2024-08-04 070831](https://github.com/user-attachments/assets/8045fd5c-ec4d-470a-93c5-9f7c8d22e798)

When using debug everything works and the web interface too.
![Снимок экрана 2024-08-04 070959](https://github.com/user-attachments/assets/f0b6043d-72e2-4446-8570-9741397e9b71)

**Comment by donaldzou** [comment]
Hi @Johnnykson,

Could you post what is the latest `error_<date>.log` under `./log` folder please? There should be some issue with Gunicorn and I'm having issue even with fresh OS :(

Just wanna make sure you're just testing it, not using it in production right 🤣  ?

**Comment by Johnnykson** [comment]
- OS: Ubuntu 20-22.04 LTS
- Python Version: Python 3.10.12

There were errors during the first installation. I think I fixed them, now `./wgd.sh` install is successful. There is no `error_<date>.log` in the` ./log` folder.
![Снимок экрана 2024-08-04 165555](https://github.com/user-attachments/assets/0a4697af-8648-4ac3-95d6-9f143e643816)
[install.txt](https://github.com/user-attachments/files/16487050/install.txt)

And yeah, I just want to see version 4, I'm curious  🤣🤣

**Comment by donaldzou** [comment]
Hi! Do you still remember what the error is you occurred in the first place?

And after the success install, is `sudo./wgd.sh start` works for you? The and port and IP is the same with debug mode

**Comment by Johnnykson** [comment]
I looked at the history, there was no error initially, i restarted with another version. I tried to install on a clean machine _(Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-117-generic x86_64))_. The error is repeated. It only starts in debug.
![Снимок экрана 2024-08-05 014804](https://github.com/user-attachments/assets/4c02d1f4-a168-434a-83b9-b80a09aa68c5)

**Comment by donaldzou** [comment]
I was able to re-create the issue lol. I'm using a fresh 22.04.4 with Python 3.10 and it won't start after install for the very first time:
<img width="780" alt="Screenshot 2024-08-04 at 3 05 46 PM" src="https://github.com/user-attachments/assets/68d12bb5-215b-4ab9-bc46-6e5f46d6f922">

But then, when I manually run the `gunicorn` command, it just works.. If you're wondering, is the command baked in `.wgd.sh` at line 240, but without all the logs
<img width="672" alt="Screenshot 2024-08-04 at 3 06 30 PM" src="https://github.com/user-attachments/assets/daad4180-a29a-4081-886f-890fe67c930e">

THEN! I removed the folder, and re-did everything, and it just works now LMAO.. idk why is causing this.. need more investigation
<img width="1003" alt="Screenshot 2024-08-04 at 3 06 51 PM" src="https://github.com/user-attachments/assets/25469e05-8785-44cc-ad47-f8a2a74d2a9d">

**Comment by donaldzou** [comment]
Hi @Johnnykson, I just pushed some new changes to the branch `v4`, not `v4.0.beta1` and I think I fixed the issue. I think it was due to the bash script exit before Gunicorn can actually spawn the workers. I've adjusted the command and added checks to see if Gunicorn is spawned, then end the script.

Feel free to test it on your side and let me know :)

**Comment by Johnnykson** [comment]
> Hi @Johnnykson, I just pushed some new changes to the branch `v4`, not `v4.0.beta1` and I think I fixed the issue. I think it was due to the bash script exit before Gunicorn can actually spawn the workers. I've adjusted the command and added checks to see if Gunicorn is spawned, then end the script.
> 
> Feel free to test it on your side and let me know :)

hangs without continuing
![Снимок экрана 2024-08-05 033738](https://github.com/user-attachments/assets/76c4455f-f3ae-4073-b59f-ba853472e275)
but if I run `gunicorn` manually, the web panel starts working and I see two processes, but the terminal still displays one `Background Thread #1 Started`
![Снимок экрана 2024-08-05 034107](https://github.com/user-attachments/assets/807731d6-3f9e-4585-9976-b4a0aecc01cd)

**Comment by donaldzou** [comment]
That's weird... I tried multiple times with a fresh 22.04.4 and it works after the update.. can you try to git clone the branch and see if it works?

**Comment by Johnnykson** [comment]
> That's weird... I tried multiple times with a fresh 22.04.4 and it works after the update.. can you try to git clone the branch and see if it works?
- Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-117-generic x86_64)

What I did:
1. reinstalled OS
2. `apt update` and `apt upgrade`
3. install WireGuard and WireGuard-Tools 
4. cloned the branch with the already fixed one `wgd.sh` and install WGDashboard

**Comment by donaldzou** [comment]
helo I'm back with some good news, seems like it was due to the actual command and not parsing it right when bash run the script.. It shouldn't but I've moved all the gunicorn configuration into the `gunicorn.conf.py`. If you have time, would you be able to try on your side plz? U can use this command to save ur time ;)

```
sudo apt-get update && apt install wireguard-tools && git clone -b v4 https://github.com/donaldzou/WGDashboard.git && cd ./WGDashboard/src && chmod +x ./wgd.sh && ./wgd.sh install
```

**Comment by donaldzou** [comment]
A complete success start should looks like this. I did the whole testing process in the "demo mode" of Ubuntu's ISO
![Screenshot 2024-08-04 at 8 33 27 PM](https://github.com/user-attachments/assets/21e46f14-91f0-48ac-89f4-ba4f5604504b)

**Comment by Johnnykson** [comment]
Everything worked, **thanks!**

**Comment by donaldzou** [comment]
Nah should be me thanking you :)
