### ISSUE TITLE
v4.0 Can't set authToken

### ISSUE THREAD

**Issue by donaldzou** [donaldzou/WGDashboard#292]
> > cannot authorize using login and password admin:admin
> 
> Hi @bkeenke, could you please check if there are any errors in `debug` mode or under console in your browser?

In debug mode in the browser console:
The "authToken" cookie does not have a valid "SameSite" attribute value defined. Soon, cookies without the "SameSite" attribute or with an incorrect value for this attribute will be considered "Lax". This means that cookies will no longer be sent to external contexts. If your application depends on this Cookie being available in any contexts, add a "SameSite=None" attribute label to it. To learn more about the "SameSite" attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite.
The problem was due to the fact that I logged in through a mobile phone, Safari, through a PC everything was fine, there was this warning in the registration window.

![изображение](https://github.com/user-attachments/assets/38d363ae-533b-4ed2-86f5-ae430fd4e8b0)
When adding a new configuration, if the address already exists, it does not allow you to change it, you have to reload the page,
same with the port

![изображение](https://github.com/user-attachments/assets/98e7609e-e272-4119-9890-1e9d497b743c)
I created wg0 but when I start it says that it already exists

_Originally posted by @bkeenke in https://github.com/donaldzou/WGDashboard/issues/290#issuecomment-2268742683_

**Comment by bkeenke** [comment]
As you wrote, the problem with vg0 was due to the fact that the vg0 config had been launched before

**Comment by donaldzou** [comment]
Is the console error still occur? May I ask which browser are you using?

**Comment by bkeenke** [comment]
I couldn’t check, I updated today and this is the error.
I use Firefox browser

![image](https://github.com/user-attachments/assets/599c5beb-4b32-4a04-9985-55de2e2c5857)

**Comment by bkeenke** [comment]
Debug:

def addLink(self, Configuration: str, Peer: str, ExpireDate: datetime = None) -> tuple[bool, message]:

**Comment by donaldzou** [comment]
Closing this issue because I believe it is fixed.
