### ISSUE TITLE
v4.0 Dashboard UI issue on Firefox 

### ISSUE THREAD

**Issue by LimonFruit** [donaldzou/WGDashboard#294]
**Describe The Problem**
Creating a schedule job on a peer doesn't work well in Firefox, specifically when selecting the date option.

**To Reproduce**
Use Firefox web browser and try to schedule a job on a peer using the date option. Note that it works great on Google Chrome with no issues. 

Here's how it looks like when using Firefox:

![Firefox](https://github.com/user-attachments/assets/5d8c1a42-ccd0-49fc-ad96-42fe31de8011)

Here's how it looks like when using Google Chrome:

![Google Chrome](https://github.com/user-attachments/assets/3e63f31a-ad2b-4434-8b61-1511ce17f0fd)

You can see that Google Chrome allows you to select the time whereas Firefox does not. Which prevents the user from saving the schedule job. However, you can easily overcome this by manually typing out the time in the textbox.

**Comment by donaldzou** [comment]
Hi, thank you for letting me know. Just tested on Safari and it has the same issue too. I will add this to the road map #293 😄 

> and it got me thinking... we are in 2024 and still browsers are not adapting standards, and datetime picker is not even a new feature 😭
