### ISSUE TITLE
latest version errors and autoload

### ISSUE THREAD

**Issue by Johnnykson** [donaldzou/WGDashboard#296]
Hi! Today I installed the latest version and found that sometimes when the system starts the IP address changes to something similar to IPv6
![Снимок экрана 2024-08-11 041822](https://github.com/user-attachments/assets/f380f4d7-8f23-4737-b007-ed060a5f0905)
 
There are no errors during normal startup, but during debugging it shows the following:
![Снимок экрана 2024-08-11 041905](https://github.com/user-attachments/assets/df5e6690-1444-439f-a9d5-29867e83a2c1)

These messages appear in the logs with the frequency with which the update interval is set in the web panel, I don’t know if this was intended or not.
![Снимок экрана 2024-08-11 041951](https://github.com/user-attachments/assets/a2dd3aac-a782-4807-a9b0-ac20db740e12)

**Comment by donaldzou** [comment]
Ah yes, that issue is not a fatal errors. Python 3.12 somehow also do a syntax check on regular expressions and it keep showing although I couldn't locate the issue on other regex parser lol.

Regarding the IPv6.. do you have that setup in your server? It means somehow WireGuard changed your wg interface IP into a IPv6 and edited the `.conf`.. need to look into that.

**Comment by donaldzou** [comment]
One way to test this is turn off the interface, manually edit `/etc/wireguard/wg1.conf` and change the IP back to the IPv4 you had, and turn it back on with`wg-quick up wg1`. See if that still happen?

**Comment by Johnnykson** [comment]
> Regarding the IPv6.. do you have that setup in your server? It means somehow WireGuard changed your wg interface IP into a IPv6 and edited the .conf.. need to look into that.

Yes, indeed, this is WireGuard playing around
![Снимок экрана 2024-08-11 044812](https://github.com/user-attachments/assets/ec63a7d8-eda9-4e8e-a412-1b4cef9dd7c0)

**Comment by donaldzou** [comment]
Maybe checking the service file? Usually the commands are in the line of `ExecStart=....`

**Comment by Johnnykson** [comment]
> Maybe checking the service file? Usually the commands are in the line of `ExecStart=....`

the script for installing WireGuard that I use creates a configuration file in `/root/vg-conf`, I deleted it and cleaned the added IP in `/etc/wireguard/wg1.conf` and now everything is fine
![Снимок экрана 2024-08-11 045800](https://github.com/user-attachments/assets/05314d5b-630c-4cb1-b508-9d79e70345aa)
It's strange that VG didn't do this before and I didn't have to clean its configuration files.

**Comment by donaldzou** [comment]
Huh never heard of that before lol. U can close this comment if everything is working now ;)
