### ISSUE TITLE
Autostart WGDashboard on boot

### ISSUE THREAD

**Issue by Johnnykson** [donaldzou/WGDashboard#297]
I tried to make autostart, it seemed to work, but maybe it's not quite right and needs to be configured further.
`wg-dashboard.service`

```
[Unit]
After=syslog.target network-online.target
Wants=wg-quick.target
ConditionPathIsDirectory=/etc/wireguard

[Service]
Type=forking
PIDFile=/opt/wgdashboard/src/gunicorn.pid
WorkingDirectory=/opt/wgdashboard/src
ExecStart=/opt/wgdashboard/src/wgd.sh start
ExecStop=/opt/wgdashboard/src/wgd.sh stop
ExecReload=/opt/wgdashboard/src/wgd.sh restart
TimeoutSec=120
PrivateTmp=yes
Restart=always

[Install]
WantedBy=multi-user.target
```
![Снимок экрана 2024-08-11 051146](https://github.com/user-attachments/assets/3fe96dd2-6806-495e-b7e3-0dd9c9f26caa)

- Ubuntu 24.04 LTS (GNU/Linux 6.8.0-40-generic x86_64)

**Comment by donaldzou** [comment]
Thanks for providing this! I've pushed the changes to the v4 branch and I'll close now ;)
