### ISSUE TITLE
Problem with large network dialog box add peer

### ISSUE THREAD

**Issue by loriszigliani** [donaldzou/WGDashboard#298]
I configured an interface with class \16 and I encounter a problem in the dialog box when I try to add a peer and the browser freezes. 
I deduce for the calculation in the drop-down menu of available IP addresses that are about 65,534. 
If I use class 24 instead I have no problem.

**Comment by donaldzou** [comment]
Hi! Yes this is a known issue, and it will be fix in the next release. Sorry about that.
