### ISSUE TITLE
v4: APP_PREFIX -> URL prefix does not apply on some API calls 

### ISSUE THREAD

**Issue by shuricksumy** [donaldzou/WGDashboard#301]
**Describe The Problem**
 APP_PREFIX=/wgdashboard
 
 STR:
 1. Try to create new peer
 2. Press to show QR code 
 3. Maybe some other API calls

**Expected Error / Traceback**
```
http://172.30.0.1:10086/wgdashboard/api/downloadPeer/wg2?id=1ErzA7Nj9%2B16hv9VUGJXQIwHtp903Vb8ptKLJIKecDU%3D - 401 Error
but
http://172.30.0.1:10086/api/downloadPeer/wg2?id=1ErzA7Nj9%2B16hv9VUGJXQIwHtp903Vb8ptKLJIKecDU%3D - OK

http://172.30.0.1:10086/wgdashboard/api/getAvailableIPs/wg2? - 401 Error
but
http://172.30.0.1:10086/api/getAvailableIPs/wg2? - OK

```

**Comment by donaldzou** [comment]
Ah yes this should be fixed now. Turns out I forgot to add the prefix to some API endpoint.

**Comment by donaldzou** [comment]
My bad :(

**Comment by shuricksumy** [comment]
Thanks for fix.
I will rebuild docker and let you know the results.

**Comment by shuricksumy** [comment]
All works great now.
Thanks for fix.
