### ISSUE TITLE
gunicorn: command not found in debian 11

### ISSUE THREAD

**Issue by Elyviere** [donaldzou/WGDashboard#310]
**Describe The Problem**
After attempting to update wgdashboard to 4.0 from 3.0.6 it now gives an error when attempting to start it.

**Expected Error / Traceback**
```
[WGDashboard] Starting WGDashboard with Gunicorn in the background.
sudo: ./venv/bin/gunicorn: command not found
```

**To Reproduce**
I installed WGDashboard in a Proxmox LXC container using this install script: 
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/wireguard.sh)"
```
Running it a second time inside the LXC container allows for installing WGDashboard, which I did. It then installed v3.0.6, and so I attempted to update it. I then did the following, in accordance with the readme except I used python 3.12 instead of 3.10.
```
# Debian 11 install instructions
wget https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz && \ 
tar -xvf Python-3.12.0.tgz && \ 
cd Python-3.12.0 && \ 
sudo ./configure --enable-optimizations && \ 
sudo make && \ 
sudo make altinstall

# Update instructions
cd /etc/wgdashboard/src && \
git pull https://github.com/donaldzou/WGDashboard.git --force && \
sudo ./wgd.sh install
```
After that running `./wgd.sh start` started giving the above error. I then attempted a "clean" install by doing the following:
```
cd /etc
mv wgdashboard wgdashboard.old

# Debian 11 install instructions
git clone https://github.com/donaldzou/WGDashboard.git && \ 
cd ./WGDashboard/src && \ 
chmod +x ./wgd.sh && \ 
./wgd.sh install
```

But even then, `./wgd.sh start` gives the same error.

**OS Information:**
 - OS: Debian 11 (Proxmox LXC container)
 - Python Version: 3.12.0

**Sample of your `.conf` file**
N/A as I'm getting the error after I cloned a fresh copy

**Comment by donaldzou** [comment]
Hi! There is an install.txt file under the log folder. Do you mind providing that for me please?

**Comment by Elyviere** [comment]
Looking at that file it's clear there were problems with SSL, although I can't say that I know what the issue is or how to resolve it. Anyway, here is the file: [install.txt](https://github.com/user-attachments/files/16650905/install.txt)

**Comment by Elyviere** [comment]
I set up a completely new LXC with Debian 12 instead, as I only had a single client set up on my old LXC. Installing wireguard v4 there worked with no major issues, other than the service failing to start. Manually starting wgdashboard with `./wgd.sh start` did work however, so I now have a working v4 WGDashboard.

I'll keep my old LXC until this ticket is closed in case you want to debug this at all, but for my part this can be considered resolved.

**Comment by TaKeOVER15** [comment]
i got the same problem, deb 11, proxmox lxc, force upgrade to python 3.10, got the same issue also looks like ssl problem

**Comment by TaKeOVER15** [comment]
not too sure how i got it to work, but i deleted the directory /etc/wgdashboard/  then re-installed the dash again from /root/WGDashbord seem to resolve its self

**Comment by donaldzou** [comment]
> Looking at that file it's clear there were problems with SSL, although I can't say that I know what the issue is or how to resolve it. Anyway, here is the file: [install.txt](https://github.com/user-attachments/files/16650905/install.txt)

> I set up a completely new LXC with Debian 12 instead, as I only had a single client set up on my old LXC. Installing wireguard v4 there worked with no major issues, other than the service failing to start. Manually starting wgdashboard with `./wgd.sh start` did work however, so I now have a working v4 WGDashboard.
> 
> I'll keep my old LXC until this ticket is closed in case you want to debug this at all, but for my part this can be considered resolved.

Hi all, I'm not sure about how Proxmox LXC configure the debian os since I have 0 knowledge on it, please forgive me. It seems like a proxy issue causing the SSL error with pip?

**Comment by donaldzou** [comment]
When I test it with both Debian 11 and 12, I used the official mirror and installed them into a VM and had no problem with it.

**Comment by Elyviere** [comment]
I'm sad to say that I'm also unsure about how exactly an LXC works. It seems this issue was specifically caused by updating from 3.x to 4.0 though, clean installs seem to be working fine based on my and takeover15's experiences above.

**Comment by donaldzou** [comment]
That's weird.. is the issue solved now?

**Comment by donaldzou** [comment]
Will close this issue now :)
