### ISSUE TITLE
delete/restrict peers error

### ISSUE THREAD

**Issue by malikshi** [donaldzou/WGDashboard#311]
**Describe The Problem**

When there is one peer and it's restricted, it causes a WireGuard server error. The default page when clicking on the server remains http://xxxx:10087/configuration/WG0/peers. Set /create as the default if there are no peers or if there's only one peer but restricted.

Additionally, for restricted peers (e.g., 192.168.70.2), the IP address of a restricted peer should not be available when creating a new peer.

**Expected Error / Traceback**
```
112.215.154.214 - - [19/Aug/2024 03:49:50] "GET /api/getWireguardConfigurationInfo?configurationName=SGHE HTTP/1.1" 200 -
[WGDashboard] SGHE Error: '[Peer]' is not in list
[WGDashboard] SGHE Error: '[Peer]' is not in list
112.215.154.214 - - [19/Aug/2024 03:50:04] "GET /api/validateAuthentication HTTP/1.1" 200 -
112.215.154.214 - - [19/Aug/2024 03:50:04] "GET /api/getDashboardConfiguration HTTP/1.1" 200 -
112.215.154.214 - - [19/Aug/2024 03:50:04] "GET /api/getAvailableIPs/SGHE HTTP/1.1" 200 -
[WGDashboard] SGHE Error: '[Peer]' is not in list
[WGDashboard] SGHE Error: '[Peer]' is not in list
```

**To Reproduce**
Please provide how you run the dashboard

**OS Information:**
 - OS: [Debian 12]
 - Python Version: [v3.11]

**Sample of your `.conf` file**
```
Please provide a sample of your configuration file that you are having problem with. You can replace your public key and private key to ABCD...
```

**Comment by donaldzou** [comment]
This is fixed in the latest release. Please run `git pull https://github.com/donaldzou/WGDashboard.git` in WGDashboard's folder
