### ISSUE TITLE
Can't update to 4.0.1 from 4.0

### ISSUE THREAD

**Issue by dwyeraidan** [donaldzou/WGDashboard#312]
Thanks for new version 4.0.  However I can't update to release 4.0.1 when following instruction.
I'm on Ubuntu 22.04

This is output when using ./wgd.sh update - "completes" update but the version is not 4.0.1.

> root@nimbus:/WGDashboard/src# sudo systemctl stop wg-dashboard.service  
> root@nimbus:/WGDashboard/src# ./wgd.sh update
> trap: usage: trap [-lp] [[arg] signal_spec ...]
> ./wgd.sh: line 340: venv_python: command not found
> ------------------------------------------------------------
> [WGDashboard] Are you sure you want to update to the ? (Y/N): y
> [WGDashboard] Shutting down WGDashboard
> [WGDashboard] Downloading  from GitHub...From https://github.com/donaldzou/WGDashboard
>  * branch            HEAD       -> FETCH_HEAD
> trap: usage: trap [-lp] [[arg] signal_spec ...]
> ------------------------------------------------------------
> [WGDashboard] Starting to install WGDashboard
> [WGDashboard] OS: ubuntu
> [WGDashboard] ✔ Python is installed
> [WGDashboard] ✔ Python Virtual Environment is installed
> [WGDashboard] ✔ Python Package Manager (PIP) is installed
> [WGDashboard] Upgrading Python Package Manage (PIP)
> [WGDashboard] Installing latest Python dependencies
> [WGDashboard] WGDashboard installed successfully!
> [WGDashboard] Enter ./wgd.sh start to start the dashboard
> ------------------------------------------------------------
> [WGDashboard] Update completed!
> ------------------------------------------------------------
> root@nimbus:/WGDashboard/src# sudo systemctl start wg-dashboard.service

**And if I try manual update I get this -** 

> root@nimbus:/WGDashboard/src# sudo systemctl stop wg-dashboard.service  
> root@nimbus:/WGDashboard/src# git pull https://github.com/donaldzou/WGDashboard.git --force
> From https://github.com/donaldzou/WGDashboard
>  * branch            HEAD       -> FETCH_HEAD
> Already up to date.
> root@nimbus:~/WGDashboard/src# sudo ./wgd.sh install
> trap: usage: trap [-lp] [[arg] signal_spec ...]
> ------------------------------------------------------------
> [WGDashboard] Starting to install WGDashboard
> [WGDashboard] OS: ubuntu
> [WGDashboard] ✔ Python is installed
> [WGDashboard] ✔ Python Virtual Environment is installed
> [WGDashboard] ✔ Python Package Manager (PIP) is installed
> [WGDashboard] Upgrading Python Package Manage (PIP)
> [WGDashboard] Installing latest Python dependencies
> [WGDashboard] WGDashboard installed successfully!
> [WGDashboard] Enter ./wgd.sh start to start the dashboard
> ------------------------------------------------------------
> root@nimbus:/WGDashboard/src# sudo systemctl start wg-dashboard.service

**and still only launches version 4.0**
<img width="480" alt="Screenshot 2024-08-19 at 20 43 18" src="https://github.com/user-attachments/assets/61a8be52-2cbc-4b90-babf-5895db8fea77">

**Comment by donaldzou** [comment]
I think it's due to my fault of forgetting changing it in the actual code. But if git pull saying it is up to date then you're good !

**Comment by sahara101** [comment]
Hi, for me git pull says up to date. But I still have the message [v4.0.1 is now avaible for update!] and also the version say 4.0

**Comment by donaldzou** [comment]
> Hi, for me git pull says up to date. But I still have the message [v4.0.1 is now avaible for update!] and also the version say 4.0

Hi, yes it is a UI issue. I'm writing an update now :) Will be up in a few minutes.

**Comment by donaldzou** [comment]
This is fixed in the latest release. Please run git pull https://github.com/donaldzou/WGDashboard.git in WGDashboard's folder

**Comment by dwyeraidan** [comment]
Thanks mate! looks good.
