### ISSUE TITLE
Cannot add peer via UI

### ISSUE THREAD

**Issue by dmddeleon** [donaldzou/WGDashboard#316]
**Describe The Problem**
When i add peer using GUI, my dashboard is automatically logout, i already extend the timeout session in configuration file

**OS Information:**
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

**Sample of your `.conf` file**

**Comment by donaldzou** [comment]
Could you please try running it with `.wgd.sh debug` and let me know what the console is printing out please?

**Comment by dmddeleon** [comment]
Hi for your reference

192.168.21.22 - - [20/Aug/2024 07:30:57] "POST /api/authenticate HTTP/1.1" 200 -
192.168.21.22 - - [20/Aug/2024 07:30:57] "GET /api/validateAuthentication HTTP/1.1" 200 -
192.168.21.22 - - [20/Aug/2024 07:30:57] "GET /api/getDashboardConfiguration HTTP/1.1" 200 -
Recursive use of cursors not allowed.
192.168.21.22 - - [20/Aug/2024 07:30:58] "GET /api/getWireguardConfigurations HTTP/1.1" 200 -
192.168.21.22 - - [20/Aug/2024 07:30:59] "GET /api/getDashboardUpdate HTTP/1.1" 200 -
192.168.21.22 - - [20/Aug/2024 07:31:01] "GET /api/validateAuthentication HTTP/1.1" 200 -
192.168.21.22 - - [20/Aug/2024 07:31:01] "GET /api/getDashboardConfiguration HTTP/1.1" 200 -
192.168.21.22 - - [20/Aug/2024 07:31:01] "GET /api/getWireguardConfigurationInfo?configurationName=wg0 HTTP/1.1" 200 -
192.168.21.22 - - [20/Aug/2024 07:31:03] "GET /api/validateAuthentication HTTP/1.1" 200 -
192.168.21.22 - - [20/Aug/2024 07:31:03] "GET /api/getDashboardConfiguration HTTP/1.1" 200 -
[2024-08-20 07:31:04,244] ERROR in app: Exception on /api/getAvailableIPs/wg0 [GET]
Traceback (most recent call last):
  File "/root/wgdashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/wgdashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/wgdashboard/src/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/root/wgdashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/wgdashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/wgdashboard/src/dashboard.py", line 1861, in API_getAvailableIPs
    status, ips = _getWireguardConfigurationAvailableIP(configName)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/wgdashboard/src/dashboard.py", line 1350, in _getWireguardConfigurationAvailableIP
    existedAddress.append(ipaddress.ip_address(a.replace(" ", "")))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'N' does not appear to be an IPv4 or IPv6 address
192.168.21.22 - - [20/Aug/2024 07:31:04] "GET /api/getAvailableIPs/wg0 HTTP/1.1" 500 -
192.168.21.22 - - [20/Aug/2024 07:31:04] "GET /api/getDashboardTheme HTTP/1.1" 200 -
192.168.21.22 - - [20/Aug/2024 07:31:04] "GET /api/isTotpEnabled HTTP/1.1" 200

**Comment by donaldzou** [comment]
Is there existing peers in the configuration already?

**Comment by dmddeleon** [comment]
yes sir, i have existing configuration.

so i installed first the wireguard server, before this UI

**Comment by donaldzou** [comment]
> yes sir, i have existing configuration.
> 
> 
> 
> so i installed first the wireguard server, before this UI

I see.. seems like one of the peer contain an invalid IP address in the `allowed-ips` field. Could you please check with `wg` and see if you could spot it?

**Comment by dmddeleon** [comment]
Okay sir, ill check it. Thanks

**Comment by dmddeleon** [comment]
Thanks for your support. Its working now
