### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by c8agomez** [donaldzou/WGDashboard#318]
Is it possible to load the web as https?

**Comment by DaanSelen** [comment]
Currently, as far as I am aware not, you can put a reverse proxy or apache machine in front which handles the TLS. Good Feature Request!

**Comment by donaldzou** [comment]
There is a way to use CertBot (self-signed certificate) with Gunicorn. I'm doing some testing and will post some updates in here.

**Comment by c8agomez** [comment]
Thanks. At the moment I have done it through apache but it generates some slowness sometimes.

**Comment by c8agomez** [comment]
> Currently, as far as I am aware not, you can put a reverse proxy or apache machine in front which handles the TLS. Good Feature Request!
That's what I had to do to get https. At the moment I am with apache with a self signed certificate as it is a local server not a public domain. Thanks

**Comment by DaanSelen** [comment]
Duplicate of https://github.com/donaldzou/WGDashboard/issues/145 I think

Please reopen if it is not.
