### ISSUE TITLE
no received any packet after connecting

### ISSUE THREAD

**Issue by hadi-dindar** [donaldzou/WGDashboard#319]
after crating wg0 interface in ui new pannel 
when i build a peer and connect it my received packets are 9B only . not work fine

**Comment by malikshi** [comment]
Did you set firewall? Setup pushup and pushdown.

**Comment by hadi-dindar** [comment]
> Did you set firewall? Setup pushup and pushdown.

no , how i should be add pust up and down in new version ?

**Comment by rhenigma** [comment]
> Did you set firewall? Setup pushup and pushdown.

It's PostUp and PostDown config lines inside *.conf files

> > Did you set firewall? Setup pushup and pushdown.
> 
> no , how i should be add pust up and down in new version ?

As far as i know during my testing, it's not accessible via web-ui, you need to do edit it via CLI preferrably using pico/nano/vi/vim for PostUp and PostDown config lines.

**Comment by MoeinNS** [comment]
> after crating wg0 interface in ui new pannel when i build a peer and connect it my received packets are 9B only . not work fine

Did your problem solve?!

**Comment by DaanSelen** [comment]
@hadi-dindar please share your WireGuard configuration. As an example:

```
[Interface]
SaveConfig = true
Address = 10.0.0.1/24
PrivateKey = yBsUJvKtKfv3PwcOzijsvLYnD1WGYWZ8EB7wQldE/W4=
PostUp = iptables -t nat -I POSTROUTING 1 -s 10.0.0.1/24 -o eth0 -j MASQUERADE
PostUp = iptables -I FORWARD -i wg0 -o wg0 -j DROP
PreDown = iptables -t nat -D POSTROUTING -s 10.0.0.1/24 -o eth0 -j MASQUERADE
PreDown = iptables -D FORWARD -i wg0 -o wg0 -j DROP
ListenPort = 51820
```

The PreUp and PostDown lines enable the software-firewall to function as a "forwarder".

**Comment by hadi-dindar** [comment]
> [https://www.cyberciti.biz/faq/how-to-set-up-wireguard-firewall-rules-in-linux](url)

tnx . solved

**Comment by hadi-dindar** [comment]
> @hadi-dindar please share your WireGuard configuration. As an example:
> 
> ```
> [Interface]
> SaveConfig = true
> Address = 10.0.0.1/24
> PrivateKey = yBsUJvKtKfv3PwcOzijsvLYnD1WGYWZ8EB7wQldE/W4=
> PostUp = iptables -t nat -I POSTROUTING 1 -s 10.0.0.1/24 -o eth0 -j MASQUERADE
> PostUp = iptables -I FORWARD -i wg0 -o wg0 -j DROP
> PreDown = iptables -t nat -D POSTROUTING -s 10.0.0.1/24 -o eth0 -j MASQUERADE
> PreDown = iptables -D FORWARD -i wg0 -o wg0 -j DROP
> ListenPort = 51820
> ```
> 
> The PreUp and PostDown lines enable the software-firewall to function as a "forwarder".

thank you Bro

**Comment by DaanSelen** [comment]
Hey @hadi-dindar if it helped, you can mark the issue as solved :)

**Comment by MoeinNS** [comment]
> > [https://www.cyberciti.biz/faq/how-to-set-up-wireguard-firewall-rules-in-linux](url)
> 
> tnx . solved

I have the same problem. How did you solve it?!

**Comment by DaanSelen** [comment]
> > > [https://www.cyberciti.biz/faq/how-to-set-up-wireguard-firewall-rules-in-linux](url)
> > 
> > 
> > tnx . solved
> 
> I have the same problem. How did you solve it?!

By setting the proper iptables masquerading rules with ther postup, and predown lines. See my example config above.
