### ISSUE TITLE
Add a copy or clone function for an existing interface configuration

### ISSUE THREAD

**Issue by DaanSelen** [donaldzou/WGDashboard#322]
A button to clone a existing working interface as a new one which of course some variables to configure such as the name and subnet, but then it can take the preup and postdown

**Comment by donaldzou** [comment]
This can be done easily on the front end 😄

**Comment by DaanSelen** [comment]
> This can be done easily on the front end 😄

I look forward to it, I noticed when I create a new interface using the WGDashboard, it created "empty" PostUp and PreDown entries, this makes the interface pretty much unusable, unless you edit it, which is not possible yet in the web-ui.

See: https://github.com/donaldzou/WGDashboard/issues/302

**Comment by donaldzou** [comment]
But you can add them when you're creating the configuration, it is under the "Optional Setting" at the bottom.

**Comment by DaanSelen** [comment]
> But you can add them when you're creating the configuration, it is under the "Optional Setting" at the bottom.

This is true, but if I do not do that. It does not allow for a change unless manually editing the files, and I feel like this is listed as an optional feel. Like I say in: https://github.com/donaldzou/WGDashboard/issues/302 I think there should be a kind of a template, which is editable? What is your opinion?
