### ISSUE TITLE
Rename Job Scheduler

### ISSUE THREAD

**Issue by DaanSelen** [donaldzou/WGDashboard#323]
Hello @donaldzou 

I think the name `Job Scheduler` is a bit of a misnomer. Maybe more akin to `Usage Limiter` or `Usage Manager` with `Rules` would be more self-explanatory. When I first saw the Job Scheduler I thought I could run commands or scripts on interval on a WireGuard interface, which would not be really logical.

I'd like to hear what you think!

**Comment by donaldzou** [comment]
lol you addressed the elephant in the room 😂😂 I've been thinking about this for the past week and I think is better just to rebrand it on the UI and not touching the codebase and DB file, is just too late

**Comment by DaanSelen** [comment]
> lol you addressed the elephant in the room 😂😂 I've been thinking about this for the past week and I think is better just to rebrand it on the UI and not touching the codebase and DB file, is just too late

This could solve the problem as long as you don't walk into it in the future, because then it will be a even bigger pain! But the feature itself is really well made!
