### ISSUE TITLE
can't login into dashboard after update to 4.0.2

### ISSUE THREAD

**Issue by b0se** [donaldzou/WGDashboard#331]
**the update works good... wgdashboard is updated to 4.0.2 (from [2024 May Release 2 (Hot fix))**

[WGDashboard] Starting to install WGDashboard
[WGDashboard] OS: debian
[WGDashboard] ✔ Python is installed
[WGDashboard] ✔ Python Virtual Environment is installed
[WGDashboard] ✔ Python Package Manager (PIP) is installed
[WGDashboard] Upgrading Python Package Manage (PIP)
[WGDashboard] Installing latest Python dependencies
[WGDashboard] WGDashboard installed successfully!
[WGDashboard] Enter ./wgd.sh start to start the dashboard

**but i can't login into the dashboard:**

192.168.2.100 - - [22/Aug/2024 20:18:07] "GET / HTTP/1.1" 200 -
192.168.2.100 - - [22/Aug/2024 20:18:07] "GET /api/getDashboardTheme HTTP/1.1" 200 -
192.168.2.100 - - [22/Aug/2024 20:18:07] "GET /api/isTotpEnabled HTTP/1.1" 200 -
192.168.2.100 - - [22/Aug/2024 20:18:08] "GET /api/getDashboardVersion HTTP/1.1" 200 -
[2024-08-22 20:18:11,973] ERROR in app: Exception on /api/authenticate [POST]
Traceback (most recent call last):
  File "/etc/wgdashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/wgdashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/wgdashboard/src/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/etc/wgdashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/wgdashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/wgdashboard/src/dashboard.py", line 1503, in API_AuthenticateLogin
    valid = bcrypt.checkpw(data['password'].encode("utf-8"),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid salt
192.168.2.100 - - [22/Aug/2024 20:18:11] "POST /api/authenticate HTTP/1.1" 500 -

---
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

---
uname -r
6.6.21-v8+

---
Python 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0] on linux

---
tested with:

firefox
edge

**Comment by b0se** [comment]
admin:admin also doesn't work :(

**Comment by DaanSelen** [comment]
Hey @b0se I think I solved it. If you know where WGDashboard is installed, go to that directory and search for the `wg-dashboard.ini` file and replace the first 3 lines with:
```shell
[Account]
username = admin
password = $2b$12$AX0vFZ5YmZrZacMF2mkY1Ou6n3Jo3b2CNCckhTEcUaPayxSk60B1m
```
This will change your password back to `admin:admin` it looks like that worked on my test instance!

Let me know what your result is.

**Comment by b0se** [comment]
nice..yepp...can confirm, its working now!
