### ISSUE TITLE
Alpine Linux support

### ISSUE THREAD

**Issue by DaanSelen** [donaldzou/WGDashboard#336]
For the purpose of the Docker container and in general compatability it would be cool if there was Alpine Linux support.

Relevant: https://github.com/donaldzou/WGDashboard/pull/334

**Comment by DaanSelen** [comment]
@NOXCIS Perhaps you can support Donald in this.

**Comment by NOXCIS** [comment]
@DaanSelen @donaldzou the install script is the only thing stopping alpine support, i think. also a bit of the gunicorn venv if i remember correctly.

**Comment by donaldzou** [comment]
> @DaanSelen @donaldzou the install script is the only thing stopping alpine support, i think. also a bit of the gunicorn venv if i remember correctly.

Yes I'm currently testing on that

**Comment by donaldzou** [comment]
Hi all, please view this install script on Alpine linux. We might need to change some commands for Docker but this works on the standard Alpine Linux ISO:

> [!NOTE]
> On line 3, please replace it with the fastest repo for you :)

```bash
setup-interfaces -a ; \
rc-service networking --quiet start ; \
printf "https://mirrors.aliyun.com/alpine/latest-stable/main\nhttps://mirrors.aliyun.com/alpine/latest-stable/community" > /etc/apk/repositories ; \
apk update ; \
apk add wireguard-tools python3 python3-dev git iptables net-tools gcc musl-dev linux-headers sudo ; \
git clone -b v4.0-alpine-linux https://github.com/donaldzou/WGDashboard.git ; \
cd ./WGDashboard/src ; \
chmod +x ./wgd.sh ; \
./wgd.sh install
```

**Comment by donaldzou** [comment]
If this works I'll merge the `v4.0-alpine-linux` branch into main :)

**Comment by NOXCIS** [comment]
@donaldzou 
2024-08-24 04:27:19 Starting the WireGuard Dashboard Docker container.
2024-08-24 04:27:19 Looking for remains of previous instances...
2024-08-24 04:27:19 No remains found, continuing.
2024-08-24 04:27:19 ------------------------------------------------------------
2024-08-24 04:27:19 [WGDashboard] Starting to install WGDashboard
2024-08-24 04:27:19 [WGDashboard] Creating ./log folder
2024-08-24 04:27:19 [WGDashboard] OS: alpine
2024-08-24 04:27:19 [WGDashboard] ✔ Python is installed
2024-08-24 04:27:21 [WGDashboard] ✔ Python Virtual Environment is installed
2024-08-24 04:27:23 [WGDashboard] ✔ Python Package Manager (PIP) is installed
2024-08-24 04:27:23 [WGDashboard] Creating ./db folder
2024-08-24 04:27:23 [WGDashboard] Creating Python Virtual Environment under ./venv
2024-08-24 04:27:28 [WGDashboard] Upgrading Python Package Manage (PIP)
2024-08-24 04:27:19 /opt/wireguarddashboard/src/wgd.sh: line 239: sudo: command not found
2024-08-24 04:27:30 [WGDashboard] Installing latest Python dependencies
2024-08-24 04:27:33 [WGDashboard] WGDashboard installed successfully!
2024-08-24 04:27:33 [WGDashboard] Enter ./wgd.sh start to start the dashboard
2024-08-24 04:27:33 ------------------------------------------------------------
2024-08-24 04:27:33 ------------------------------------------------------------
2024-08-24 04:27:33 [WGDashboard] Starting WGDashboard with Gunicorn in the background.
2024-08-24 04:27:33 /opt/wireguarddashboard/src/wgd.sh: line 308: sudo: command not found

**Comment by NOXCIS** [comment]
@donaldzou How are you testing alpine?

**Comment by donaldzou** [comment]
> Hi all, please view this install script on Alpine linux. We might need to change some commands for Docker but this works on the standard Alpine Linux ISO:
> 
> Note
> 
> On line 3, please replace it with the fastest repo for you :)
> 
> ```shell
> setup-interfaces -a ; \
> rc-service networking --quiet start ; \
> printf "https://mirrors.aliyun.com/alpine/latest-stable/main\nhttps://mirrors.aliyun.com/alpine/latest-stable/community" > /etc/apk/repositories ; \
> apk update ; \
> apk add wireguard-tools python3 python3-dev git iptables net-tools gcc musl-dev linux-headers sudo ; \
> git clone -b v4.0-alpine-linux https://github.com/donaldzou/WGDashboard.git ; \
> cd ./WGDashboard/src ; \
> chmod +x ./wgd.sh ; \
> ./wgd.sh install
> ```

@NOXCIS, I'm using this command. Had to install `sudo` tho

**Comment by NOXCIS** [comment]
@donaldzou Which do you think is better?
Image with C dev kit or Image with precompiled binaries but reduces python venv isolation?

**Comment by donaldzou** [comment]
@NOXCIS  I think is better to have C dev tools pre installed, but leave the Python stuff to be download it fresh? And I feel like installing the C dev tools takes much longer than installing Python venv

**Comment by NOXCIS** [comment]
Build times are not practical for 32bit ARM when installing the dev tools and trying to compile psutil & bcrypt. However I still agree with you on installing the dev tools over giving the venv access to site system packages even if the whole thing is containerized. I'll look into other options so i can keep running this on a potato 🥔 if need be.

**Comment by NOXCIS** [comment]
@donaldzou Nevermind its two lines 
			{ apk update; apk add python3 net-tools python3-dev; printf "\n\n"; } &>> ./log/install.txt 

    apk add --no-cache sudo gcc musl-dev linux-headers && \
prebuilt potato chips are good.

**Comment by donaldzou** [comment]
Should we still keep it if someone used Alpine without Docker😂😂

**Comment by NOXCIS** [comment]
@donaldzou 
<img width="1494" alt="Screenshot 2024-08-24 at 5 49 25 PM" src="https://github.com/user-attachments/assets/45e66587-3a78-4ee4-97e9-4285c4f15c6e">
Two stage docker build

**Comment by DaanSelen** [comment]
> @donaldzou 
> <img width="1494" alt="Screenshot 2024-08-24 at 5 49 25 PM" src="https://github.com/user-attachments/assets/45e66587-3a78-4ee4-97e9-4285c4f15c6e">
> Two stage docker build  

So you want to use multistage builds to compile bcrypt and psutil modules?

**Comment by NOXCIS** [comment]
@donaldzou @DaanSelen 
<img width="1494" alt="Screenshot 2024-08-24 at 6 37 46 PM" src="https://github.com/user-attachments/assets/22a44d25-af2a-4e02-ac8b-7476d99ae25c">
I got a working build just need to do some clean up.

**Comment by DaanSelen** [comment]
> @donaldzou @DaanSelen 
> <img width="1494" alt="Screenshot 2024-08-24 at 6 37 46 PM" src="https://github.com/user-attachments/assets/22a44d25-af2a-4e02-ac8b-7476d99ae25c">
> I got a working build just need to do some clean up.

If you reference the code somewhere I can look at the code later.

**Comment by NOXCIS** [comment]
@DaanSelen Sure i just have to do some clean up, it was alot of trial and error

> > @donaldzou
> > <img alt="Screenshot 2024-08-24 at 5 49 25 PM" width="1494" src="https://private-user-images.githubusercontent.com/26854391/361175305-45e66587-3a78-4ee4-97e9-4285c4f15c6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NDI5ODUsIm5iZiI6MTcyNDU0MjY4NSwicGF0aCI6Ii8yNjg1NDM5MS8zNjExNzUzMDUtNDVlNjY1ODctM2E3OC00ZWU0LTk3ZTktNDI4NWM0ZjE1YzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDIzMzgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMjgxMGQ0ZWQ0YTc0NDQ4OTY4MzNkNGVkYmY5ZGQ4YTkwYTdiNThiZTM3YTUyNzJkNzhiNjI4YzFmZjRjMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NW0YwmkR9VnyQcXDJgMu4IFT--8_QO81sHLDyichsa4">
> > Two stage docker build
> 
> Do you want to use multistage builds to compile bcrypt and psutil modules?

Yeah thats how i got the image to be so small without poking holes in the python venv.

**Comment by NOXCIS** [comment]
@DaanSelen @donaldzou  Alpine Docker build [here](https://github.com/NOXCIS/WGDashboard)
ARM 32 bit takes ~400 seconds to build

**Comment by donaldzou** [comment]
Let me know if the clean up is done and I can merge it into main :)

**Comment by NOXCIS** [comment]
@DaanSelen Im working on a dotenv implement to safely pass environment variables via a .env file. Check out my Wiregate repo prion branch for an example.
