### ISSUE TITLE
no received any packet after connecting

### ISSUE THREAD

**Issue by MoeinNS** [donaldzou/WGDashboard#338]
This is my config 
![Screenshot_20240824_120541_Termius](https://github.com/user-attachments/assets/751c8b4a-eba7-456e-ad1a-3906a99c3c6d)
![Screenshot_20240824_114625_WireGuard](https://github.com/user-attachments/assets/5538a6d8-d6a6-420e-969c-fc584f1962bc)

**Comment by donaldzou** [comment]
Hi, seems like you didn't setup wg0 properly. Please follow these following steps:

1. Find the default interface: `ifconfig`
    - Find the interface that is connected to the outside world, maybe something like `eth0`.. remember the interface name

2. Add this value to the `PostUp`
    ```
    iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o <interface> -j MASQUERADE;
    ```

3. Add this value to the `PostDown`
    ```
    iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o <interface> -j MASQUERADE;
    ```

> [!WARNING]
> **Replace the `<interface>` with the default interface name in your system in step 2 and 3**

4. `wg-quick down wg0`
5. `wg-quick up wg0`

**Comment by MoeinNS** [comment]
tnx bro
