### ISSUE TITLE
Feature to disable the graphs and other animations.

### ISSUE THREAD

**Issue by mzs114** [donaldzou/WGDashboard#351]
**Is your feature request related to a problem? Please describe.**
The dashboard may go slow for large number of peers  due to the animations and the visualizations.

**Describe the solution you'd like**
A toggle feature to disable or enable these optional features will help in such cases.

**Comment by donaldzou** [comment]
I think is alright in my testing. I've test it under around 250 peers for a configuration, but still a good idea :)
