### ISSUE TITLE
Pre Shared key switch

### ISSUE THREAD

**Issue by NOXCIS** [donaldzou/WGDashboard#353]
Can a switch be added for using preshared keys?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by donaldzou** [comment]
Yes, this will be implemented in the next minor release :)

**Comment by NOXCIS** [comment]
@donaldzou Oh and the mobile UI ![image](https://github.com/user-attachments/assets/44b25e7c-6b8d-4118-933b-318bad6d741d)

**Comment by donaldzou** [comment]
Huh.... will look into that

**Comment by donaldzou** [comment]
Fixed ;)
![ScreenRecording2024-10-03at8 26 28PM-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/f32641cd-ef95-4ec3-97ab-77a85b125fb9)
