### ISSUE TITLE
Delete, Rename, Clone and Edit - Configurations

### ISSUE THREAD

**Issue by sanoj-m** [donaldzou/WGDashboard#357]
@donaldzou Love your work, really happy to see an improved version of the dashboard.

I would love to see few options if its possible to do. 
- Even though turning on and off configuration is an option, it would be really nice if there an option to turn off the configuration and edit or rename.
- Delete and clone can be another wonderful feature

Clicking Restrict Peer now deleting the Peer configuration, please look in to it

<img width="210" alt="image" src="https://github.com/user-attachments/assets/4c5c691a-fced-4697-9471-9f58f62547db">

Bring back the version number as it was in V3 underneath the sign-out button.

<img width="79" alt="image" src="https://github.com/user-attachments/assets/7fcff09c-7d86-4d18-b2a2-1dac18d821c3">

Bring back dashboard port changer option in the settings

<img width="284" alt="image" src="https://github.com/user-attachments/assets/f0dccca2-b7a7-44bd-87b9-58c67385346c">

I also feel that, may be you can consider bringing the buttons to save configuration in the setting to be back too. It feels like it didint do anything without a button,(Just a suggesion)

<img width="158" alt="image" src="https://github.com/user-attachments/assets/23e01e8b-3d22-4ee4-b98c-65e8f64a82d2">

**Comment by donaldzou** [comment]
Hi! Thanks for these suggestions! Do you mind telling me what do you mean by this?
> Even though turning on and off configuration is an option, it would be really nice if there an option to turn off the configuration and edit or rename.

**Comment by sanoj-m** [comment]
I mean to say that after turning the configuration off, maybe you can add an option to edit and delete or clone the configuration.

also its nice to see an on off button for the configuration.

**Comment by donaldzou** [comment]
Gotcha... you are able to turn on or off on the configuration, there's a switch on the configuration page

**Comment by alirezaalavi87** [comment]
Sorry for commenting on an old issue.
what @sanoj-m  means is DELETE ing the configuration not disabling it.
I also ran into the same issue. I want to rename or delete a configuration but there is no option for that.
So I tried deleting the file from `/etc/wireguard` and thought WGDashboard will automatically remove it. but it still shows it and I can't do anything with it.

**Comment by donaldzou** [comment]
> Sorry for commenting on an old issue.
> 
> what @sanoj-m  means is DELETE ing the configuration not disabling it.
> 
> I also ran into the same issue. I want to rename or delete a configuration but there is no option for that.
> 
> So I tried deleting the file from `/etc/wireguard` and thought WGDashboard will automatically remove it. but it still shows it and I can't do anything with it.
> 
> 
> 
> ## Update:
> 
>  I restarted the server and now the configuration is gone.
> 
> So I think for DELETE, CLONE, UPDATE ing the configuration, we can do it from the server and then restart wgdashboard. but a better GUI experience would be nice

Hi! Yes I do understand the current version does not have this feature and I've implemented in the next release :) Please stay tuned!
