### ISSUE TITLE
Telegraf -> InfluxDB -> Grafana

### ISSUE THREAD

**Issue by Nautilus34** [donaldzou/WGDashboard#359]
Hello, 

Is there any documentation for monitoring WireGuard with Telegraf and InfluxDB, along with a Grafana graph and a Grafana dashboard?"

Thank you

**Comment by mzs114** [comment]
Hi, there exists prometheus exporter https://github.com/MindFlavor/prometheus_wireguard_exporter, there may a Grafana dashboard for this, I;m not sure how TIG stack fits into that.

**Comment by Nautilus34** [comment]
Thank you
