### ISSUE TITLE
Auto-create pre-shared key on new client profiles

### ISSUE THREAD

**Issue by martin-g-it** [donaldzou/WGDashboard#364]
I noticed after upgrading to version 4 that the pre-shared key on the new client profiles is not generated anymore.

In previous versions, this psk was generated upon flagging; 'Use Pre-shared Key'
![image](https://github.com/user-attachments/assets/c747f6b7-5c3f-4722-8de8-16fe27852e99)

Would be great to have this auto-generated psk in again.

**Comment by NOXCIS** [comment]
@martin-g-it @donaldzou said it would be in the next minor release. Bummer ik.

**Comment by donaldzou** [comment]
Refer to #354
