### ISSUE TITLE
How to change the log directory location?

### ISSUE THREAD

**Issue by mzs114** [donaldzou/WGDashboard#365]
**Is your feature request related to a problem? Please describe.**
Hi, I noticed that it has nested log directory, I wanted to change it to `/var/log` to make use of `logrotate` on Debian. 
I checked `wgd.sh` but could not find the log path there.

**Describe the solution you'd like**
Ability to change the log directory path or location.

**Comment by mzs114** [comment]
Found it, it is in `gunicorn.conf.py`, mostly application access and error log, and not heavy like peer/users logs.

> pidfile = './gunicorn.pid'
wsgi_app = "dashboard:app"
accesslog = f"./log/access_{date}.log"
log_level = "debug"
capture_output = True
errorlog = f"./log/error_{date}.log"

**Comment by donaldzou** [comment]
Hi! There's another installation log file called `install.txt` under the log directory. I believe is set in the `wgd.sh` :)

**Comment by donaldzou** [comment]
> Please do consider whether moving the log location to the `.ini` file helps, as the user then needs to edit at one location.

This is a good idea, will do
