### ISSUE TITLE
Does the delete API call exist in v4.x?

### ISSUE THREAD

**Issue by mzs114** [donaldzou/WGDashboard#367]
**Is your feature request related to a problem? Please describe.**
Hi, I checked the API documentation and could not find the delete call, we are testing WGD out and wanted to bulk delete all the created peers.  Currently we cannot automate testing due to lack of this.

**Describe the solution you'd like**
Please share a way to delete peers in bulk or get a list and then delete. If no API, can we delete from the wgX.conf file and delete from the backend DB(Sqlite) ?

**Comment by donaldzou** [comment]
Hi! Yes it does I'm just too busy to finish the doc. Here is how to use it in JS, for example my configuration name is `wg0`:



```javascript
const headers = new Headers();
headers.append("Content-Type", "application/json");

const requestOptions = {
    method: "POST",
    headers: myHeaders,
    body: JSON.stringify({
        "peers": [
            "public_key_1",
            "public_key_2",
            "public_key_3"
        ]
    }),
};

fetch("/api/deletePeers/wg0", requestOptions)
    .then((response) => response.json())
    .then((result) => console.log(result));
```

Hope this helps :)

**Comment by mzs114** [comment]
Just a side note, would it be easier to use something like Django for this?  Though it is heavy compared to flask, perhaps the unwanted modules can be disabled or removed and it may suffice.
I mean it comes with user management and web UI included, just a thought.

**Comment by donaldzou** [comment]
Well yes Django should be a better solution. The reason I used Flask is it is easy to configure, code and maintain and is minimal to endusers :)

**Comment by DaanSelen** [comment]
> Well yes Django should be a better solution. The reason I used Flask is it is easy to configure, code and maintain and is minimal to endusers :)

So this issue is solved? @mzs114

**Comment by mzs114** [comment]
> > Well yes Django should be a better solution. The reason I used Flask is it is easy to configure, code and maintain and is minimal to endusers :)
> 
> So this issue is solved? @mzs114

Yes, it is resolved, thanks!
