### ISSUE TITLE
I can't log in after upgrading from version 3.0.6

### ISSUE THREAD

**Issue by Larrycher** [donaldzou/WGDashboard#368]
After the update, I go to the authorization page and get an endless loading after entering personal data. I updated via sudo ./wgd.sh install and also via manual installation.

Operating system Ubuntu 22.04.2
Python 3.10.12

[wg0.txt](https://github.com/user-attachments/files/16887857/wg0.txt)

**Comment by b0se** [comment]
https://github.com/donaldzou/WGDashboard/issues/331

;-)

**Comment by Larrycher** [comment]
Thanks b0se
