### ISSUE TITLE
Config file download

### ISSUE THREAD

**Issue by sohrabp72** [donaldzou/WGDashboard#369]
**Describe The Problem**
The Share Link for downloading config files works well using Chrome on PC, Android, and iPhone. Still, when I send the Share Link in messengers or iMessage for people, they tap on it. The link will open by an internal app browser which is Safari or an internal Android browser, tapping on the download icon nothing happens.
Seems the reason is for a warning.
on Chrome, no matter what device is, a warning shows up and asks if the file is not safe to keep, would you like to keep it? but on other browsers, it does not show up. is there any way to enable HTTPS for the panel?

**Comment by donaldzou** [comment]
Hi, you can consider using a Nginx server to reverse proxy the gunicorn app, and configure HTTPS on the Nginx server.
