### ISSUE TITLE
AlmaLinux support

### ISSUE THREAD

**Issue by sohrabp72** [donaldzou/WGDashboard#382]
[WGDashboard] Starting to install WGDashboard
[WGDashboard] OS: almalinux
[WGDashboard] ✔ Python is installed
[WGDashboard] ✔ Found Python 3.11. Will be using [python3.11] to install WGDashboard.
[WGDashboard] ✔ Python Virtual Environment is installed
[WGDashboard] ✗ Sorry, your OS is not supported. Currently the install script only support Debian-based, Red Hat-based OS.
[WGDashboard] Please check ./log/install.txt for more details. For further assistance, please open a ticket on https://github.com/donaldzou/WGDashboard/issues/new/choose, I'm more than happy to help :)
Terminated
The error is clear, please add Almalinux installation support.

**Comment by DaanSelen** [comment]
I am not known with almalinux, do you have suggestions or experience with it? If you know, please let me know!

**Comment by donaldzou** [comment]
Hi @sohrabp72, I've added support on AlmaLinux 9, please follow the instruction on here [🛠 Install](https://donaldzou.github.io/WGDashboard-Documentation/install.html#axsxi2_12) :)

**Comment by moeinrahimi1** [comment]
@donaldzou 
dear sir link is 404

**Comment by donaldzou** [comment]
Hi @moeinrahimi1 sorry we moved our doc to https://docs.wgdashboard.dev/install.html#axsxi2_12 since this year
