### ISSUE TITLE
Return of Endpoint IP

### ISSUE THREAD

**Issue by exvbrn** [donaldzou/WGDashboard#383]
Is it possible to return Endpoint IP to the cards of connected users as it was in version 3? 
This would make it much easier to track users if they are not assigned names. Or make this function switchable depending on the needs?

**Comment by DaanSelen** [comment]
You mean instead of the names in v4 you'd like to see the IP addresses as a identifier?

**Comment by donaldzou** [comment]
I think what @exvbrn means showing the Peer's actual IP address on the UI (I had that back in v3)

**Comment by exvbrn** [comment]
> I think what @exvbrn means showing the Peer's actual IP address on the UI (I had that back in v3)

Yeah, that's what i meant

**Comment by donaldzou** [comment]
Yesss this is in the latest version

![Screenshot 2024-11-12 at 10 50 22 PM](https://github.com/user-attachments/assets/251d9f41-ec28-4f54-a9b6-03228aa939b9)
