### ISSUE TITLE
Generate pre-shared key within the WGDashboard in the peers screen

### ISSUE THREAD

**Issue by schmid-mn** [donaldzou/WGDashboard#392]
When activating the optional feature to use a pre-shared key one needs to enter a pre-shared key. This can be gereated with the wg genpsk in the bash line, but as I am using the WGDashboard I want to stay away from the cmd line.

It would be great to have a button to generate the psk in the peers screen of the dashboard and simply fill the psk-field with it.

**Comment by donaldzou** [comment]
Yes, this feature is already added into the next release :)
