### ISSUE TITLE
Ssl

### ISSUE THREAD

**Issue by 1Uncia** [donaldzou/WGDashboard#394]
Good afternoon.
Is there support for ssl port 443?
I cant do it

**Comment by donaldzou** [comment]
Currently there's no official support using SSL. But you can use Apache/Nginx and CertBot to self host with reverse proxy :)

**Comment by DaanSelen** [comment]
Might be interesting: https://github.com/NginxProxyManager/nginx-proxy-manager

**Comment by 1Uncia** [comment]
Thanks for your job!
