### ISSUE TITLE
Optional Tor Outbound transparent Proxy option like WireAdmin.

### ISSUE THREAD

**Issue by NOXCIS** [donaldzou/WGDashboard#396]
Ive figured out the iptables and tor TransPort with runtime compiled Anti censorship client plugin binaries such as Snowflake, lyrebird(obfs4), and Webtunnel. 

The UI being updated to support optimal configuration would be nice for user behind restrictive networks. I'm not really good at UI, but there is a working demo on my Wiregate project, prion-tor branch.

**Comment by donaldzou** [comment]
Hi @NOXCIS , this sounds great! But at the moment, I'm trying to keep the dashboard simple and easy to use :)

**Comment by donaldzou** [comment]
Should we close this issue?
