### ISSUE TITLE
Modify the iptable-rules

### ISSUE THREAD

**Issue by Profik** [donaldzou/WGDashboard#399]
I ran into an iptable-rules problem. Due to default settings in the wgdashboard/src/iptable-rules folder, the server began to malfunction. 

Eg: 
**MASQUERADE_INTERFACE=eth0** 
many people have a different interface name, I have it called ens3 
**WIREGUARD_LAN=10.0.0.1/24**
I had a different network range of 10.10.10.1/24, because the hosting provider uses 10.0.0.1/24 

As a result, I had to delete this folder in order for everything to work correctly.

**Comment by DaanSelen** [comment]
Is this with the new merger still the case?
