### ISSUE TITLE
Reduce DNS request

### ISSUE THREAD

**Issue by daletman** [donaldzou/WGDashboard#403]
**Is your feature request related to a problem? Please describe.**
The container does send a DNS request every 5 seconds to `xrx4fcdff.homelan`

**Describe the solution you'd like**
A way to disable or reduce the amount of DNS requests

I also wonder where this comes from and why it's needed.
Thank you!

**Comment by donaldzou** [comment]
Hi @daletman , what do you mean by container, do you mean Docker?

**Comment by daletman** [comment]
Sorry for not clarifying: I installed WGDashboard on Proxmox via HelperScripts (so it's in a LXC).

Link: https://tteck.github.io/Proxmox/#wireguard-lxc

**Comment by donaldzou** [comment]
Ah I see.. I think you might need to raise an ticket under the `Promox` repo as they developed the whole container. WGDashboard does not request to DNS at all, it is just a dashboard developed to manage WireGuard configurations. I don't have any relationship with the Promox project and I guess they like this project and decided to integrate it in :)

**Comment by daletman** [comment]
Ok, thank you for the support!
