### ISSUE TITLE
Allow access on restricted peers

### ISSUE THREAD

**Issue by sohrabp72** [donaldzou/WGDashboard#404]
I got some peers Restricted on my panel, after a while I transferred to a new VPS, on the new VPS I tried to allow access to some of those restricted peers, but when clicking on Allow Access of the peer, the web session ended and the browser is redirected to the login page. it seems this is because of different wg0.conf peers on the previous VPS and the new one and internal panel database, as I didn't find those peers in the new VPS's wg0.conf file. Can these peers be removed manually from the db to sort up the panel?

**OS Information:**
 - OS: Ubuntu 22.04
 - Python Version: 3.10

**Comment by donaldzou** [comment]
Hi! Do you mind to run the dashboard in debug mode and recreate the issue and let me know what do you see on the console please?

You can run debug mode with this command:

```
./wgd.sh debug
```

**Comment by sohrabp72** [comment]
`root@WG:~/WGDashboard/src# ./wgd.sh debug
------------------------------------------------------------
[WGDashboard] Starting WGDashboard in the foreground.
Traceback (most recent call last):
  File "/root/WGDashboard/src/dashboard.py", line 1412, in <module>
    DashboardConfig = DashboardConfig()
  File "/root/WGDashboard/src/dashboard.py", line 1121, in __init__
    "remote_endpoint": ifcfg.default_interface()['inet'],
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/ifcfg/__init__.py", line 81, in default_interface
    return Parser(ifconfig=ifconfig)._default_interface(route_output=route_output)
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/ifcfg/parser.py", line 34, in __init__
    self.parse(self.ifconfig_data)
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/ifcfg/parser.py", line 76, in parse
    raise RuntimeError(
RuntimeError: Got results that don't belong to a device`

**Comment by sohrabp72** [comment]
> Here is the output:
> 
> ```
> ------------------------------------------------------------
> [WGDashboard] Starting WGDashboard in the foreground.
> Traceback (most recent call last):
>   File "/root/WGDashboard/src/dashboard.py", line 1412, in <module>
>     DashboardConfig = DashboardConfig()
>   File "/root/WGDashboard/src/dashboard.py", line 1121, in __init__
>     "remote_endpoint": ifcfg.default_interface()['inet'],
>   File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/ifcfg/__init__.py", line 81, in default_interface
>     return Parser(ifconfig=ifconfig)._default_interface(route_output=route_output)
>   File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/ifcfg/parser.py", line 34, in __init__
>     self.parse(self.ifconfig_data)
>   File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/ifcfg/parser.py", line 76, in parse
>     raise RuntimeError(
> RuntimeError: Got results that don't belong to a device```
> 
> **btw my server didn't start correctly again, and my peers are now disconnected :sad**
> ```

I reboot the server and wg-dashboard.service started, thank god,

**Comment by donaldzou** [comment]
This issue seemed fixed. Will close for now :)
