### ISSUE TITLE
Incorrect representation of speed unit (MB/s -> Mb/s)

### ISSUE THREAD

**Issue by sysoppl** [donaldzou/WGDashboard#408]
**Describe The Problem**
Speed is visualised in MB/s which is incorrect, as it should be Mb/s

![image](https://github.com/user-attachments/assets/8b93d717-684c-4187-be41-2aa19265450c)

**Comment by DaanSelen** [comment]
Just to clarify, you mean the difference between MegaBYTES per second and MegaBITS?

**Comment by sysoppl** [comment]
Yes.

**Comment by DaanSelen** [comment]
![image](https://github.com/user-attachments/assets/04542ee3-3350-4422-bbf9-2a8b48267469)
Like this?

**Comment by donaldzou** [comment]
Closing this, I think this is fixed by @DaanSelen. Thank u thank u!

**Comment by DaanSelen** [comment]
I will make a PR once I figured out the gihub actions! Will do
