### ISSUE TITLE
All conf files downloaded shows same Public Key.

### ISSUE THREAD

**Issue by vinaynarasimhan** [donaldzou/WGDashboard#410]
**Describe The Problem**
All conf files downloaded shows same Public Key.

But the file on Dashboard shows proper unique public key. So incase i want to bulk delete a conf using public keys via API, I will have to copy the public keys from gui one by one and then do the api call.

If the conf files get downloaded with correct Public keys. I can run my local script to grep the public keys from  the file i want and run the bulk deletion api call.

**Comment by donaldzou** [comment]
Hi! Could you please elaborate what do you mean by 
> shows same Public Key

**Comment by vinaynarasimhan** [comment]
Got it. Thanks.
