### ISSUE TITLE
IP sorting issue

### ISSUE THREAD

**Issue by sysoppl** [donaldzou/WGDashboard#416]
**Describe The Problem**
Similar to https://github.com/donaldzou/WGDashboard/issues/99
Sorting by IP is wrong

![image](https://github.com/user-attachments/assets/ad0c59d6-b81a-45f9-b6c0-e049112615b3)

**Comment by donaldzou** [comment]
Hi! Yes I'm aware this issue.. Was trying to solve but when it comes to Peers containing multiple IP addresses, or IPv4 mixing with v6, is hard to sorting them "correctly". So I just did a Lexicographic sort to keep it simple ;) But if you have some good idea, please let me know!

**Comment by donaldzou** [comment]
Closing this for now. Will look for a better solution in the future :)
