### ISSUE TITLE
why no work? 

### ISSUE THREAD

**Issue by Buckley27** [donaldzou/WGDashboard#418]
Schedule Jobs 
 
 I set all the exact dates, went through, and have to close access. And it's not responding to anything, I think it's a bug. Please check it.

**Comment by Buckley27** [comment]
I set all the exact dates, went through, and have to close access. And it's not responding to anything, I think it's a bug. Please check it.

**Comment by DaanSelen** [comment]
Can you provide more details on what jobs? What did you specify, and specifically what does not work?

- What did you make?
- What is it not responding to?
- What do you think specifically is a bug?
- Did you wait for about 3 minutes, I think this is a interval WGDashboard checks.
