### ISSUE TITLE
Scan QR code gone ?

### ISSUE THREAD

**Issue by MorphyDK** [donaldzou/WGDashboard#419]
**Describe The Problem**
In your earlier version there was an option to scan the QR config so wireguard was configured  in Wireguard app on IOS?

Don't seem to find that option anymore?

**CLOSE It - LOCATED IT :) **

**Comment by donaldzou** [comment]
Hi, yes I hide it under the context menu of each peer to keep the UI clean :) Please let me know if you have any other questions :)

**Comment by MorphyDK** [comment]
Actually … have 1 😃😃😃.

Homepage you have - with the terminal login…. I love it.

Is that something you have made public? 😃
