### ISSUE TITLE
API: Bulk Add Peers Fails

### ISSUE THREAD

**Issue by TapanBala** [donaldzou/WGDashboard#425]
Seems the documentation for [Bulk Add Peers](https://donaldzou.github.io/WGDashboard-Documentation/add-peers.html#add-peers-in-bulk) has incorrect body parameters mentioned.

The described payload throws an exception since the [addPeers route](https://github.com/donaldzou/WGDashboard/blob/2297d6b85be0ae7144b76e38646bc47aa1db2aad/src/dashboard.py#L1804) is still expecting `public_key`, `allowed_ips` and `preshared_key` in the payload and throws a `KeyError` exception.

As a temporary workaround passing empty values in the payload works:
```
"public_key": "",
"allowed_ips": "",
"preshared_key": ""
```

Also I couldn't find `preshared_key_bulkAdd` being used anywhere.

**Comment by donaldzou** [comment]
Oh nooo.. I must've pushed the `v4.1` documentation to it...my bad

> Also I couldn't find preshared_key_bulkAdd being used anywhere.

Yes and this is also only being used in the next release.

**Comment by vinaynarasimhan** [comment]
@donaldzou and @TapanBala , did you guys also notice, untitled files getting created ? when you try to generate files in large number.

i have noticed with 2000, but even have noticed with 50 numbers occasionally .

This is via web portal.

**Comment by donaldzou** [comment]
> @donaldzou and @TapanBala , did you guys also notice, untitled files getting created ? when you try to generate files in large number.
> 
> i have noticed with 2000, but even have noticed with 50 numbers occasionally .
> 
> This is via web portal.

Hi @vinaynarasimhan , did you choose to use **Pre-Shared Key**?

**Comment by TapanBala** [comment]
> Oh nooo.. I must've pushed the `v4.1` documentation to it...my bad

Ahh no worries. Thanks.
