### ISSUE TITLE
Error Deleted 0 peer(s) 

### ISSUE THREAD

**Issue by Buckley27** [donaldzou/WGDashboard#426]
The error is not deleted 
![image](https://github.com/user-attachments/assets/0c88d62a-8dab-4645-8fa3-ce0b9e23827a)

/etc/wireguard/wg*.conf - 
I can't find the ones I need to delete. There all clear Even 5 pcs, and on the site 7 pcs that I need to delete, of which 2 pcs are unnecessary.

I tried making
wg-quick down wg0
wg-quick up wg0
+
restart and linux. 
 didn't help. How do I need to delete it?

**Comment by Buckley27** [comment]
I decided to reinstall and solved the problem. And for the future, could you please tell me what I need to remove from the config? Just so I know.

**Comment by donaldzou** [comment]
I think WGDashboard got confused when there are duplicate keys... Will look into this issue. I'm glad this issue is solved for you now :)
