### ISSUE TITLE
[QUESTION] Managing Multiple WGDashboard Instances with a Central PostgreSQL Database

### ISSUE THREAD

**Issue by velrino** [donaldzou/WGDashboard#429]
First, CONGRATULATIONS on this amazing tool! 😊

I'm exploring the possibility of using it in a project.

In my case, I'm developing a NestJS API that manages users, and now I also need to manage the WireGuard connections for these users. 

My goal is to use the WGDashboard API to handle the communication with WireGuard.

I have a few questions I'd like to clarify:

1. I noticed that WGDashboard uses SQLite by default, but I need to set up three instances of WGDashboard, one in each region (US, EU, JP). Is it possible to use a single shared **PostgreSQL** database for all instances to centralize management?

2. If a centralized PostgreSQL setup is not recommended, would it be better to keep each instance with its own local SQLite database?

3. Lastly, I would like to confirm this: do I need to send a POST request to `/api/addPeers/<configName>` every time a user connects, or is there a more efficient way to manage connections automatically?

Thank you in advance for your attention!

**Comment by velrino** [comment]
Hi @donaldzou 

Thank you for your detailed response and insights!

I now understand the potential risks of using a centralized PostgreSQL database, especially with the possibility of overlapping configurations and key conflicts. Your explanation about each instance having its own local SQLite database makes sense given WGDashboard’s design. I’ll proceed with that approach.

Also, I appreciate the clarification regarding the need to POST to /api/addPeers/. Knowing that I only need to do it once for each user simplifies things a lot!

Thanks again for your support!

**Comment by donaldzou** [comment]
I'm glad I solved your questions! Anytime!
