### ISSUE TITLE
Multiple networks for "Peer Endpoint Allowed IPs" and multiple DNS

### ISSUE THREAD

**Issue by e-snezhko** [donaldzou/WGDashboard#431]
Impossible to add multiple networks for "Peer Endpoint Allowed IPs" via UI
`0.0.0.0/1, 128.0.0.0/1`
(' 128.0.0.0/1' does not appear to be an IPv4 or IPv6 network)
and multiple DNS
`1.1.1.1, 8.8.8.8`
(' 8.8.8.8' does not appear to be an IPv4 or IPv6 address)
Add only via the wg-dashboard.ini file

**Comment by goerdi** [comment]
hmmm no problem so far
<img width="367" alt="wgdashboard" src="https://github.com/user-attachments/assets/36662c57-8428-4dd7-b56f-63958ac0f86b">

**Comment by donaldzou** [comment]
Hi @e-snezhko, just tested on my side and it doesn't appear to have any problems :)

**Comment by donaldzou** [comment]
Ahh I see what you mean, it is a minor issue. Will fix in the next release.
