### ISSUE TITLE
AmneziaWG Integration

### ISSUE THREAD

**Issue by NOXCIS** [donaldzou/WGDashboard#444]
@donaldzou Will exporting and uploading backups be supported? Yes or No?

**Comment by donaldzou** [comment]
Backup yes :) but not front end export, it is saved under the WireGuard directory in `/etc`

**Comment by donaldzou** [comment]
U can try it out in the `v4.1-dev` branch ;) I've implemented already. You can find it under each configuration, click on the 3 dots on the right and click **Backup & Restore**

**Comment by NOXCIS** [comment]
@donaldzou Tested the dev beach days ago, looks great.
- Heads up for the AmneziaWG integration. The "wg set" and a few other commands overwrites the interface section when creating new peers. 
- a project called amnezia-wg-easy is using a json file to avoid this issue. 
- other than that AmneziaWG(specific version) is compatible with WGDashboard. The peer creation would need to be modified slightly to avoid using "wg set" and try "wg syncconf" like the amnezia-wg-easy project.

**Comment by donaldzou** [comment]
@NOXCIS Thank u thank u... haven't have chance to test it out myself. But looked over the doc and seems like we can do a symbolic link replace `wg` to `awg` and `wg-quick` to `awg-quick`?

**Comment by NOXCIS** [comment]
@donaldzou  I have a working version at [WireGate](https://github.com/NOXCIS/Wiregate/tree/amneziawg). Run the dev-docker-compose.yml on the amneziawg branch.

**Comment by donaldzou** [comment]
Hi @NOXCIS , I wasn't able to run the dev docker compose file...will try later.

In this case, do you still think changes to WGDashboard is required to use AWG, or maybe system level configuration is good enough? (i.e symbolic link)

**Comment by NOXCIS** [comment]
@donaldzou 
- symbloic links works work fine. So far no need to modify the dashboard other than passing the extra amneziaWG arguments to the clients. Which ive already halfassed in my dev demo. 

- There is one issue with the amnezia-go upstream where they forgot to add the address parameter causing it to be removed from the config after running "wg set" I've already submitted the issue and working on a fix in the meantime. Otherwise the dev compose I have works fine with creating peers until the container is restarted due to the missing address line from the config.

**Comment by donaldzou** [comment]
I see.. in this case, should I leave the support AmneziaWG to WireGate or you wanna merge it into WGDashboard?

**Comment by NOXCIS** [comment]
- The best option would be native AmneziaWG support within WGDash with backwards compatibility for standard WireGuard. Maybe with some sort of switch to avoid doing
Symbolic links so WireGuard and AmneziaWG can coexist. 

-Then on WireGate I can ship two base images. One using AmneziaWG and another using WireGuard. With manifest for amd64, arm64, arm/v6/, arm/v7. 

- As for peer creation functionality breaking down after restarts for container that have had peers created. Two actionable options.

1. Some sort of wrapper function around any "wg set" calls. To restore the address in the file.

2. Store and retrieve each config interface address from the db instead of the actual .conf after first run or as long as db is present. 

This would be ideal scenario.

However, someone else would have to add the  Amnezia Build Stage to WG-Dash existing docker image. Due to Wiregate having a conflicting environment setup and the integration of tor transports. 

For bare metal setups, a similar shell function to the build stage with the addition of golang for bin compilation on the host should do the trick. Some host would have the ability to use the kernel module but that should be left to sysadmins for decision, build and install. 

What do you think is the best option?

**Comment by NOXCIS** [comment]
- @donaldzou Nevermind. I patched the dashboard. Wiregate's  WG-Dashboard now has full AmneziaWG support and Backwards Compatability. 
- uses (ip addr show) and write functions to get and reappend the Interface address at all (wg) and (wg-quick) calls with respect to non AmneziaWG configs.
- Same goes for downloading peer configs and backups. 
- Frontend support is upto you.

- Use what works, modify, add support or not.   🤠 

### See 
- [WireGate](https://github.com/NOXCIS/Wiregate/tree/amneziawg)
- [dashboard.py](https://github.com/NOXCIS/Wiregate/blob/amneziawg/WG-Dash/src/dashboard.py), 
- [wgd.sh](https://github.com/NOXCIS/Wiregate/blob/amneziawg/WG-Dash/src/wgd.sh), 
- [entrypoint.sh](https://github.com/NOXCIS/Wiregate/blob/amneziawg/WG-Dash/src/entrypoint.sh) 
- [Dockerfile](https://github.com/NOXCIS/Wiregate/blob/amneziawg/WG-Dash/Dockerfile) 
- [compose.yml](https://github.com/NOXCIS/Wiregate/blob/amneziawg/dev-docker-compose.yml)
