### ISSUE TITLE
WGDashboard Discord, IRC or Reddit?

### ISSUE THREAD

**Issue by DaanSelen** [donaldzou/WGDashboard#449]
Hi Donald,

I was just thinking about the community here, who love the Dashboard, just as I do.
I see a lot of small issues on the Issues board here on GitHub, which could maybe be handled differently?

Perhaps a Community Reddit, Discord or IRC would be helpful?
People could be helped much more easily and faster.

I just wanted to ask if there is a demand for that.

**Comment by donaldzou** [comment]
Hi Daan,

Lol I had this idea several months ago but didn't put it into place. Here is the Discord Server ;)

https://discord.gg/MXDBpuRB
