### ISSUE TITLE
Show .conf without downloading

### ISSUE THREAD

**Issue by aleminkirali** [donaldzou/WGDashboard#453]
Currently, the only way to view the configuration is by downloading the .conf file and opening it in a text editor. While this is manageable on a desktop, it becomes cumbersome on an iOS device.

I primarily use my mobile device to share these configurations with other users. Many of them rely on hotspot Wi-Fi devices where uploading .conf files or scanning QR codes isn't an option. To streamline the process, I often need to copy and paste the configuration directly and send it via chat or email from my mobile device.

This means I need to download all the .conf files on my iOS device and share them over email. However, the recipients still have to open each file one by one in a text editor and paste the content into the router's web configuration.

If I could view and copy the .conf files directly on my mobile device, I would save significant time and effort. It would make my workflow much smoother. As you may know, iOS file management is far from user-friendly, so any improvement in this area would be a huge help.

**Comment by donaldzou** [comment]
Yes this can be done easily. Will implement into this upcoming release :)

**Comment by aleminkirali** [comment]
Thank you so much. Would save me alot of time.

**Comment by donaldzou** [comment]
https://github.com/user-attachments/assets/b32b54ee-e721-465b-a1cf-67e41ccd331a

Resolved ;)

**Comment by aleminkirali** [comment]
@donaldzou Looks amazing. Would it be possible to add a button on that screen to copy to the clipboard? I realize this might be asking a lot.

**Comment by donaldzou** [comment]
Yes that is implemented ;)
