### ISSUE TITLE
Issue with / at start of Public Key? (WireGuard config parsing problem)

### ISSUE THREAD

**Issue by khaberz** [donaldzou/WGDashboard#47]
I am getting the below error when reading in the wg0.conf. Only thing I notice about that particular key is the fact that it starts with a /   
Could that be a problem for the parser?

[2021-08-15 07:00:34,122] ERROR in app: Exception on /get_config/wg0 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "dashboard.py", line 714, in get_conf
    "peer_data": get_peers(config_name, search, sort),
  File "dashboard.py", line 248, in get_peers
    get_all_peers_data(config_name)
  File "dashboard.py", line 209, in get_all_peers_data
    search = db.search(peers.id == i['PublicKey'])
KeyError: 'PublicKey'
10.200.200.32 - - [15/Aug/2021 07:00:34] "GET /get_config/wg0?search= HTTP/1.1" 500 -

**Comment by donaldzou** [comment]
Hi, would you mind provide your .conf WireGuard configuration file? It might have something that causing the crash

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: khaberz ***@***.***>
Sent: Sunday, August 15, 2021 3:08:45 AM
To: donaldzou/wireguard-dashboard ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [donaldzou/wireguard-dashboard] Issue with / at start of Public Key? (#47)


I am getting the below error when reading in the wg0.conf. Only thing I notice about that particular error is the fact that it starts with a /
Could that be a problem for the parser?

[2021-08-15 07:00:34,122] ERROR in app: Exception on /get_config/wg0 [GET]
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functionsrule.endpoint<**req.view_args>
File "dashboard.py", line 714, in get_conf
"peer_data": get_peers(config_name, search, sort),
File "dashboard.py", line 248, in get_peers
get_all_peers_data(config_name)
File "dashboard.py", line 209, in get_all_peers_data
search = db.search(peers.id == i['PublicKey'])
KeyError: 'PublicKey'
10.200.200.32 - - [15/Aug/2021 07:00:34] "GET /get_config/wg0?search= HTTP/1.1" 500 -

**Comment by khaberz** [comment]
What part would you need? It's rather large and I am certainly not going to provide any keys  :-)

**Comment by donaldzou** [comment]
Right😂 could you please check if you have any comments in the configuration file? Other than

[Interface]
Address = .....

...
[Peer]
PublicKey=....

?

**Comment by khaberz** [comment]
Yes, I do, I have a comment for every peer indicating which user the peer belongs to. If that is conflicting with your tool, then I'll have to refrain from using it for now - I have my own script visualising status, which relies on these comment lines. 

Thanks a lot for your help and for writing this tool though!

**Comment by donaldzou** [comment]
I see. I'm still looking for a way to parse the configuration in a more reliable way. Since it is kinda different from a standard ini file format, cuz it has multiple [Peer] sections, so I can only hard coded parsing it and it might cause some bug. But still thanks for give my project a try ;) and I'll continue to improve it.

**Comment by donaldzou** [comment]
Do you mind also provide a little piece of your config file on how you comment in it? Since I would love to solve this problem but I don't know what exactly will cause it :)

**Comment by khaberz** [comment]
Sure, see below. What I find odd is that the error mentions 10.200.200.32 - which is just one of the peers, nothing different about it. As mentioned in the first post, I only noticed the / at the start of the public key for that one...

Note that I know you mention SaveConfig=true as a requirement for changing the config file with your tool. I do not need the tool to change anything, I was just looking to use it for monitoring. I need SaveConfig off in my setup.

[Interface]
Address = 10.200.200.1/24
SaveConfig = false
ListenPort = #####
PrivateKey = XXXXXX

[Peer]
# Name of user 1
PublicKey = XXXXXX
AllowedIPs = 10.200.200.2/32

[Peer]
# Name of User 2
PublicKey = XXXXXX
AllowedIPs = 10.200.200.3/32

**Comment by donaldzou** [comment]
Hi, thank you so much for providing this, I will look into it and get back to you ;) Actually, you can have `SaveConfig = false`. This just allow to create peers directly with WireGuard, like:  `wg set wg0 peer ABCDE...` and then use `wg-quick save wg0` and it will save the newly created peer into the configuration.

**Comment by donaldzou** [comment]
I've been trying to replicate any comment in the configuration file and adding slash `/` t to all of my peers and is seems running just fine. I'm thinking will it be you have a peer's public key is not the same format, because previously there are user who wrote:

```
[Peer]
Publickey = ABCD
...
```
but the dashboard is looking for `PublicKey = ...` and it caused a similar issue. Do you mind checking your configuration? I might need to fix this problem if WireGuard is not case-sensitive on the configuration file. Thank you!

**Comment by khaberz** [comment]
All my keys have the K capitalized. Here's the peer that is mentioned with the comment changed and the key shotrtened:

```
[Peer]
# Name of user 32
PublicKey = /wRrxxxxxxxx=
AllowedIPs = 10.200.200.32/32
```

**Comment by donaldzou** [comment]
Hmmmmm... I really have no idea what caused the crash, I've tried to mess up the the config files with different kind of comments. I'm gonna leave this issue open just in case someone come across this problem too 👍
