### ISSUE TITLE
Backup of Peers

### ISSUE THREAD

**Issue by vinaynarasimhan** [donaldzou/WGDashboard#476]
Is there a way we can backup all peers.

--
Like -

Import / Export of peers in bulk can be a good feature to have.
--

it can be very useful

**Comment by donaldzou** [comment]
Hi! Yes there are.

# To backup peers

Open a configuration on WGDashboard
1. Click the "3 dots" on the right
    - ![Screenshot 2024-11-11 at 2 53 07 PM](https://github.com/user-attachments/assets/fdef4e6b-6da0-4c9d-801f-a221363f50f9)

2. Click "Backup & Restore"
    - ![Screenshot 2024-11-11 at 2 53 27 PM](https://github.com/user-attachments/assets/fb125ac2-7a5a-4fe2-a952-1778af82709a)

3. Click "Add Backup"
    - ![Screenshot 2024-11-11 at 2 53 44 PM](https://github.com/user-attachments/assets/d6919395-fee3-4152-ae01-09a51f24fff7)

# To export peers in bulk

There are 2 ways

## 1st Way

1. Click "Download All" on your configuration page

![Screenshot 2024-11-11 at 2 55 56 PM](https://github.com/user-attachments/assets/e3be0bb5-935e-4849-90b9-aacd1192c9ac)

## 2nd Way

1. Click the "3 dots" on the right
    - ![Screenshot 2024-11-11 at 2 53 07 PM](https://github.com/user-attachments/assets/fdef4e6b-6da0-4c9d-801f-a221363f50f9)

2. Click "Select Peers"
![Screenshot 2024-11-11 at 2 56 40 PM](https://github.com/user-attachments/assets/c8595cd6-0810-4ead-8594-8aa998b284ef)

3. ![Screenshot 2024-11-11 at 2 57 20 PM](https://github.com/user-attachments/assets/6402f18f-47de-4285-b58e-ed960ce812f2)

# Import Peers
Currently there are no feature to import peers through the UI. But you can simply paste the peers into the configuration files located in `/etc/wireguard` and WGDashboard will automatically pick them up :)

**Comment by vinaynarasimhan** [comment]
Great Thanks. Is there any API ..
Create Backup..
List Backup
And the restore Backup.

**Comment by donaldzou** [comment]
Yes, there is.. I'm still finishing the documentation. Please give me few hours and I will post them on the documentation
