### ISSUE TITLE
Interface Improvement: Control and Delete Buttons for Configurations

### ISSUE THREAD

**Issue by mizoil** [donaldzou/WGDashboard#480]
Hello! I have an idea for making it easier to add buttons to the interface. Here are some examples in the screenshots:

First Configuration

This configuration could be improved by adding a name, like “wg0,” with a delete (trash) icon next to it. Why add these buttons? Sometimes I accidentally create a configuration or make a mistake, and I need to delete it. But going to /etc/ can be inconvenient and complicated, especially if there's a bug. That’s why I recommend adding a delete button next to each configuration, along with a confirmation prompt: "Are you sure you want to delete this configuration?" — this would make the interface much more convenient for us.

Here's how it looks in the screenshots:

Screenshot 1
![Удалить корзина](https://github.com/user-attachments/assets/0c429b3b-a3c3-491e-9897-db3569f72ddb)

Screenshot 2
![Удалить корзина 2](https://github.com/user-attachments/assets/f7ca5e93-8693-4301-ad70-c43320acd13f)

Second Client

This client is for users who distribute VPN traffic. It would be helpful to add a button to control the client status (online/offline). If the client is online, traffic is distributed; if the client is offline, the traffic stops. This would be useful because when a service expires, we could simply press "Block," and the client would stop working. The “online” and “offline” buttons would make it easy for me to manage traffic sharing.

Here’s an example in the screenshots:

Screenshot 1
![Снимок](https://github.com/user-attachments/assets/1b6814f9-de4c-4082-8c19-df1d80d7f72b)

Screenshot 2
![Снимок2](https://github.com/user-attachments/assets/e7dce376-c5c0-4670-904b-2c8d340db15e)

What do you think of this idea? I believe it would be well-received! I hope these buttons can be added. Thank you!

**Comment by donaldzou** [comment]
Hi @mizoil, thank you for bringing these suggestions up!

> First Configuration

Currently, you are able to delete configuration by going to the "3-dots" next to the search bar:

![ScreenRecording2024-11-12at9 39 45PM-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/4375c2fc-a85a-4609-bec7-79f307da0565)


> Second Client

You're also able to "Restrict" peers, by blocking but not deleting them

![ScreenRecording2024-11-12at9 44 33PM-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/6dc36443-00a3-48b2-82aa-fcd585b339aa)

Also you can schedule a time to restrict the peer :)
