### ISSUE TITLE
Get Peer Config via API. "Peer does not exist"

### ISSUE THREAD

**Issue by NovianPutera** [donaldzou/WGDashboard#485]
**The Problem**
I want to know why I can't get peer config via API with error "Peer does not exist".

I tried to reinstall WGDashboard (Delete Folder -> reclone -> ./wgd.sh install -> ./wgd.sh start). After that process, API get config peer can be obtained.

However, 1 day later, peer config can't be obtained again with the same error, "Peer does not exist".

Can the symbols in the public key affect the API?

**Error**
No error found at error-xxx.log

**Configuration**
- Public Key: (screenshoot). manual from ``` wg pubkey ```
- Config Name: wg0
- Private Key: manual from ``` wg genkey ```

**OS Information:**
 - OS: Debian 12
 - Python Version: 3.11.2
 - WGDashboard Version: v4.1.0
 
 
![Screenshot 2024-11-13 at 09 06 53](https://github.com/user-attachments/assets/883d2ff6-735d-47c6-b9b8-ddf7c25df4c5)
![Screenshot 2024-11-13 at 09 07 20](https://github.com/user-attachments/assets/6ea1e491-8547-47eb-82d9-ee089d0f2771)

**Comment by DaanSelen** [comment]
I am going to try to recreate this.

**Comment by DaanSelen** [comment]
I can reproduce this, will let you know more once we figure it out!

**Comment by DaanSelen** [comment]
@NovianPutera can you URL encode your peer's public key in the URL? https://www.urlencoder.org/

**Comment by DaanSelen** [comment]
> Sorry for late reply.
> 
> Ahh, after I encode my public key at https://www.urlencoder.org/. And I tried to get the configuration via API, apparently it works.
> 
> The problem is Postman does not encode the "+" sign to URL-encoded format on Query Params.
> 
> Thanks @DaanSelen

I was afraid it was not passing something correctly! Good to hear it works.
