### ISSUE TITLE
[KNOWN BUG] wg-quick will reformat comma separated value  

### ISSUE THREAD

**Issue by donaldzou** [donaldzou/WGDashboard#497]
`wg-quick save wgX` will reformat the configuration file in a weird way.

`demo.conf`
```ini
[Interface]
PrivateKey = abcdE
Address = 10.0.0.1/24,2001:db8::/64
SaveConfig = true  <== I need this to edit configuration on the fly

...  
```

once I run `wg-quick save demo`, then the configuration will get reformatted into

```ini
[Interface]
Address = 10.20.21.0/24
Address = 2001:db8::/64

...
```

and currently WGDashboard is not handling multiple same key configuration. Fixing it in [fix-wg-quick-duplicate-keys](https://github.com/donaldzou/WGDashboard/tree/fix-wg-quick-duplicate-keys)

**Comment by NOXCIS** [comment]
I think one of the amneziawg patches i did over on wiregate resloved this, will have to retrace my steps to find it, will post later.
