### ISSUE TITLE
PresharedKey not added in WG server conf

### ISSUE THREAD

**Issue by guiaume** [donaldzou/WGDashboard#498]
**Describe The Problem**
When adding a new peer with a PresharedKey, this PresharedKey is added in the client configuration, but not in the server configuration
This concerns both the addition of a simple client or the mass addition
On the other hand, if you disable access for this peer, then re-enable it, the PresharedKey will be added.
This requires you to restrict access and then re-authorize access each time you create a new peer

**Expected Error / Traceback**
```
...
```

**To Reproduce**
Just add a new peer, then check the wireguard conf file, you'll see the the new peer, but without the PresharedKey 

**OS Information:**
 - OS: Debian 11 / Debian 12
 - Python Version: v3.10.15 / v3.11.2

**Sample of your `.conf` file**
```
[Interface]
Address = 10.0.5.1/24
SaveConfig = true
PostUp = ...
PostDown = ...
ListenPort = ...
PrivateKey = ...

# [New peer just added]
[Peer]
PublicKey = ...
AllowedIPs = 10.0.5.30/32
```

**Comment by donaldzou** [comment]
Hi! Can you try to stop WHDashboard, then `git pull` and restart and see if this issue is solved?

We just fixed this issue earlier today :)

**Comment by guiaume** [comment]
Yes, indeed, it is fixed, I was just doing that because in the meantime I saw that there was a branch `fix-preshared-key`.
Sorry, I had not searched enough before posting.
Thank you, and by the way congratulations for this great project.

**Comment by donaldzou** [comment]
No problem! We should’ve posted a small release but wanna wait for few other buys to get fixed before doing that.

I’m glad you like this project :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
