### ISSUE TITLE
Web GUI cannot be accessed if VPN connection is established

### ISSUE THREAD

**Issue by Ferohers** [donaldzou/WGDashboard#508]
**Describe The Problem**
I use the docker version. It works without an issue. However the GUI cannot be accessed if VPN is active on the computer. I think it might be related to iptables.

**To Reproduce**
Connect the VPN. Go visit the GUI.

**OS Information:**
 - OS: [e.g. Ubuntu 24.04]

**Sample of your `.conf` file**
docker compose default

**Comment by DaanSelen** [comment]
I can reproduce. And because of the routing... Can you try accessing `10.0.0.1:10086` once you are connected?

**Comment by Ferohers** [comment]
Yes, 10.0.0.1:10086 works.
