### ISSUE TITLE
Update .. dont update?

### ISSUE THREAD

**Issue by MorphyDK** [donaldzou/WGDashboard#517]
**Describe The Problem**
I see a message in the gui that  [v4.1.0 is now avaible for update!](https://github.com/donaldzou/WGDashboard/releases/tag/v4.1.0)

@ https://github.com/donaldzou/WGDashboard/releases/tag/v4.1.0 im going in manually to /etc/wgdashboard/src

Running ./wgd.sh install 

Output: 

root@wireguard:/etc/wgdashboard/src# ./wgd.sh install
------------------------------------------------------------
[WGDashboard] Starting to install WGDashboard
[WGDashboard] OS: debian
[WGDashboard] ✔ Python is installed
[WGDashboard] ✔ Python Virtual Environment is installed
[WGDashboard] ✔ Python Package Manager (PIP) is installed
[WGDashboard] WireGuard is already installed.
[WGDashboard] Upgrading Python Package Manage (PIP)
[WGDashboard] Installing latest Python dependencies
[WGDashboard] WGDashboard installed successfully!
[WGDashboard] Enter ./wgd.sh start to start the dashboard
------------------------------------------------------------

**To Reproduce**
I use: systemctl restart wg-dashboard.service

**OS Information:**
Proxmox container: 

Linux version 6.8.12-4-pve (build@proxmox) (gcc (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-4

After installation - I still see that there is an update available?

**Comment by donaldzou** [comment]
Hi! Can you try the following:

```
systemctl stop wg-dashboard.service

./wgd.sh update
./wgd.sh install

systemctl start wg-dashboard.service
```

**Comment by MorphyDK** [comment]
Worked :)

Thank you Donald.

Just a minor question. When im connected - I can access my LAN and all my services . But when I do a whatsmyip look up, I dont see my wanip if im connected from my phone? I see the isp adress? But its working fine.

**Comment by donaldzou** [comment]
Do you mean by you're not seeing your "server"'s public IP?

**Comment by MorphyDK** [comment]
Yes :)

**Comment by donaldzou** [comment]
do you mind showing your peer's configuration? you can remove all keys

**Comment by MorphyDK** [comment]
![IMG_7323](https://github.com/user-attachments/assets/04548d00-231a-47b3-b947-77e10df57a67)
 Herr you go :)

**Comment by MorphyDK** [comment]
![IMG_7323](https://github.com/user-attachments/assets/928d2969-ced7-4c58-b9df-f471e6695103)
Here you go :)

**Comment by DaanSelen** [comment]
> Worked :)
> 
> Thank you Donald.
> 
> Just a minor question. When im connected - I can access my LAN and all my services . But when I do a whatsmyip look up, I dont see my wanip if im connected from my phone? I see the isp adress? But its working fine.

ISP address, that's correct. Whatsmyip or ifconfig.me check the PUBLIC ip address you are sending traffic from. So your router, not your WireGuard machine (unless its directly on the internet)

**Comment by MorphyDK** [comment]
Hi @DaanSelen 

Yes and no :) . 

I get the ISP IP adress from my cellular phone provider ( 5G network ). 

When I log into my VPN  - and I use whatsmyip , I should see my IP of my WAN ISP at home and not my 5G network.
I can access my LAN servers - but my WAN IP at home is not showed to me via whatsmyip.

Rather odd.

**Comment by donaldzou** [comment]
@DaanSelen I think what @MorphyDK meant internet traffic is not going through the WireGuard tunnel.

I think I found the reason.. in the image below, you have **Endpoint Allowed IPs** set to `192.168.0.0/24`, which means **only** traffic that is point to any IP from `192.168.0.1` to `192.168.0.254` will go through the tunnel. If you would like to have all traffic to go through, you can have it set to `0.0.0.0/0` which means traffic to every IPv4 address will go through the tunnel :)

<img width="795" alt="Screenshot 2024-11-25 at 5 14 49 PM" src="https://github.com/user-attachments/assets/1df43aa0-e081-4d1b-bb17-f807b128cd88">

**Comment by DaanSelen** [comment]
> @DaanSelen I think what @MorphyDK meant internet traffic is not going through the WireGuard tunnel.
> 
> I think I found the reason.. in the image below, you have **Endpoint Allowed IPs** set to `192.168.0.0/24`, which means **only** traffic that is point to any IP from `192.168.0.1` to `192.168.0.254` will go through the tunnel. If you would like to have all traffic to go through, you can have it set to `0.0.0.0/0` which means traffic to every IPv4 address will go through the tunnel :)
> 
> <img alt="Screenshot 2024-11-25 at 5 14 49 PM" width="795" src="https://private-user-images.githubusercontent.com/25237201/389456470-1df43aa0-e081-4d1b-bb17-f807b128cd88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjcwMDgsIm5iZiI6MTczMjUyNjcwOCwicGF0aCI6Ii8yNTIzNzIwMS8zODk0NTY0NzAtMWRmNDNhYTAtZTA4MS00ZDFiLWJiMTctZjgwN2IxMjhjZDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA5MjUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZDkwNzU0MGNhMjg1ZTE4Y2RhNTM4MDk4ZWJiNGMzYzcxZmZiM2YxMjhmYmViMmUwOWQ4YzZlMjBjMGE1NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mmuznpLmDyjcexXVWbltrV0XUj5kizujD8RmPFJ_BNI">

Yeah this is probably it. Donald explained it well.

**Comment by MorphyDK** [comment]
YES :) worked like a charm .

Thanks for great support guys. 

Worked perfectly and now its working. Couldnt remember what in earth I made wrong lol

**Comment by DaanSelen** [comment]
> YES :) worked like a charm .
> 
> Thanks for great support guys.
> 
> Worked perfectly and now its working. Couldnt remember what in earth I made wrong lol

Probably when creating the peer you placed your home network in Allowed IP's because maybe you thought "It's allowed to access that". But WireGuard interpreters that differently. Good to hear it works now!

**Comment by MorphyDK** [comment]
Exactly :)
