### ISSUE TITLE
Get peer share link API

### ISSUE THREAD

**Issue by sohrabp72** [donaldzou/WGDashboard#533]
this API based on this [doc](https://donaldzou.github.io/WGDashboard-Documentation/get-share-peer-url.html), will create a link and send just shareID back in response, I managed to contact the ShareID to the end of the web panel URL to make it just clickable in output, when I get the link for the first time, everything is fine when it comes to getting the same link for the second time, it says the share link has been created, remove it first to get another one.
what if we get the same link if it has not expired yet?
It can be added to the next update, I know handling the expiration time makes the context a bit complex but the panel can detect if the shareid has not expired yet, ignore the expiration date sent in the body of the request.

**Comment by sohrabp72** [comment]
> Hi! basically what you need to request is:
> 
> 1. https://donaldzou.github.io/WGDashboard-Documentation/create-share-peer-url.html use this to create a link first and specify the expiry date
> 2. Then use this https://donaldzou.github.io/WGDashboard-Documentation/get-share-peer-url.html to actually get the link

I used the get share peer, seems it is a bug then.

**Comment by donaldzou** [comment]
Hmmm i did it on my side and it appear to be all good..

```bash
donaldzou@wg:~$ curl --location http://wg.local:10086/api/sharePeer/create --header 'wg-dashboard-apikey: XArBQbS_PKDlSJDH
L7VVyfoIa1d7tvFiZzjHxEQpCQ4' --header 'Content-Type: application/json' --data '{
        "Configuration": "demo",                  
        "Peer": "43n5oLXCdaNysS/+kaByKrXIlE94oV14b+ibkoHz82Y=",
        "ExpireDate": "2024-11-30 22:50:00"
}'
```
```json
{"data":[{"Configuration":"demo","ExpireDate":"2024-11-30 22:50:00","Peer":"43n5oLXCdaNysS/+kaByKrXIlE94oV14b+ibkoHz82Y=","ShareID":"d016f1a4-7daf-4049-bdbf-79792aa220be"}],"message":null,"status":true}
```
```bash
donaldzou@wg:~$ curl --location http://wg.local:10086/api/sharePeer/get?ShareID=d016f1a4-7daf-4049-bdbf-79792aa220be --header 'wg-dashboard-apikey: XArBQbS_PKDlSJDHL7VVyfoIa1d7tvFiZzjHxEQpCQ4'
```
```json
{"data":{"file":"[Interface]\nPrivateKey = GPfNlgbI6Y1GWjaU18AgMuwiOYWFq957DEIFZNRM2Wk=\nAddress = 10.20.31.1/32\nMTU = 1420\nDNS = google.dns, 1.1.1.1\n\n[Peer]\nPublicKey = tS4DinqVLd8b2WihJJAJxeRHd7O0Y+Wqt9YHiT1Yizk=\nAllowedIPs = 0.0.0.0/0\nEndpoint = 10.0.3.6:51889\nPersistentKeepalive = 21\n","fileName":"BulkPeer#1_20241126_212258_demo"},"message":null,"status":true}
```

**Comment by donaldzou** [comment]
Ahhh okay I got your point, and yes I agree it is a bit annoying. Will change in the next release :)

**Comment by donaldzou** [comment]
Will close for now ;)
