### ISSUE TITLE
Can't login with default password

### ISSUE THREAD

**Issue by seanbts** [donaldzou/WGDashboard#537]

**Comment by seanbts** [comment]
All sorted!

**Comment by donaldzou** [comment]
Hi! May I still ask what happened?

**Comment by seanbts** [comment]
Hi Donald,

Firstly congrats on a great WG dashboard, great work! I was having an issue logging in but it was something wrong i was doing so all sorted now.

Can I ask you a question on config, I've set your dashboard on a VM, port forwarded 51821 ( thats the port i'm using in your software ) on our PFsense router, and configured a peer for my iphone. From my iphone i can ping the tunnel address 
( 10.152.77.1) but can't ping or connect to anything on the local LAN ( 192.168.1.xxx ) attached is a screenshot of the peer config, do i have this correct, or is there something wrong? Thanks for your help.
![peer](https://github.com/user-attachments/assets/7901af62-9be2-4547-811f-6484f25ec8e4)

**Comment by donaldzou** [comment]
Hi, sorry for the delay. When you iPhone's tunnel is turned on, do you see it is connected on WGDashboard?

**Comment by donaldzou** [comment]
Also, do you have any `PostUp` rules set in your `wgX.conf`?

**Comment by seanbts** [comment]
Hi, yes on WGDashboard iphone is connected. From the Iphone i can ping the tunnel IP ( 10.152.77.1 ) but not the local lan ( 192.168.1.xxx ). Attached are 2 screenshots showing the config on WGDashboard. OS is fresh install of Debian. I SSH in to Debian and did a service iptables status and the result is  iptables.service could not be found. I wonder do i need to install iptables so the Postup / down will work? Thanks
![WG_2](https://github.com/user-attachments/assets/dddd492b-b350-4966-956c-cf04fe57d2c3)
![WG_1](https://github.com/user-attachments/assets/e849cf99-f9d6-4af6-ba77-f00f8845e6f1)

**Comment by donaldzou** [comment]
Hmm that's weird, theoretically it should work.. how did you "Ping" after you connected?

**Comment by seanbts** [comment]
Using Ping app on iPhone, this is the result ![image](https://github.com/user-attachments/assets/71cbba6a-6f79-4cb5-a11b-642788df4c05)

**Comment by donaldzou** [comment]
Gotcha, one thing we can test is to change **Endpoint Allowed IPs** on your peer to `0.0.0.0/0` and try again?

**Comment by seanbts** [comment]
Just tried that on the endpoint allowed IPs 0.0.0.0/0 , same result - can ping 10.152.77.1 but not 192.168.1.250 and also don't have internet on the iPhone when set 0.0.0.0/0

**Comment by donaldzou** [comment]
Try run this on your server.. `sudo echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf`

> ...don't have internet on the iPhone when set 0.0.0.0/0

and yes you can set it back to your original value, and try the solution above ;)

**Comment by donaldzou** [comment]
also if you'd like, you can join our Discord server for a faster response (email push on GitHub sucks) lol. The link is in the Readme file :)

**Comment by donaldzou** [comment]
Will close this issue for now as it is resolved over at Discord server ;)
