### ISSUE TITLE
Get peers list and peer info by IP

### ISSUE THREAD

**Issue by nabiullin** [donaldzou/WGDashboard#541]
Hello. Are there any plans to add methods to API to get information about peers in configurations? It should be nice to get by API more information)
We want to provide this info to thirdparty code by API in our service)

**Comment by donaldzou** [comment]
Hi! Yes sorry I forgot to add to the doc:

`GET /api/getWireguardConfigurationInfo?configurationName=`

**Comment by nabiullin** [comment]
oh, thanks) It works

**Comment by nabiullin** [comment]
comment to close) /api/getWireguardConfigurationInfo?configurationName= where name is configuration name works perfect. Thank you
