### ISSUE TITLE
Peer puts off a rude principal

### ISSUE THREAD

**Issue by edsonblwolf** [donaldzou/WGDashboard#544]
**Describe The Problem**
When I add a peer it takes the (Endpoint Allowed IPs (Required)) of the main network and not the network that I am registering the peer.

**Expected Error / Traceback**
```
Please provide the error traceback here
```

**To Reproduce**
![Captura de tela_2024-12-05_12-12-07](https://github.com/user-attachments/assets/2e3050bb-b44a-43e1-b03b-6759e542ae2f)

**OS Information:**
 - OS: Debian 12
 - Python Version: 3.11.2

**Comment by donaldzou** [comment]
Hi! That would be the default value of what you set in **Settings** > **Peer Settings**

**Comment by edsonblwolf** [comment]
Yes I understand. But in my case I have several networks. 10.60.60.0/24, 10.61.61.0/24.
Each client uses a network.
![Captura de tela_2024-12-08_15-16-20](https://github.com/user-attachments/assets/1ef25868-1d49-44dd-9014-c79d43c622a1)

**Comment by donaldzou** [comment]
Ahh gotcha.. at this moment it will apply to all peers. I will figure something out to overcome your issue :)

You can also edit them individually.. I know it might be tedious😭

**Comment by donaldzou** [comment]
Will close this issue for now
