### ISSUE TITLE
Active or default (pre-shared key) hint

### ISSUE THREAD

**Issue by edsonblwolf** [donaldzou/WGDashboard#545]
![Captura de tela_2024-12-05_12-17-39](https://github.com/user-attachments/assets/302c160d-2343-4e54-a5e0-0f3058e57bf3)

**Comment by donaldzou** [comment]
Hi! I'm not sure what do you mean, would you elaborate that?

**Comment by edsonblwolf** [comment]
When dictionary pair, (Pre-Shared Key), come active by default.

**Comment by donaldzou** [comment]
Hi! This feature is not frequently used, so it won't turn on by default.

**Comment by edsonblwolf** [comment]
I understand. It would be nice to have an option in settings, to activate by default or not.

**Comment by donaldzou** [comment]
For sure, will add this feature in the next release :)
