### ISSUE TITLE
WGD wipes server Interface config on new peer or stopping wg0 instance

### ISSUE THREAD

**Issue by ikidd** [donaldzou/WGDashboard#81]
Ubuntu 20.04

Twice now I've had wgd remove the privatekey and IPAddress values from the wg0.conf file, then crash the webapp.  First time was when I created a peer under the newly created wg0 instance, and then again when I stopped the wg0 instance via the web interface.

logfile: https://gist.github.com/ikidd/a148be0d9e4996119fadfc661db29519

**Comment by donaldzou** [comment]
Could you provide a sample of your configuration file?

**Comment by ikidd** [comment]
Of the wg config or the wgd config?  Just a basic config of the wg server:

[Interface]
Address = 10.10.10.1/24
PrivateKey = <privkey>
ListenPort = 51822
SaveConfig = true

[Peer]
PublicKey = <pubkey>
AllowedIPs = 10.10.10.5/32

The config for wgd is just the default one created by the script.

**Comment by ikidd** [comment]
So I've rebooted and tried it a few times, now it seems to be working and stable.  I'll reopen if it goes sideways again.

**Comment by donaldzou** [comment]
> So I've rebooted and tried it a few times, now it seems to be working and stable. I'll reopen if it goes sideways again.

I'm sorry this happened to you, if you encountered a similar problem, please let me know :)
