### ISSUE TITLE
WGDashboard will not start anymore

### ISSUE THREAD

**Issue by b0se** [donaldzou/WGDashboard#83]
./wgd.sh debug
-----------------------------------------------------------
**| Starting WGDashboard in the foreground.                  |
Traceback (most recent call last):
  File "/etc/wgdashboard/src/dashboard.py", line 1167, in <module>
    update = check_update()
  File "/etc/wgdashboard/src/dashboard.py", line 1154, in check_update
    data = urllib.request.urlopen("https://api.github.com/repos/donaldzou/WGDashboard/releases").read()
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded**

OS: 
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by donaldzou** [comment]
Hi, can you try to execute this command into your PI: `curl https://api.github.com/repos/donaldzou/WGDashboard/releases` and to see if it will give out an output.

**Comment by edmundasa** [comment]
Hi, I have same issue as @b0se.
Here is curl output:
`curl https://api.github.com/repos/donaldzou/WGDashboard/releases
{"message":"API rate limit exceeded for 78.31.187.47. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}`

78.31.187.47 - is my IP. In all I would say I used setup script maybe 3 times in 1 hour time... Not much I would say.

**Comment by donaldzou** [comment]
> Hi, I have same issue as @b0se. My OS - Ubuntu 20.04.3 LTS
> Here is curl output:
> `curl https://api.github.com/repos/donaldzou/WGDashboard/releases {"message":"API rate limit exceeded for 78.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}`
> 
> 78.xxx.xxx.xxx - is my IP. In all I would say I used setup script maybe 3 times in 1 hour time... Not much I would say.

Hi, I'm so sorry for you encountering errors, could you try to execute this following command and send me the full response please? You can remove any sensitive information: `curl -i https://api.github.com/repos/donaldzou/WGDashboard/releases/lateset`

**Comment by donaldzou** [comment]
@edmundasa I've been reading the Github documentation, and i think the only other reason is someone using the same IP address who requested github API more than 60 times per hour (github limitation)

**Comment by edmundasa** [comment]
Hi @donaldzou thanks for looking into it. I get that, but could you explain why requests to Github go so often? Is it some kind of check? 
Can it be made to have delay or something? 
Or for it not to be breaking step?

P.S> I managed to start Dashboard by adding my Github token to ./wgd.sh script to get more API calls.
Here is example:
`curl -H "Authorization: token OAUTH-TOKEN" https://api.github.com/user`

Thanks.

**Comment by donaldzou** [comment]
Hi @edmundasa, I'm glad is working for you now. So in the current version, I will let the dashboard request to Github to see if there's any new release on the dashboard whenever you go to the `index` page. I think i might need to remove the function and just let it check everytime you start the dashboard, i guess that would be the safest way.

**Comment by xiki808** [comment]
Same issue here

**Comment by donaldzou** [comment]
This issue has been solve in the next release ;)
