### ISSUE TITLE
Kill switch at signing page

### ISSUE THREAD

**Issue by Pantamis** [donaldzou/WGDashboard#85]
**Is your feature request related to a problem? Please describe.**
I find the dashboard really useful as a VPN kill switch. If I want to make my home network unreachable remotely, I just log on the app and tap the switch of the main wg configuration. This can be useful if you are physically under duress outside, you disable wireguard from the dashboard quickly and the bad guys cannot access anything even if they are threatering you. You will be able to restore the VPN later at home.

The problem is that I need to be logged on the dashboard to do that, it takes quite a bit of time to log in and tap the switch.

**Describe the solution you'd like**
I would find really cool to have a kind of "emergency button" on the signin page of the dashboard. It could be one emergency button for each configuration to disable them, or it can be only one switch to disable everything.

If you don't like the idea of having such button on the signin page, you can unset it by dfault and add an option to display it on the signin page for people who wants to have that.

It needs to be large enough but maybe not too obvious that this is a kill switch (like the text on the button could be just the name of the wireguard configuration it would kill)

**Comment by donaldzou** [comment]
Hi, this is an interesting idea. I'll look into it and to see how can I implement this ;) Thank you!
