### ISSUE TITLE
Block peer feature

### ISSUE THREAD

**Issue by xiki808** [donaldzou/WGDashboard#88]
**Is your feature request related to a problem? Please describe.**
Nope not a problem.

I like this dashboard solution! It's very neat and well presented, thank you! 

I think it would be a good idea to introduce a block feature to peers, so the user does not need to delete a peer but simply temporarily block it. Would be quite handy as the peer doesn't need to apply the configuration again on their device, but instead it's all controlled from the server/dashboard.

**Comment by donaldzou** [comment]
Hi, sorry for a super late response. I will add this to the next release suggestion #129  :) I think this is a great idea
