### ISSUE TITLE
Add the possibility to create a new Wireguard server

### ISSUE THREAD

**Issue by Willena** [donaldzou/WGDashboard#92]
**Is your feature request related to a problem? Please describe.**
Not at all

**Describe the solution you'd like**
This is quite simple: I'd like to see a dedicated page for creating a new WG server.

**Comment by donaldzou** [comment]
Hi! Actually I'm planning to implement this in my next major release, since I'm super busy recently, I might need some time to finish it ;) Stay tuned!!

**Comment by donaldzou** [comment]
Hi, I'm sorry to inform you that this functionality would not be in the next release. I tried to implement it, but I couldn't find good way to safely **edit** the server after it got created. I will definitely try some other way 😢
