### ISSUE TITLE
IP Sorting range issues

### ISSUE THREAD

**Issue by barryboom** [donaldzou/WGDashboard#99]
**Describe The Problem**
When using the sort peers by Allowed IP it seems to fail to recognise early / single digit IPs as attached 

instead of going 10.1.1.1 , 10.1.1.2 it seems to start at 10.1.1.10 then place 10.1.1.2 and the start of the .20 ranges

screenshots attached

**To Reproduce**
server with maybe 20+ like mine i have over 50 Peers, change to sort peers by Allowed IPs then review sequeance 

**OS Information:**
 - OS: [e.g. Ubuntu 20.04.3]
 - Python Version: [e.g v3.7]

**Sample of your `.conf` file**
```
Please provide a sample of your configuration file that you are having problem with. You can replace your public key and private key to ABCD...
```
[Interface]
PrivateKey = ABCDEFGHIJKLMNOP=
Address = 10.9.0.6/24
DNS = 8.8.8.8,8.8.4.4
[Peer]
PublicKey = ABCDEFGHIJKLMNOP=
AllowedIPs = 0.0.0.0/0, ::/0 
Endpoint = MYSERVERIP:52080
PersistentKeepalive = 25
![AlllowedIP](https://user-images.githubusercontent.com/67483859/140646950-22e3604c-8b66-401c-912e-8df0af86de23.png)
![AllowedIPsorting](https://user-images.githubusercontent.com/67483859/140646952-2db3c068-a894-4233-92bd-d21d68c7578a.png)

**Comment by donaldzou** [comment]
Hi, sorry for the super late reply. I used the `sort` function in Python and I believe it will sort it in lexicographic order. I will fix this in the next major release.

**Comment by donaldzou** [comment]
This issue has been solved in the next release ;)
